- src/dataAccess/db/credentials.ts
- src/dataAccess/db/modificationRequest.ts
- src/dataAccess/db/passwordRetrieval.ts
- src/dataAccess/db/project.ts
- src/dataAccess/db/projectAdmissionKey.ts
- src/infra/sequelize/migrations/20200911091342-initial.js
- src/infra/sequelize/migrations/20200911100703-add-gf-fileId.js
- src/infra/sequelize/migrations/20200911154832-add-dcr-fileId.js
- src/infra/sequelize/migrations/20200914124850-add-modificationRequest-fileId.js
- src/infra/sequelize/migrations/20200917130249-add-project-certificateFileId.js
- src/infra/sequelize/migrations/20201007095348-create-eventStore.js
- src/infra/sequelize/models/eventStore.ts
- src/infra/sequelize/models/project.ts
BREAKING CHANGE: Changed DataTypes
> fix: fix models DataTypes

- src/entities/modificationRequest.ts
fixes [#327](https://trello.com/c/oHFeRvtA/327-le-modèle-de-courrier-de-réponse-à-recours-indique-une-date-de-demande-à-la-date-du-jour-reprendre-la-date-de-la-demande)
> fix: date on modèle réponse recours should be request date

- src/views/pages/projectDetails/index.tsx
- src/views/pages/projectDetails/sections/EditProjectData.tsx
> "Corriger les données du projet" => "Remplacer l'attestation"

- src/controllers/postCorrectProjectData.ts
- src/modules/project/Project.shouldCertificateBeGenerated.spec.ts
- src/modules/project/Project.ts
Fixes [#359 ](https://trello.com/c/d1dgRxuv/359-remplacer-attestation)
> correctProjectData shouldn't regenerate certificate if one is given

- .github/workflows/ci.pullrequest.yml
- package-lock.json
- package.json
- src/helpers/logger.ts
- src/views/pages/invitationList.tsx
- tsconfig.json
- Avoid running build during ci
- Remove unused libs from package.json dependencies
- Move build-time dependencies from `devDependencies` to `dependencies` to enable building in a production environment
> Cleanup build process

- src/modules/project/eventHandlers/handlePeriodeNotified.ts
When many projects are notified (and has their certificate generated) simultaneously, it can provoke an
out-of-memory situation and crash the server.
> Projects should be notified sequentially

- src/config/useCases.config.ts
Fixes sentry bug #POTENTIEL-PROD-N and #POTENTIEL-PROD-P
> :bug:  add a binding on shouldUserAccessProject

- src/controllers/upload.ts
Fixes sentry bug #POTENTIEL-PROD-M
> :bug:  Do not delete file from request if there is none

- src/dataAccess/inMemory/appelsOffres/batiment.ts
> :bug:  Set renvoiSoumisAuxGarantiesFinancieres to 36 months for Batiments

- src/useCases/signup.ts
> :bug:  Use lower cased email when adding projects to user on signup

- src/dataAccess/inMemory/appelsOffres/sol.ts
> :star2:  Create 9th period on Appel Offre Sols

- src/views/pages/newModificationRequest.tsx
> :star2:  Improve demande de recours justification label

- src/controllers/auth/authentication.ts
In local dev, we needed to enter the login twice or three times. This fixes the behaviour: if the user session is not available right away, wait a bit and retry.
> Fix login loop in local dev

- src/public/index.html
> :bug:  Add cookies policy link on home page

- src/dataAccess/inMemory/appelsOffres/zni.ts
> 485 Update marks for AO ZNI 5th periode

- src/controllers/admin/postAppelsOffres.ts
- src/controllers/admin/postPeriodes.ts
- src/controllers/candidateNotification/postImportProjects.ts
- src/helpers/parseCsv.ts
wrap parseCsv in ResultAsync and handle the error case properly
> 472  parseCsv should not crash the import request on fail

- src/controllers/admin/postAppelsOffres.ts
- src/controllers/admin/postPeriodes.ts
- src/controllers/candidateNotification/postImportProjects.ts
- src/helpers/parseCsv.ts
- src/modules/appelOffre/useCases/importAppelOffreData.ts
Accept `utf-8` as encoding (files are coming from google drive) and also fix the column for `appelOffreId` in the `remove` case.
> Fix appel offre import

- src/controllers/modificationRequest/postRequestModification.ts
> 507 Add file and justification to demande changement actionnaire

- src/__tests__/fixtures/project.ts
- src/entities/project.ts
- src/views/components/actions/porteurProjet.ts
Fixes the compilation error introduced by PR #177
> Fix compilation by adding missing potentielIdentifier

- src/dataAccess/inMemory/appelsOffres/sol.ts
Note threshold added for the 13th periode of batiments and the 10th periode for sol
> :star2:  627 - Ajout des notes du dernier retenu pour la 10e période sol

- src/controllers/project/index.ts
- src/controllers/project/postUpdateNewRulesOptIn.ts
- src/public/scripts.js
- src/routes.ts
- src/views/components/CDCChoiceForm.tsx
- src/views/components/index.ts
- src/views/pages/newModificationRequestPage/index.tsx
- src/views/pages/projectDetailsPage/index.tsx
to be confirmed: under which conditions must the form be displayed
> 630 as pp i can opt in new cdc rules from project page

- src/infra/sequelize/queries/modificationRequest/getModificationRequestDataForResponseTemplate.integration.ts
- src/infra/sequelize/queries/modificationRequest/getModificationRequestDataForResponseTemplate.ts
`getModificationRequestDataForResponseTemplate` faisait un appel à `details['Adresse postale du contact']` or `details` peut être indéfini pour certains projets. Cela faisait planter la récupération du modèle de réponse.
> :bug: 651 Fix Erreur lors de la génération du modèle de réponse

- src/views/legacy-pages/candidateCertificate.stories.tsx
- src/views/legacy-pages/drealList.stories.tsx
- src/views/legacy-pages/modificationRequestDetails/modificationRequestDetails.stories.tsx
- src/views/pages/projectDetailsPage/projectDetails.stories.tsx
Ajout d'une étape dans le workflow github afin de vérifier tous les types TS du code source (domain, storybooks, tests...)
> :goal_net: Fix some Typescript type errors in storybooks

- src/controllers/admin/postInviteUser.ts
- src/controllers/admin/postRelanceInvitations.ts
- src/controllers/project/postInviteUserToProject.ts
- src/controllers/steps/getUpdateStatusStep.ts
Remove usage of request.get('Referrer') for redirections
> :bug:  718 Fix redirections after success

- src/views/pages/projectDetailsPage/sections/ProjectFrise.tsx
concerne la frise actuelle seulement
> :star2:  As PP I cannot remove GF if is has been validated

- src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRSubmitted.integration.ts
- src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRSubmitted.ts
- src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.integration.ts
- src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
- src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectPTFSubmitted.integration.ts
- src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectPTFSubmitted.ts
- src/infra/sequelize/queries/frise/getProjectEvents.ts
- src/infra/sequelize/queries/frise/getProjectEventsDCR.integration.ts
- src/infra/sequelize/queries/frise/getProjectEventsGF.integration.ts
- src/infra/sequelize/queries/frise/getProjectEventsPTF.integration.ts
- src/modules/frise/dtos/ProjectEventListDTO.ts
- src/views/components/timeline/Timeline.stories.tsx
- src/views/components/timeline/components/DCRItem.tsx
- src/views/components/timeline/components/PTFItem.tsx
- src/views/components/timeline/helpers/extractDCRItemProps.spec.ts
- src/views/components/timeline/helpers/extractDCRItemProps.ts
- src/views/components/timeline/helpers/extractGFItemProps.spec.ts
- src/views/components/timeline/helpers/extractGFItemProps.ts
- src/views/components/timeline/helpers/extractPTFItemProps.spec.ts
- src/views/components/timeline/helpers/extractPTFItemProps.ts
- Ajout d'un événement à ProjectEvent même si nous n'avons pas de filename
- Dans ce cas, afficher un message 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/312"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 795 handle drc submitted and filename not found for timeline

- src/controllers/modificationRequest/postReplyToModificationRequest.ts
- src/views/pages/modificationRequestPage/components/UploadResponseFile.tsx
Exception : puissance modification that follows a justice decision
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/394"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 959 As admin or dreal I have to attach a file to requests response

- src/controllers/ademe/getAdemeStatistiquesPage.ts
- src/controllers/ademe/index.ts
- src/controllers/index.ts
- src/infra/sequelize/seeds/20220322101200-users.js
- src/routes.ts
- src/views/components/PartnerDashboard.tsx
- src/views/index.ts
- src/views/pages/statistiques/AdemeStatistiques.tsx
- src/views/pages/statistiques/index.ts
- ajout d'une page statistiques pour le role ademe
- modification du script de création des seeds (j'ai modifié tous les id car ils étaient identiques et j'avais une erreur en retour)
- to do : publier le dashboard stat ademe depuis metabase (dashboard 5)
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/389"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 966 ademe statistiques page

- src/infra/sequelize/migrations/20220328093025-fix-dreal-users.js
Certains utilisateurs DREAL ont vu leur rôle corrigé dans keycloak cependant ce role n'a pas été corrigé dans la projection users de Potentiel
> :card_file_box: Correction des rôles de certains utilisateurs DREAL

- src/controllers/admin/index.ts
- src/controllers/admin/postCancelGFDueDateForPPE2AOs.ts
- src/modules/project/Project.ts
AO concernés : Eolien, Bâtiment et Autoconso.
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/417"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 930 remove gf due date for PPE2 AOs

- src/views/components/buttons/LinkButton.tsx
- src/views/components/buttons/index.ts
- src/views/legacy-pages/listProjects.tsx
- src/views/pages/homePage/Home.tsx
Ici j'en ai profité pour utiliser un composant `LinkButton` qui était présent dans le composant `Home`
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/429"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> :bug: Correction de l'export de la liste des projets filtrées

- src/controllers/garantiesFinancieres/postSubmitGF.ts
- src/controllers/garantiesFinancieres/postUploadGF.ts
- src/infra/sequelize/migrations/20220407140613-set-ProjectGFInvalidated-aggregateId-to-projectId.js
- src/modules/project/events/ProjectGFInvalidated.ts
- src/modules/project/useCases/submitGF.ts
`ProjectGFInvalidated` manquait un `aggregateId` et l'agrégat ne le chargeait donc pas.
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/431"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 🐛1052 : user could not submit new GF

- src/controllers/modificationRequest/postRequestModification.ts
- src/useCases/index.ts
- src/useCases/requestModification.spec.ts
- src/useCases/requestModification.ts
- src/views/components/ModificationRequestActionTitles.tsx
- src/views/components/RequestList.tsx
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/550"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ⚰️ 967 ne plus mentionner des demandes de type délai dans l'ancien postModificationRequest

- src/infra/sequelize/queries/frise/getProjectEvents.ts
- src/infra/sequelize/queries/frise/getProjectEventsGF.integration.ts
- src/modules/frise/dtos/ProjectEventListDTO.ts
- src/views/components/ProjectList.tsx
- src/views/components/timeline/components/GFItem.tsx
- src/views/components/timeline/helpers/extractGFItemProps.spec.ts
- src/views/components/timeline/helpers/extractGFItemProps.ts
- src/views/pages/garantiesFinancieresPage/GarantiesFinancieres.tsx
- sur la page GF, pour les GF "en retard"
- dans la frise d'un projet 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/562"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 306 Remettre lien modèle de mise en demeure

- src/infra/sequelize/projectionsNext/projectEvents/events/DemandeDélaiEvent.ts
- src/infra/sequelize/queries/frise/getProjectEvents.DemandeDélai.integration.ts
- src/infra/sequelize/queries/frise/getProjectEvents.ts
- src/modules/frise/dtos/ProjectEventListDTO.ts
- src/views/components/timeline/components/DemandeDélaiItem.tsx
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/598"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 💄 (1080): Erreur d'affichage d'une demande de délai accordé dans la frise

- src/controllers/modificationRequest/fournisseur/postChangerFournisseur.ts
cet import a fait échouer le dernier déploiement en prod...
> 🐛 (Contrôleur postChangerFournisseur): Correction import /src

- src/modules/notification/Notification.ts
- src/modules/notification/eventHandlers/handleProjectCertificateUpdatedOrRegenerated.ts
⚠️ Penser à mettre à jour le [template mailjet](https://app.mailjet.com/template/8046079/build) en ajoutant la variable `urlRedirection` ⚠️ 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/657"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 🎨 (1064): ajout d'une variable urlRedirection dans le template maijet de nouvelle attestation PP

- package-lock.json
- package.json
- src/core/utils/Result.ts
- src/core/utils/makeEventStore.ts
- src/modules/appelOffre/useCases/importAppelOffreData.ts
- src/modules/appelOffre/useCases/importPeriodeData.ts
- src/modules/modificationRequest/useCases/requestActionnaireModification.ts
changelog : https://github.com/supermacro/neverthrow/releases
> ⬆️ (1209): upgrade neverthrow

- package-lock.json
- package.json
- src/controllers/lettreInformation/postSinscrireLettreInformation.ts
- src/infra/mail/mailjet.ts
changelog : https://github.com/mailjet/mailjet-apiv3-nodejs/blob/master/CHANGELOG.md
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/701"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ⬆️ (1209): upgrade node mailjet

- package-lock.json
- package.json
À merger après https://github.com/MTES-MCT/potentiel/pull/698
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/700"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 1209 maj majeur packages 4

- docs/KEYCLOAK.md
- keycloak-legacy/realm-export.json
- keycloak-legacy/themes/potentiel/welcome/index.ftl
- update doc
- redirection vers url local
- fix bug redirectURIs
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/731"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 🎨 (1283): Fixer les problèmes de keycloak local

- src/controllers/modificationRequest/délai/postAccorderOuRejeterDemandeDelai.ts
- src/controllers/modificationRequest/délai/postDemanderDélai.ts
- src/views/pages/demanderDelaiPage/DemanderDelai.tsx
- src/views/pages/modificationRequestPage/components/AdminRéponseDélaiForm.tsx
Le problème vient de la dernière version de multer qui pose des problème d'encoding des propriété du body de la request.
Pour l'instant j'ai enlvé les accents mais il va falloir regarder ce qui cloche avec multer
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/763"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 🐛 (1315): Correction du bug pour soumettre une demande de delai

- src/infra/sequelize/projectionsNext/projectEvents/updates/délai/onDélaiAccordé.integration.ts
- src/infra/sequelize/projectionsNext/projectEvents/updates/délai/onDélaiAccordé.ts
- src/modules/demandeModification/demandeDélai/accorder/accorderDemandeDélai.spec.ts
- src/modules/demandeModification/demandeDélai/accorder/accorderDemandeDélai.ts
- src/modules/demandeModification/demandeDélai/events/DélaiAccordé.ts
- src/modules/notification/eventHandlers/demandeDélai/onDélaiAccordé.spec.ts
- src/modules/project/eventHandlers/onDélaiAccordé.spec.ts
- src/modules/project/eventHandlers/onDélaiAccordé.ts
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/807"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ♻️ (1347): dateAchèvementAccordée > adapter le code pour le passage du payload en Date

- src/controllers/modificationRequest/postRequestModification.ts
- src/controllers/modificationRequest/puissance/index.ts
- src/controllers/modificationRequest/puissance/postDemanderChangementPuissance.ts
- src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
- src/modules/modificationRequest/useCases/requestPuissanceModification.ts
- src/routes.ts
- src/views/pages/demanderChangementPuissancePage/DemanderChangementPuissance.tsx
À merger après https://github.com/MTES-MCT/potentiel/pull/848
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/849"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ♻️ (1418): Demander un changement de puissance refacto - Controller post

- src/controllers/candidateNotification/getProjectCertificateFile.ts
- src/controllers/helpers/miseAJourStatistiquesUtilisation.ts
- src/controllers/project/getProjectListCsv.ts
Vu avec Julie, on garde encore quelques mois la mise à jour côté umami. J'ai créer une [carte](https://airtable.com/apphLwfLi4vad9EAq/tbl8Xmi9jiTVtLxVp/viwZ5cGuW9v5FJb7B/recoWEkCK9z2ng3jy?blocks=hide) pour ne pas oublier 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/856"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ✨ (1424): Ajout statistique d'utilisation pour le téléchargement de la liste projets

- src/controllers/project/getProjectListCsv.ts
- src/dataAccess/inMemory/appelsOffres/commonDataFields.ts
…ement participatfi
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/855"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> 🐛 (1423): Correction de l'export des donnees d'investissement/financement participatif

- src/config/eventHandlers/notifications/demandeAnnulationAbandon.notifications.ts
- src/config/eventHandlers/notifications/index.ts
- src/modules/notification/eventHandlers/demandeAnnulationAbandon/index.ts
- src/modules/notification/eventHandlers/demandeAnnulationAbandon/onAnnulationAbandonAccordée.spec.ts
- src/modules/notification/eventHandlers/demandeAnnulationAbandon/onAnnulationAbandonAccordée.ts
- src/modules/notification/eventHandlers/demandeAnnulationAbandon/onAnnulationAbandonRejetée.spec.ts
- src/modules/notification/eventHandlers/demandeAnnulationAbandon/onAnnulationAbandonRejetée.ts
- src/modules/notification/eventHandlers/index.ts
- src/modules/notification/useCases/notifierPorteurChangementStatutDemande.spec.ts
- src/modules/notification/useCases/notifierPorteurChangementStatutDemande.ts
Notification des porteurs en cas de réponse à une demande d'annulation d'abandon (acceptée ou rejetée).
> ✨ (Demande annulation abandon): notification des porteurs

- src/views/pages/AdminNotificationCandidatsPage.tsx
- src/views/pages/demandeAbandonPage/DemandeAbandon.tsx
- src/views/pages/demandeAnnulationAbandonPage/DemandeAnnulationAbandon.tsx
- src/views/pages/demanderAbandonPage/DemanderAbandon.tsx
- src/views/pages/garantiesFinancieresPage/GarantiesFinancieres.tsx
- src/views/pages/modificationRequestPage/components/DemandeDetails.tsx
- src/views/pages/modificationRequestPage/components/DemandeStatus.tsx
- src/views/pages/modificationRequestPage/components/DownloadResponseTemplate.tsx
Utilisation partout où nécessaire des composants DownloadLink, SecondaryLinkButton ...
> :lipstick:  1536 - liens téléchargement explicites

- .github/workflows/codeql-analysis.yml
Cette PR contient:
- Rajout de TypeScript dans la matrice des langages
- Passage des actions en v2
> 👷 Mise à jour de la configuration CodeQL

- src/dataAccess/inMemory/appelsOffres/CRE4/autoconsommationMetropole.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/autoconsommationMetropole2016.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/autoconsommationZNI.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/autoconsommationZNI2017.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/batiment.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/eolien.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/fessenheim.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/innovation.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/pvEolien.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/sol.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/zni.ts
- src/dataAccess/inMemory/appelsOffres/CRE4/zni2017.ts
- src/dataAccess/inMemory/appelsOffres/PPE2/ppe2.autoconsommationMetropole.ts
- src/dataAccess/inMemory/appelsOffres/PPE2/ppe2.batiment.ts
- src/dataAccess/inMemory/appelsOffres/PPE2/ppe2.eolien.ts
- src/dataAccess/inMemory/appelsOffres/PPE2/ppe2.innovation.ts
- src/dataAccess/inMemory/appelsOffres/PPE2/ppe2.neutre.ts
- src/dataAccess/inMemory/appelsOffres/PPE2/ppe2.sol.ts
- src/entities/appelOffre.ts
- src/modules/demandeModification/demandeDélai/demander/demanderDelai.ts
- src/modules/demandeModification/demandeDélai/demander/demanderDélai.spec.ts
Correction de l'autorité compétente pour les demandes de délai. Règles à appliquer : l'autorité est "DGEC" pour l'AO "CRE4 - Eolien", et "DREAL" pour tous les autres AOs.
> :sparkles: (1540): autorité compétente demandes délai

- src/public/scripts.js
Cette fonction fait partie du fichier legacy `public/script.js`, elle se base sur tout les éléments html qui ont un attribut `data-testid=frise-show-timeline`. Aujourd'hui dans le projet, aucun élément HTML n'utilise cet attribut. La fonction est donc obsolète et doit être supprimée
> 🔥 suppression de la fonction legacy addFriseToggleHandler

- src/public/css/potentiel.css
- src/public/scripts.js
- src/views/index.css
- src/views/pages/AdminNotificationCandidatsPage.tsx
- src/views/pages/ListeProjetsPage.tsx
- src/views/pages/ProjetsÀRéclamerPage.tsx
- src/views/pages/garantiesFinancieresPage/GarantiesFinancieres.tsx
- src/views/pages/modificationRequestListPage/ModificationRequestList.tsx
Dans cette PR j'ai viré la méthode `addVisibilityToggleHandler` du fichier `script.js` en utilisant des dropdown pour l'affichage des filtres sur les listes + la fonctionnalité d'ajout d'utilisateur à un projet depuis la liste des projets
> ♻️ utilisation de react pour conditionner l'affichage des dropdowns de filtrage des listes

- packages/domain/src/raccordement/raccordement.aggregate.ts
🐛 (hotfix): Fix aggregat raccordement - modification DCR avec meme ref
> Hotfix modification dcr meme ref dossier (#1101)

- src/controllers/project/getProjectPage.ts
- src/views/pages/projectDetailsPage/ProjectDetails.stories.tsx
- src/views/pages/projectDetailsPage/ProjectDetails.tsx
- src/views/pages/projectDetailsPage/components/ProjectHeader.tsx
Deux alertes : 
- si le projet est concerné par le CDC 2022 et qu'il n'a pas de réference de dossier de raccordement
- si le projet n'a pas d'AR de DCR
> Alertes page projet donnees raccordements manquantes

- src/infra/file/S3FileStorageService.ts
- src/modules/project/utils/parseProjectLine.spec.ts
- src/modules/project/utils/parseProjectLine.ts
- Correction intitulé colonne
- Valeur N/A acceptée dans la colonne type de GF pour les projets éliminés
> :sparkles: Modification règles import GF

- src/controllers/project/getProjectPage.ts
> 🐛 ne pas afficher l'alerte DCR manquante si le projet est éliminé ou abandonné

- src/controllers/notificationCandidats/getProjectCertificateFile.ts
- src/controllers/project/getProjectFile.ts
carte airtable : https://airtable.com/apphLwfLi4vad9EAq/tbl8Xmi9jiTVtLxVp/viwZ5cGuW9v5FJb7B/rec5m3Rsug1OubNZ9?blocks=hide
> 🐛 Accès aux fichiers projet pour AO + Accès à l'attestation de désignation pour CRE

- packages/libraries/pg-event-sourcing/sql/event-store.sql
Cette PR contient la premiére étape pour la refonte du système d'acknowledgement des events
> ♻️ Améliration Event Store + accusé traitement des events

- src/controllers/garantiesFinancieres/postEnregistrerGarantiesFinancières.ts
- src/views/pages/garantiesFinancières/EnregistrerGarantiesFinancièresPage.tsx
- correction d'un import dans le contrôleur pour permettre d'afficher les messages des Domain Errors
- mettre un premier filtre sur la date de constitution côté front avec une date max dans l'input
> Bug affichage erreurs post enregistrer GF

- src/controllers/modificationRequest/getModificationRequestPage.ts
- src/infra/sequelize/queries/frise/getProjectEvents.ts
- src/infra/sequelize/queries/modificationRequest/getModificationRequestListForAdmin.integration.ts
- src/infra/sequelize/queries/modificationRequest/getModificationRequestListForAdmin.ts
- src/modules/modificationRequest/dtos/ModificationRequestListItemDTO.ts
- src/views/components/RequestList.tsx
- src/views/pages/demandeAbandonPage/DemandeAbandon.tsx
Accès à la page d'une demande, mais limité aux info suivantes : 
- statut demande
- détail du projet
- courrier de réponse
Détail demande accessible depuis la frise et depuis la liste des demandes.
> :sparkles: Accès DREAL aux réponse aux demandes d'abandon

- packages/domain/src/permissions/garantiesFinancières.permissions.ts
- src/controllers/garantiesFinancieres/getDéposerGarantiesFinancièresPage.ts
- src/controllers/garantiesFinancieres/getEnregistrerGarantiesFinancièresPage.ts
- src/controllers/garantiesFinancieres/getFichierDépôtAttestationGarantiesFinancières.ts
- src/controllers/garantiesFinancieres/getModifierDépôtGarantiesFinancièresPage.ts
- src/controllers/garantiesFinancieres/index.ts
- src/controllers/garantiesFinancieres/postDéposerGarantiesFinancières.ts
- src/controllers/garantiesFinancieres/postEnregistrerGarantiesFinancières.ts
- src/controllers/garantiesFinancieres/postModifierDépôtGarantiesFinancières.ts
- src/controllers/project/getProjectPage.ts
- src/modules/authN/Permission.ts
- src/routes.ts
- src/views/components/UI/atoms/headings/Heading4.tsx
- src/views/components/UI/molecules/Alertes/AlertMessage.tsx
- src/views/components/UI/molecules/InputFile.tsx
- src/views/helpers/formatDateForInputMaxDate.ts
- src/views/helpers/index.ts
- src/views/index.ts
- src/views/pages/garantiesFinancières/DéposerGarantiesFinancièresPage.tsx
- src/views/pages/garantiesFinancières/EnregistrerGarantiesFinancièresPage.tsx
- src/views/pages/garantiesFinancières/ModifierDépôtGarantiesFinancièresPage.tsx
- src/views/pages/garantiesFinancières/index.ts
- src/views/pages/projectDetailsPage/ProjectDetails.tsx
- src/views/pages/projectDetailsPage/sections/GarantiesFinancières.tsx
- src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx
- src/views/pages/raccordement/demandeComplèteRaccordement/ModifierDemandeComplèteRaccordementPage.tsx
- src/views/pages/raccordement/demandeComplèteRaccordement/TransmettreDemandeComplèteRaccordementPage.tsx
- src/views/pages/raccordement/miseEnService/TransmettreDateMiseEnServicePage.tsx
- src/views/pages/raccordement/propositionTechniqueEtFinancière/ModifierPropositionTechniqueEtFinancièrePage.tsx
- src/views/pages/raccordement/propositionTechniqueEtFinancière/TransmettrePropositionTechniqueEtFinancièrePage.tsx
- affichage sur la page d'un projet
- formulaires de dépôt et modification dépôt
- ajout contrôleurs
> :sparkles: Affichage GF et branchement front dépôt GF

- src/controllers/modificationRequest/getModificationRequestPage.ts
- src/infra/sequelize/queries/frise/getProjectEvents.ts
- src/infra/sequelize/queries/modificationRequest/getModificationRequestListForAdmin.integration.ts
- src/infra/sequelize/queries/modificationRequest/getModificationRequestListForAdmin.ts
- src/views/components/timeline/components/ModificationRequestItem.tsx
- src/views/pages/modificationRequestPage/ModificationRequest.tsx
Pour les dreals, la seule restriction est la région.
Les dreals doivent pouvoir accéder au détail des demandes depuis la liste des demandes et depuis la frise.
> :sparkles: ETQ dreal j'ai accès au détail de tous les types de demandes

- src/infra/sequelize/queries/project/exporter/exporterProjets.ademe.integration.ts
- src/infra/sequelize/queries/project/exporter/requêtes/exporterProjetsPourADEME.ts
On donne les mêmes accès que pour le CRE concernent l'export des projets
> ✨ Mise à jour colonnes export des projets pour l'ADEME

- src/modules/demandeModification/demandeChangementDePuissance/demander/NouvellePuissanceAuDessusPuissanceMaxVolumeReserveError.ts
- src/modules/demandeModification/demandeChangementDePuissance/demander/demanderChangementDePuissance.spec.ts
- src/modules/demandeModification/demandeChangementDePuissance/demander/demanderChangementDePuissance.ts
- src/modules/demandeModification/demandeChangementDePuissance/demander/index.ts
- src/views/pages/demanderChangementPuissancePage/DemanderChangementPuissance.tsx
- src/views/pages/demanderChangementPuissancePage/components/AlertePuissanceMaxDepassee.tsx
- src/views/pages/demanderChangementPuissancePage/components/ChangementPuissance.tsx
- mise à jour wording alerte
- blocage côté front
- erreur retournée par le back
> :sparkles: Plafond puissance bloquant pour les volumes réservés

- packages/applications/ssr/src/app/abandons/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/page.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/DetailAbandonPage.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/EtapesAbandon.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/PreuveRecandidatureStatutBadge.tsx
- packages/applications/ssr/src/components/pages/abandon/lister/AbandonListItem.tsx
- packages/applications/ssr/src/components/pages/abandon/lister/AbandonListPage.tsx
- packages/domain/lauréat/src/abandon/abandon.projection.ts
- packages/domain/lauréat/src/abandon/consulter/consulterAbandon.query.ts
- packages/domain/lauréat/src/abandon/index.ts
- packages/domain/lauréat/src/abandon/lister/listerAbandon.query.ts
- packages/domain/lauréat/src/abandon/statutAbandon.valueType.ts
- packages/domain/lauréat/src/abandon/statutPreuveRecandidature.valueType.ts
- packages/infrastructure/domain-adapters/src/abandon/listerAbandons.adapter.ts
- packages/infrastructure/domain-adapters/src/abandon/listerAbandonsPourPorteur.adapter.ts
- packages/infrastructure/projectors/src/lauréat/abandon.projector.ts
- affichage d'un badge sur la liste des abandons
- ajout d'un filtre pour afficher les preuves transmises ou en attente
> :sparkles: Filtrer abandons par preuve de recandidature

- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
- packages/domain/lauréat/src/abandon/lister/listerAbandon.query.ts
- packages/domain/utilisateur/src/role.valueType.ts
- packages/domain/utilisateur/src/vérifierAccèsProjet/vérifierAccèsProjet.query.ts
- src/views/components/UI/organisms/UserNavigation.tsx
- accès à tous les abandons
- accès aux documents
- pas d'instruction possible
> 🛂 La CRE peut accéder aux abandons

- packages/domain-inmemory-referential/src/appelOffre/CRE4/fessenheim.ts
- packages/domain-inmemory-referential/src/appelOffre/CRE4/sol.ts
- src/views/pages/demanderChangementPuissancePage/components/AlertePuissanceFourchetteRatioInitialEtCDC2022.tsx
Appliquer les retours à la ligne quand il y en a...
> 💄 (Affichage): Alerte puissance CDC 2022

- src/controllers/garantiesFinancieres/getUploadGF.ts
- src/infra/sequelize/queries/frise/getGarantiesFinancièresDTO.integration.ts
- src/infra/sequelize/queries/frise/getGarantiesFinancièresDTO.ts
- src/modules/authN/Permission.ts
- src/modules/project/Project.addGFExpirationDate.spec.ts
- src/modules/project/Project.ts
- src/modules/project/Project.uploadGarantiesFinancieres.spec.ts
- src/modules/project/errors/DateEchéanceIncompatibleAvecLeTypeDeGFError.ts
- src/modules/project/errors/index.ts
- src/modules/project/useCases/addGFExpirationDate.ts
- src/modules/project/useCases/uploadGF.spec.ts
- src/modules/project/useCases/uploadGF.ts
- src/views/components/timeline/components/GFItem.tsx
- les porteurs peuvent enregistrer le fichier + date de constitution, il n'y a pas de date d'échéance à renseigner dans le formulaire
- l'ajout / modification d'une date d'échéance n'est possible que si le rôle le permet et si le type de GF le permet
- les porteurs ne peuvent pas modifier une date d'échéance
> ✨ (LEGACY GF): Upload fichier GF

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/infrastructure/domain-adapters/src/utilisateur/index.ts
- packages/infrastructure/domain-adapters/src/utilisateur/récupérerDrealsParIdentifiantProjet.adapter.ts
- packages/infrastructure/notifications/src/index.ts
- packages/infrastructure/notifications/src/lauréat/garantiesFinancières.notification.ts
- packages/infrastructure/notifications/src/templateId.ts
- Notification porteurs et Dreals en cas de GF soumises
- à voir sur mailjet : nouveaux templates préfixés avec [NEW]
> ♻️ (Migration domaine GF): notification GF soumises

- docs/contributing/GETTING_STARTED.md
Bonjour :)
En lançant le projet j'ai remarqué quelques typos dans le getting started (principalement un `` ``` `` en trop qui détruisait la mise en forme). Voici une proposition de correction. Qu'en pensez-vous ?
Bonne journée !
> ✏️ Fix some typos in GETTING_STARTED.md

- packages/applications/legacy/src/views/pages/newModificationRequestPage/components/actionnaire/ChangementActionnaire.tsx
[POT-83](https://linear.app/startup-potentiel/issue/POT-83/2404-la-demande-de-changement-dactionnaire)
> 💬 Made label for demande actionnaire optional

- packages/applications/legacy/src/views/pages/changerProducteurPage/ChangerProducteur.tsx
[POT-93](https://linear.app/startup-potentiel/issue/POT-93/2403-la-demande-de-changement-de-producteur)
> 💬 Fix demande prod

- packages/applications/legacy/src/views/pages/Signup.tsx
- packages/applications/legacy/src/views/pages/homePage/components/InscriptionConnexion.tsx
[POT-64](https://linear.app/startup-potentiel/issue/POT-64/2388-potentiel-doit-etre-plus-clair-sur-le-processus-dinscription)
> 🚸 Feat v1 signup impr

- packages/applications/legacy/src/views/components/UI/organisms/Footer.tsx
- packages/applications/legacy/src/views/components/UI/organisms/Header.tsx
- packages/applications/legacy/tailwind.config.js
Could probably have done something smarter BUT that's legacy
> 🎨 Fix font for header and footer

- packages/infrastructure/pg-projections/src/listProjectionV2.test.ts
Problem : order is not guaranteed when querying without orderBy in SQL
Solved by find right chaï commands
> ✅ Fix flaky test

- packages/applications/legacy/src/controllers/modificationRequest/postReplyToModificationRequest.ts
- packages/applications/legacy/src/modules/demandeModification/demandeChangementDePuissance/demander/demanderChangementDePuissance.spec.ts
- packages/applications/legacy/src/modules/demandeModification/demandeChangementDePuissance/demander/demanderChangementDePuissance.ts
- packages/applications/legacy/src/modules/demandeModification/demandeChangementDePuissance/demander/helpers/getAutoritéCompétenteInstructionPuissance.ts
Règle métier : pour une demande de changement de puissance hors ratio du CDC applicable
- si le ratio est supérieur au ratio max : la demande est adressée à la DGEC
- si le ratio est inférieur au ratio min : la demande est adressée à la DREAL
> ✨ Autorité instructrice changement puissance hors ratio CDC

- cron.json
Suppression de la tâche automatisée, à réactiver une fois l'env monté et prêt. Cette PR pourra être revert et passer en patch dans une MEP future
> 🔥 Remove scheduled tasks for backup OSS

- scripts/migration-streams-garanties-financieres.sql
détails issue : https://linear.app/startup-potentiel/issue/POT-234/gerer-les-cas-de-projets-ppe2-dont-le-type-de-gf-na-pas-ete-importe
Pour rappel, voilà ce que peuvent faire les porteurs avec la V1 de la migration des GF : 
- Soumettre  un dépôt de GF, modifier un dépôt de GF, supprimer un dépôt de GF
- Pour les GF actuelles, le porteur ne peut qu'enregistrer l'attestation (après import du type)
Donc actuellement pour les projets PPE2 pour lesquels nous n'avons pas importé le type de GF (300 projets), les porteurs ne peuvent que "soumettre" un dépôt de GF, alors que leurs GF ont été validée à la candidature. 
**=> Solution proposée :** Mettre par défaut type "type-inconnu" pour ces GF. Comme cela les porteurs peuvent enregistrer l'attestation de GF actuelles validées à la candidature …
> 🗃️ (GF streams migration): projets PPE2 sans type importé

- packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
- packages/domain/réseau/src/raccordement/consulter/consulterDossierRaccordement.query.ts
- packages/domain/réseau/src/raccordement/raccordement.entity.ts
Réintégration du Hotfix de raccordement dans master
> 🐛 Hotfix raccordement (#1754)

- packages/applications/scheduled-tasks/src/créer-backup-oos.ts
Fix du probĺeme lorsqu'un next marker est retourné aprés l'appel d'un list objects
Il faut déclencher la Schedule Tasks créer-backup-oos
- [ ] Avoir + de 1000 fichiers dans le bucket de tests
> 🐛 Fix list objects with next marker

- packages/applications/legacy/src/server.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/demande-complete-raccordement:modifier/page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/GestionnaireRéseauSelect.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.page.tsx
- better handling of gestionnaireReseauSelect and of default value
- Fixing a weird display bug
Issue : https://linear.app/startup-potentiel/issue/POT-264/raccordement-mauvaise-gestion-du-default-au-select
Visual testing
> 🐛 Fix display bug

- packages/applications/legacy/src/controllers/modificationRequest/postReplyToModificationRequest.ts
- packages/applications/legacy/src/infra/sequelize/projectionsNext/modificationRequest/updates/onModificationRequestRejected.ts
- packages/applications/legacy/src/infra/sequelize/projectionsNext/projectEvents/updates/onModificationRequestAccepted.ts
- packages/applications/legacy/src/infra/sequelize/projectionsNext/projectEvents/updates/onModificationRequestRejected.integration.ts
- packages/applications/legacy/src/infra/sequelize/projectionsNext/projectEvents/updates/onModificationRequestRejected.ts
- packages/applications/legacy/src/modules/modificationRequest/ModificationRequest.ts
- packages/applications/legacy/src/modules/modificationRequest/events/ConfirmationRequested.ts
- packages/applications/legacy/src/modules/modificationRequest/events/ModificationRequestAccepted.ts
- packages/applications/legacy/src/modules/modificationRequest/events/ModificationRequestRejected.ts
- packages/applications/legacy/src/modules/modificationRequest/useCases/acceptModificationRequest.ts
- packages/applications/legacy/src/modules/modificationRequest/useCases/rejectModificationRequest.ts
- packages/applications/legacy/src/views/components/UI/atoms/Label.tsx
- packages/applications/legacy/src/views/pages/modificationRequestPage/components/PuissanceForm.tsx
- packages/applications/legacy/src/views/pages/modificationRequestPage/components/UploadResponseFile.tsx
Linked to : https://linear.app/startup-potentiel/issue/POT-229/le-courrier-dinstruction-doit-etre-obligatoire-quen-cas-dacceptation
> 🎨 Fix courrier instruction case

- packages/applications/scheduled-tasks/src/déplacer-fichier-gf.ts
Pendant la MEP on a modifié ce script pour qu'on utilise la date de constitution et le statut pour les path des fichiers.
Pendant la MEP
> 🎨 Mise à jour du script pour déplacer les fichiers gfs suite aux modifs de la MEP

- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/demander/page.tsx
Actuellement il n'y a pas de vérification côté domaine/agrégat pour vérifier le statut d'un projet (lauréat/éliminé/abandonné) lorsqu'un porteur demande un abandon. 
Le filtre est fait côté détail du projet, on n'affiche le lien vers le formulaire d'abandon seulement si le projet est lauréat non abandonné.
Cependant on peut toujours accéder au formulaire en saisissant directement l'url de la page. Et donc il est possible de faire une demande d'abandon sur un projet éliminé. 
Pour éviter que des demandes puissent être faites sur des projets éliminés, dans cette PR on bloque l'accès au formulaire pour les projets non "classés".
A noter que cette vérification devra être faite plus tard côté agrégat, lorsque nous aurons un agrégat avec le statut du projet.  
Veuillez supprimer les options qui …
> ✨ bloquer l'accès au formulaire d'abandon si projet non classé

- packages/libraries/monitoring/src/capture.ts
- packages/libraries/monitoring/src/logger.ts
Sentry
=> un projet unique
=> plusieurs environnements
TODO
Mettre à jour les variables d'env SENTRY_DNS sur scalingo une fois la PR merged
définir des niveaux d'alerte pour recevoir des mails si y'a des soucis graves : 
https://sentry.incubateur.net/organizations/betagouv/alerts/wizard/?referrer=project_detail&project=potentiel
Test concluant sur Sentry
> 🔊 New sentry set up

- packages/applications/ssr/src/components/atoms/CallOut.stories.tsx
- packages/applications/ssr/src/components/atoms/CallOut.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/GarantiesFinancièresActuelles.tsx
[Linear](https://linear.app/startup-potentiel/issue/POT-245/harmoniser-laffichage-des-informations-entre-les-gf-actuelles-et-le)
Quelques changements d'harmonisation non majeurs
Un petit fix sur le ternaire pour plus de lisibilité du code
> 🎨 Harmonize front for GF actuelles

- packages/applications/legacy/src/controllers/modificationRequest/postReplyToModificationRequest.ts
- packages/applications/legacy/src/controllers/notificationCandidats/getProjectCertificateFile.ts
- packages/applications/legacy/src/controllers/notificationCandidats/postSendCandidateNotifications.ts
- packages/applications/legacy/src/modules/project/utils/parseProjectLine.spec.ts
- packages/applications/legacy/src/modules/project/utils/parseProjectLine.ts
- designation => redirection plus claire
- fix a typo
- delete an olllldddd comment when passing by
- gave up : add another redirection after designation success
> 💄 little wording fix

- packages/applications/legacy/src/controllers/project/getProjectPage.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
https://linear.app/startup-potentiel/issue/POT-282/[cleancode]-achevement-petites-ameliorations
> ♻️ Little refacto

- cron.json
> 🐛 Fix cron setup

- cron.json
> 🐛 Fix cron setup (#1811)

- packages/applications/bootstrap/src/setupRéseau.ts
- packages/applications/projectors/src/subscribers/réseau/gestionnaireRéseau.projector.ts
- packages/domain/réseau/src/gestionnaire/ajouter/ajouterGestionnaireRéseau.behavior.ts
- packages/domain/réseau/src/gestionnaire/gestionnaireRéseau.aggregate.ts
- packages/domain/réseau/src/gestionnaire/modifier/modifierGestionnaireRéseau.behavior.ts
🐛 Fix GRD events and projector
> 🐛 Fix GRD events and projector

- packages/applications/projectors/src/subscribers/réseau/gestionnaireRéseau.projector.ts
- packages/applications/projectors/src/subscribers/tâche/tâche.projector.ts
- packages/applications/ssr/src/app/taches/page.tsx
- packages/applications/ssr/src/components/pages/tâche/TâcheList.page.tsx
- packages/applications/ssr/src/components/pages/tâche/TâcheList.stories.tsx
- packages/applications/ssr/src/components/pages/tâche/TâcheListItem.tsx
- packages/domain/common/src/valueTypes/dateTime.valueType.ts
- packages/domain/common/src/valueTypes/identifiantProjet.valueType.ts
- packages/domain/core/src/entity.ts
- packages/domain/core/src/plainType.ts
- packages/domain/réseau/src/gestionnaire/ajouter/ajouterGestionnaireRéseau.behavior.ts
- packages/domain/réseau/src/gestionnaire/modifier/modifierGestionnaireRéseau.behavior.ts
- packages/domain/tâche/src/lister/listerTâches.query.ts
- packages/domain/tâche/src/typeTâche.valueType.ts
- packages/domain/tâche/src/tâche.entity.ts
Cette PR finalise la partie Option, ListV2, Flat et Isomorphique sur le domain tâche.
Il y a aussi un ajustement sur l'utilisation de ts-pattern dans les cas ou la valeur est undefined.
> ♻️ Switch Tâche en isomorphique + Finalisation support complet list V2

- packages/specifications/src/tâche/acheverTâche.feature
- packages/specifications/src/tâche/ajouterTâche.feature
- packages/specifications/src/tâche/stepDefinitions/tâche.then.ts
- packages/specifications/src/tâche/tâche.world.ts
Il manquait les tests pour ce type de tâche
> ✅ Ajout des tests nécessaire pour la tâche "Demander des garanties financières"

- packages/applications/legacy/.env.template
- packages/applications/scheduled-tasks/src/gestionnaireRéseau/addGRDs.ts
- packages/applications/scheduled-tasks/src/gestionnaireRéseau/index.ts
- packages/applications/scheduled-tasks/src/gestionnaireRéseau/référencielGRD.ts
- packages/applications/scheduled-tasks/src/gestionnaireRéseau/updateGRDs.ts
- packages/infrastructure/ore-client/src/constant.ts
- packages/infrastructure/ore-client/src/index.ts
- packages/infrastructure/ore-client/src/récupérerGRDParVille.ts
- packages/infrastructure/ore-client/src/récupérerTousLesGRD.ts
- packages/libraries/http-client/src/index.ts
- Better logs when error after calling an external service
- Same logic to match gestionnaire
- Change env variable to first version
[Ticket](https://linear.app/startup-potentiel/issue/POT-317/ore-improvements-before-mep)
> 🎨 Amélioration de ORE

- packages/applications/legacy/src/views/pages/ListeProjetsPage.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact.tsx
- autorisation (front + back) pour les dreal
- Toute petite reprise de front en bonus
Petit ticket 👍 https://linear.app/startup-potentiel/issue/POT-287/%5Bdreal%5D-en-tant-que-dreal-je-dois-pouvoir-donner-acces-a-potentiel-aux
Test dans l'app (connexion côté dreal + submission form)
Petite amélioration visuelle en bonus 👍
> ✨ Dreal peuvent donner accès à potentiel au PP des projets de leur région

- packages/infrastructure/ore-client/src/récupérerGRDParVille.ts
- packages/infrastructure/ore-client/src/récupérerTousLesGRD.ts
Tout est dans le titre de la PR
> ♻️  Ajout des search params en passant directement par l'objet URL

- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
- packages/domain/lauréat/src/garantiesFinancières/dépôtEnCours/soumettreDépôt/soumettreDépôtGarantiesFinancières.behavior.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/soumettreGarantiesFinancières.feature
ETQ porteur, je ne peux pas déposer de nouvelles GF si j'ai une demande de main-levée "demandée"
https://linear.app/startup-potentiel/issue/POT-332/etq-pp-je-ne-peux-plus-ajouter-ou-modifier-mes-gf-si-jai-une-demande
> 🛂 [garanties financières] Impossible de soumettre un dépôt s'il y a une demande de main-levée "demandée"

- packages/specifications/src/projet/lauréat/garantiesFinancières/effacerHistoriqueGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/enregistrerAttestationGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/enregistrerGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/importerTypeGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/modifierGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/modifierGarantiesFinancièresÀTraiter.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/soumettreGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/supprimerGarantiesFinancièresÀTraiter.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/validerGarantiesFinancièresÀTraiter.feature
Jusqu'à présent nos scénarios d'erreur suivent ce wording :  _Impossible de **faire action** si_. 
Pour les Gfs le wording était différent. Cette PR fait juste l'harmonisation
> ✅ Harmonisation du wording des scénarios d'erreur pour les specifications GFs

- docs/contributing/diagrams/public-api.drawio.svg
Ajout du diagram pour la partie API Public
> 📝 Ajout Public API diagram

- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/annulerMainLevéeGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/demanderMainLevéeGarantiesFinancières.feature
PR pour harmoniser les scénarios d'erreurs du domain mainLevée des GF
> ✅ Wording scénario d'erreurs du domain main levée des gfs

- packages/applications/feature-flags/src/index.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/achevement/attestation-conformite:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
- packages/domain/lauréat/src/garantiesFinancières/mainLevée/demander/demanderMainLevéeGarantiesFinancières.usecase.ts
Feature flag ajouté sur : 
- les actions "demande main-levée" et conditionnement affichage info main-levée côté contrôleur (page.tsx)
- useCase demander main levée
> 🔧 Ajout feature flag main-levée

- packages/applications/scheduled-tasks/src/raccordement/attribuer-gestionnaire-réseau.ts
- packages/applications/scheduled-tasks/src/raccordement/maj-gestionnaire-réseau-des-projets-avec-raccordement.ts
- packages/infrastructure/domain-adapters/src/projet/listerProjetForOre.adapter.ts
Contourner la limit de call API de ORE (sans réponse de leur part)
Lancement de script => avec et sans limit / offset
> 🐛 Feat: added offset and limit

- packages/applications/ssr/src/components/pages/attestation-conformité/FormulaireAttestationConformité.tsx
- ajout d'une info box simple dans le formulaire attestation de conformité
[SPECS](https://linear.app/startup-potentiel/issue/POT-308/[pp]-en-tant-que-pp-et-dreal-jai-acces-a-une-info-box-sur-le)
> 🎨 InfoBox pour transmettre ou modifier une attestation de conformité

- packages/applications/ssr/src/components/atoms/form/InputDownload.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/EtapesAbandon.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/accorder/AccorderAbandonSansRecandidature.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/demanderConfirmation/DemanderConfirmationAbandon.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/rejeter/RejeterAbandon.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/GarantiesFinancièresActuelles.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/GarantiesFinancièresDépôtEnCours.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/en-attente/lister/ListItemProjetAvecGarantiesFinancièresEnAttente.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapeDemandeComplèteRaccordement.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapePropositionTechniqueEtFinancière.tsx
> 🔀 Intégration des modifications de la release 3.24

- packages/infrastructure/pg-event-sourcing/src/subscribe/subscribe.ts
Cette PR met à jour dynamiquement le nombre max de listeners du Client utilisé par les subscribers.
> 🐛 Mise à jour des listeners max du Client dynamiquement

- packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.page.tsx
- packages/domain/lauréat/src/abandon/demander/demanderAbandon.behavior.ts
- packages/specifications/src/projet/lauréat/abandon/demanderAbandon.feature
[POT-303](https://linear.app/startup-potentiel/issue/POT-303/[pp]-en-tant-que-pp-la-piece-jointe-du-formulaire-de-demande-dabandon)
> ✨ Document obligatoire lors d'une demande d'abandon sans recandidature

- docs/contributing/ARCHITECTURE.md
- docs/contributing/CODING_CONVENTION.md
- package-lock.json
- packages/applications/bootstrap/src/middlewares/delay.middleware.ts
- packages/applications/legacy/src/views/components/LegacyPageTemplate.tsx
- packages/applications/legacy/src/views/components/UI/organisms/ProjectList.tsx
- packages/domain/common/src/valueTypes/dateTime.valueType.ts
- packages/infrastructure/pg-projections/src/findProjection.ts
Une PR avec des changements variés suite à mes premiers pas sur le projet et la découverte de problèmes mineurs
- correction de typos (doc et erreur)
- fix d'une checkbox avec label non clickable
- mise à jour de la DB `caniuse` pour retirer un warning
- passage de `user` en optionnel dans `LegacyPageTemplate` pour reféter la réalité et supprimer des erreurs TS
- correction d'un import pour `@potentiel-libraries/flat`
> ✏️ Correction typos et problèmes mineurs

- packages/applications/legacy/src/views/components/UI/organisms/Footer.tsx
- packages/applications/ssr/src/components/organisms/Footer.tsx
[POT-360](https://linear.app/startup-potentiel/issue/POT-360/ajout-des-conditions-generales-dutilisation-et-de-la-politique-de)
équivalent pour keycloak [ici](https://github.com/MTES-MCT/potentiel-keycloak/pull/24)
Legacy:
SSR:
> 💬 Mise à jour des liens du footer

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
Pour utiliser node 20 et corriger les warnings
> 👷 MAJ github actions

- packages/applications/projectors/src/subscribers/lauréat/abandon.projector.ts
- packages/domain/lauréat/src/abandon/abandon.entity.ts
- packages/domain/lauréat/src/abandon/lister/listerAbandonAvecRecandidatureÀRelancer.query.ts
Suppression de la projection AbandonAvecRecandidatureSansPreuveProjection
Lancer les specs
> 🔥 Remove AbandonAvecRecandidatureSansPreuveProjection

- .github/workflows/release.yml
- .github/workflows/shared-workflow.yml
> 👷 Mise à jour github actions

- packages/specifications/src/raccordement/transmettreDemandeComplèteDeRaccordement.feature
Suppression scenario sur les espaces et tabulations
> 🔥 Suppression scenario sur les espaces et tabulations

- packages/domain/inmemory-referential/src/appelOffre/PPE2/ppe2.eolien.ts
> ✨ Ouverture de la période 7 de notification de l'appel d'offres PPE2 Eolien

- packages/applications/bootstrap/src/setupRéseau.ts
- packages/applications/bootstrap/src/setupTâche.ts
- packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
- packages/applications/ssr/src/components/pages/tâche/TâcheListItem.tsx
- packages/domain/réseau/src/raccordement/attribuer/attribuerGestionnaireRéseau.behavior.ts
- packages/domain/réseau/src/raccordement/index.ts
- packages/domain/réseau/src/raccordement/modifier/modifierGestionnaireRéseauRaccordement.behavior.ts
- packages/domain/réseau/src/raccordement/raccordement.aggregate.ts
- packages/domain/tâche/src/typeTâche.valueType.ts
- packages/domain/tâche/src/tâche.saga.ts
- packages/specifications/src/raccordement/stepDefinitions/raccordement.given.ts
- packages/specifications/src/tâche/acheverTâche.feature
- packages/specifications/src/tâche/ajouterTâche.feature
- packages/specifications/src/tâche/tâche.world.ts
> ✨ Composant pour afficher la tâche GRD Inconnu

- docs/contributing/GETTING_STARTED.md
J'ai juste remis la bonne commande dans la documentation
> 📝 Documentation autour de la commande pour générer le fichier dump

- packages/applications/ssr/src/components/molecules/Search.tsx
- packages/applications/ssr/src/components/organisms/ListFilters.tsx
- les filtres s'appliquent directement au choix
- suppression du bouton
> 🎨 amélioration du fonctionnement des filtres

- package-lock.json
- package.json
- packages/applications/cli/bin/dev.js
- packages/applications/cli/bin/run.js
- packages/applications/cli/package.json
- packages/applications/cli/src/commands/files/load-files.ts
- packages/applications/cli/src/commands/files/rename-files.ts
- packages/applications/cli/src/commands/files/rename.command.ts
- packages/applications/cli/src/hooks/init/config.ts
- packages/applications/cli/tsconfig.json
Utilitaire tech pour permettre le renommage de fichiers en masse lors de migration de domaine.
⚠️ testé uniquement en local sur des petits nombres de fichiers
> ✨ Application CLI pour renommer des fichiers S3

- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/GarantiesFinancièresActuelles.tsx
https://linear.app/startup-potentiel/issue/POT-373/alerte-quand-il-manque-lattestation-de-constitution-sur-la-page
> 🎨 Alerte attestation sur la page GF actuelle

- package-lock.json
- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/demander/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/transmettre-preuve-recandidature/page.tsx
- packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.page.tsx
- packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.stories.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.page.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.stories.tsx
- packages/applications/ssr/src/components/pages/abandon/transmettrePreuveRecandidature/TransmettrePreuveRecandidature.page.tsx
- packages/applications/ssr/src/components/pages/abandon/transmettrePreuveRecandidature/TransmettrePreuveRecandidature.stories.tsx
Nettoyage d'abandon suite merge #1930
> ♻️ Suppression récupération des données de candidatures dans les pages Abandon

- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/date-mise-en-service:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/demande-complete-raccordement:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/proposition-technique-et-financiere:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/proposition-technique-et-financiere:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/gestionnaire:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/DétailsRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/DétailsRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierPropositionTechniqueEtFinancière/ModifierPropositionTechniqueEtFinancière.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierPropositionTechniqueEtFinancière/ModifierPropositionTechniqueEtFinancière.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDateMiseEnService/TransmettreDateMiseEnService.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettrePropositionTechniqueEtFinancière/TransmettrePropositionTechniqueEtFinancière.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettrePropositionTechniqueEtFinancière/TransmettrePropositionTechniqueEtFinancière.stories.tsx
PR idem que #1932 mais pour raccordement
> ♻️ Suppression récupération des données de candidatures dans les pages Raccordement

- packages/applications/ssr/src/app/taches/page.tsx
- packages/applications/ssr/src/components/organisms/ListFilters.tsx
- packages/applications/ssr/src/components/pages/tâche/TâcheList.page.tsx
- packages/domain/tâche/src/lister/listerTâches.query.ts
❓  dans TâcheList.page.tsx, j'ai implémenté une solution générique pour `tagFilters` qui pour moi devrait être dans `ListPageTemplate`, qu'en pensez vous ?
> ✨ Filtrer les tâches par catégorie

- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/date-mise-en-service:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/proposition-technique-et-financiere:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/DétailsRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/ImporterDatesMiseEnService.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/importerDatesMiseEnService.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierPropositionTechniqueEtFinancière/ModifierPropositionTechniqueEtFinancière.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierPropositionTechniqueEtFinancière/ModifierPropositionTechniqueEtFinancière.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDateMiseEnService/TransmettreDateMiseEnService.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDateMiseEnService/TransmettreDateMiseEnService.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDateMiseEnService/TransmettreDateMiseEnService.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettrePropositionTechniqueEtFinancière/TransmettrePropositionTechniqueEtFinancière.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettrePropositionTechniqueEtFinancière/TransmettrePropositionTechniqueEtFinancière.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettrePropositionTechniqueEtFinancière/TransmettrePropositionTechniqueEtFinancière.stories.tsx
> 🐛 Corriger les composants RSC Raccordement

- packages/applications/bootstrap/src/bootstrap.ts
En mode dev, si plusieurs pages sont ouvertes, le bootstrap peut avoir lieu plusieurs fois en simultané et on se retrouve avec plusieurs handlers par type de messages. 
Cette PR corrige ce problème en s'assurant qu'un seul bootstrap a lieu en parallèle.
> 🐛 Gérer la concurrence dans bootstrap

- packages/applications/ssr/src/components/organisms/Timeline.tsx
- packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.form.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/HistoriqueMainlevéeRejetée.tsx
- Fix MUI timeline
- Simplification for Abandon (wording)
- Avant
- Après
> 🎨 amélioration composant timeline

- packages/applications/ssr/src/components/atoms/form/Form.tsx
- packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.form.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/accorder/AccorderAbandonAvecRecandidature.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/accorder/AccorderAbandonSansRecandidature.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/annuler/AnnulerAbandon.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/confirmer/ConfirmerAbandon.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/demanderConfirmation/DemanderConfirmationAbandon.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/rejeter/RejeterAbandon.tsx
- packages/applications/ssr/src/components/pages/abandon/transmettrePreuveRecandidature/TransmettrePreuveRecandidature.form.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/dépôt/supprimer/SupprimerDépôtEnCoursGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/dépôt/valider/validerDépôtEnCoursGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/accorder/AccorderDemandeMainlevéeGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/annuler/AnnulerDemandeMainlevéeGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/demander/DemanderMainlevéeGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/instruire/DémarrerInstructionDemandeMainlevéeGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/rejeter/RejeterDemandeMainleveGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/réseau/gestionnaire/ajouter/AjouterGestionnaireRéseau.form.tsx
- packages/applications/ssr/src/components/pages/réseau/gestionnaire/modifier/ModifierGestionnaireRéseau.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/importerDatesMiseEnService.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.form.tsx
Cette PR fix le bug sur les regex dans le formulaire de modif de GRD
npm run dev
> 🐛 Fix regex GRD non modifiable

- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
- packages/applications/ssr/src/components/molecules/ModalWithForm.tsx
Ne pas afficher l'infobox lorsque le porteur peut demander la mainlevée (pas besoin d'information dans ce cas là)
> 🐛 Amélioration condition infobox mainlevée

- packages/applications/ssr/src/app/laureats/[identifiant]/achevement/attestation-conformite:transmettre/page.tsx
- packages/applications/ssr/src/components/pages/attestation-conformité/FormulaireAttestationConformité.tsx
- packages/applications/ssr/src/components/pages/attestation-conformité/modifier/modifierAttestationConformité.page.tsx
- packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.page.tsx
- packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.stories.tsx
"Quand je n'ai pas de garanties financières, je ne devrais pas voir la checkbox "demander une mainlevée", ni l'alerte sur la page Transmettre une attestation de constitution"
> 🐛 Amélioration conditions checkbox mainlevée sur formulaire attestation de constitution

- packages/domain/utilisateur/src/role.valueType.ts
- nouvelle autorisation mise à jour
Carte => https://linear.app/startup-potentiel/issue/POT-400/[dreal]-en-tant-que-dreal-je-dois-avoir-les-meme-droits-sur-la-page
Test en front de tous les usecases
> 🚸 ETQ DREAL j'ai de nouvelles autorisation sur raccordement

- packages/applications/legacy/src/controllers/modificationRequest/postReplyToModificationRequest.ts
La query ConsulterGarantiesFinancièresQuery retourne une Option, il  faut donc utiliser isSome pour vérifier l'existence d'une projection existante
- avoir un projet avec des GFs validées + 1 dépôt en cours
- demander un changement de producteur pour ce projet
- valider la demande etq admin
- etq admin aller voir la partie GF de ce projet
> 🐛 Fix bug legacy effacer historique GFs en cas de changement de produteur

- packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/actuelles:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
- packages/applications/ssr/src/components/molecules/garantiesFinancières/StatutGarantiesFinancièresBadge.tsx
- packages/applications/ssr/src/components/organisms/garantiesFinancières/GarantiesFinancières.tsx
- packages/applications/ssr/src/components/organisms/garantiesFinancières/types.ts
- packages/applications/ssr/src/components/pages/garanties-financières/actuelles/modifier/ModifierGarantiesFinancièresActuelles.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.stories.tsx
- packages/domain/lauréat/src/garantiesFinancières/dépôtEnCours/soumettreDépôt/soumettreDépôtGarantiesFinancières.behavior.ts
- packages/domain/lauréat/src/garantiesFinancières/dépôtEnCours/validerDépôtEnCours/validerDépôtGarantiesFinancièresEnCours.behavior.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.aggregate.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/consulter/consulterGarantiesFinancières.query.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/enregistrer/enregistrerGarantiesFinancières.behavior.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/garantiesFinancièresActuelles.entity.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/importer/importerTypeGarantiesFinancières.behavior.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/modifier/modifierGarantiesFinancières.behavior.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/statutGarantiesFinancières.valueType.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresDéjàLevées.error.ts
- packages/domain/lauréat/src/garantiesFinancières/index.ts
- packages/domain/lauréat/src/garantiesFinancières/mainlevée/accorder/accorderDemandeMainlevéeGarantiesFinancières.behavior.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/modifierGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/soumettreGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/stepDefinitions/garantiesFinancières.then.ts
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/stepDefinitions/mainlevéeGarantiesFinancières.then.ts
- Ajout statut GF => validé, levé, échu
- Ajout de check pour soumettre et modifier GF (interdiction si GF est levée) en back et en front
- Ajout d'en badge de statut pour GF Actuelles
> 🎨  Ajout d'un statut au niveau des garanties financières "actuelles" (validé / levé / échu)

- packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.page.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/InfoBoxMainlevée.tsx
> 🚸 Afficher lien vers formulaire transmission de l'attestation de conformité depuis le détail des GFs

- packages/specifications/src/projet/lauréat/achèvement/attestationConformité/modifierAttestationConformité.feature
- packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.given.ts
- packages/specifications/src/projet/lauréat/achèvement/attestationConformité/transmettreAttestationConformité.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/modifierGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/soumettreGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/accorderDemandeMainlevéeGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/annulerDemandeMainlevéeGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/demanderMainlevéeGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/démarrerInstructionDemandeMainlevéeGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/rejeterDemandeMainlevéeGarantiesFinancières.feature
redéfinir un step pour qu'il soit cohrérent avec la formulation appliquée au reste des specs
> ✅ Update step "une attestation de conformité transmise pour le projet {string}

- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/MainlevéeEnCours.tsx
Affichage `modifié par` pour mainlevée en cours
> 🚸 Fix affichage mainlevée

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
- packages/domain/lauréat/src/garantiesFinancières/dépôtEnCours/validerDépôtEnCours/validerDépôtGarantiesFinancièresEnCours.behavior.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.aggregate.ts
- packages/specifications/src/setup.ts
Ajout DépôtGarantiesFinancièresEnCoursValidé-V2
```
npm run specs
```
> ♻️ Ajout DépôtGarantiesFinancièresEnCoursValidé-V2

- packages/applications/bootstrap/src/setupTâche.ts
- packages/applications/projectors/src/subscribers/tâche/tâche.projector.ts
- packages/domain/common/src/valueTypes/dateTime.valueType.ts
- packages/domain/lauréat/src/garantiesFinancières/dépôtEnCours/validerDépôtEnCours/validerDépôtGarantiesFinancièresEnCours.behavior.ts
- packages/domain/tâche/src/index.ts
- packages/domain/tâche/src/lister/listerTâchesPlanifiées.query.ts
- packages/domain/tâche/src/planifier/planifierTâche.behavior.ts
- packages/domain/tâche/src/planifier/planifierTâche.command.ts
- packages/domain/tâche/src/register.ts
- packages/domain/tâche/src/saga/tâcheGarantiesFinancières.saga.ts
- packages/domain/tâche/src/typeTâche.valueType.ts
- packages/domain/tâche/src/tâche.aggregate.ts
- packages/domain/tâche/src/tâche.entity.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/stepDefinitions/garantiesFinancières.given.ts
- packages/specifications/src/tâche/executerTâche.feature
- packages/specifications/src/tâche/planifierTâche.feature
- packages/specifications/src/tâche/stepDefinitions/tâche.then.ts
- packages/specifications/src/tâche/tâche.world.ts
Ajout de la notion de planification dans les tâches afin de permettre les reminders sur GF
Hors scope de cette PR: execution de la tâche le jour J, a faire dans une prochaine PR
> ✨ Tâches planifiées

- packages/applications/bootstrap/src/setupTâchePlanifiée.ts
- packages/applications/projectors/src/subscribers/tâche/tâchePlanifiée.projector.ts
- packages/domain/tâche-planifiée/src/ajouter/ajouterTâchePlanifiée.behavior.ts
- packages/domain/tâche-planifiée/src/annuler/annulerTâchePlanifiée.behavior.ts
- packages/domain/tâche-planifiée/src/annuler/annulerTâchePlanifiée.command.ts
- packages/domain/tâche-planifiée/src/index.ts
- packages/domain/tâche-planifiée/src/lister/listerTâchesPlanifiées.query.ts
- packages/domain/tâche-planifiée/src/register.ts
- packages/domain/tâche-planifiée/src/saga/tâchePlanifiéeAchévement.saga.ts
- packages/domain/tâche-planifiée/src/statutTâchePlanifiée.valueType.ts
- packages/domain/tâche-planifiée/src/tâchePlanifiée.aggregate.ts
- packages/specifications/src/tâche-planifiée/annulerTâchePlanifiée.feature
- packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.then.ts
> ✨ Annuler une tâche planifiée

- packages/applications/legacy/src/views/components/UI/organisms/Header.tsx
- packages/applications/ssr/src/components/molecules/UserHeaderQuickAccessItem.tsx
Uniformiser le lien vers le compte keycloak
> 🎨 Uniformisation lien vers compte keycloak

- docs/contributing/CODING_CONVENTION.md
- packages/applications/projectors/src/subscribers/lauréat/abandon.projector.ts
- packages/applications/ssr/src/components/pages/abandon/détails/PreuveRecandidatureStatutBadge.tsx
- packages/applications/ssr/src/components/pages/abandon/lister/AbandonList.stories.tsx
- packages/domain/lauréat/src/abandon/statutPreuveRecandidature.valueType.ts
Appliquer convention sur les statuts
> 🎨 Change statut abandon au singulier

- packages/applications/ssr/.storybook/main.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
- packages/applications/ssr/src/components/molecules/CopyAndPaste.tsx
- packages/applications/ssr/src/components/molecules/CopyButton.stories.tsx
- packages/applications/ssr/src/components/molecules/CopyButton.tsx
- packages/applications/ssr/src/components/organisms/garantiesFinancières/GarantiesFinancières.tsx
- packages/applications/ssr/src/components/organisms/garantiesFinancières/GarantiesFinancièresActions.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.page.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/InfoBoxDrealGarantiesFinancièresÉchues.tsx
- molécule CopyAndPaste
- Application pour GarantiesFinancièresEchues
> 🎨 copier coller contacts porteurs quand gfs est échues

- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/stepDefinitions/helper.ts
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/stepDefinitions/mainlevéeGarantiesFinancières.given.ts
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/stepDefinitions/mainlevéeGarantiesFinancières.then.ts
- packages/specifications/src/projet/lauréat/mainLevéeGarantiesFinancières/stepDefinitions/mainlevéeGarantiesFinancières.when.ts
Petit test sur les specs de `mainlevée` pour harmoniser un peu les tests:
- partage des defaults,
- function en helpers pour setup les données sans répéter mes defaults
- virer les optionnel et autre `||` si pas utile
Test
> 🚧 Testing better setup for testing (mainlevée)

- package-lock.json
- packages/applications/legacy/package.json
- packages/applications/legacy/src/infra/file/S3FileStorageService.ts
Afin de réduire la taille de l'image docker à déployer et débloquer les déploiements
En tant que développeur
Je souhaite utiliser la dernière version du sdk aws dans l'application legacy
- Refacto de code
Avec les tests automatiques
- Mon code [suit les directives de style](../docs/contributing//DEVELOPMENT_FLOW.md) de ce projet
- J'ai effectué une auto-revue de mon code
- Mes modifications ne génèrent aucun warning
- Les nouveaux tests unitaires et les tests existants passent en local / dans la CI avec mes modifications
> ⬆️ Mise à jour du package AWS SDK à la version 3 pour l'application legacy

- package-lock.json
- packages/applications/legacy/package.json
- packages/applications/legacy/src/infra/file/S3FileStorageService.ts
This reverts commit b7ce38f5a52fe845cd75f315663a4634c036af63.
> ⏪️ Revert de la mise à jour du package AWS SDK à la version 3 pour l'application legacy

- docs/contributing/GETTING_STARTED.md
- package.json
Script pour mettre à jour le dump dev automatiquement
> 🔧 Ajout script npm pour création du dump

- packages/domain/lauréat/src/garantiesFinancières/mainlevée/demander/demanderMainlevéeGarantiesFinancières.behavior.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/mainlevée/demanderMainlevéeGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/mainlevée/stepDefinitions/mainlevéeGarantiesFinancières.when.ts
> ✅ Impossible de demander la mainlevée des garanties financières si le projet dispose de garanties financières échues

- cron.json
- packages/applications/scheduled-tasks/package.json
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.saga.ts
et ajout d'un `switch` dans la saga
> ✨ Cron pour le scheduler

- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/enregistrerAttestationGarantiesFinancièresActuelles.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/enregistrerGarantiesFinancièresActuelles.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/stepDefinitions/garantiesFinancièresActuelles.given.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/stepDefinitions/garantiesFinancièresActuelles.when.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/stepDefinitions/helper.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/échoirGarantiesFinancièresActuelles.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/dépôt/stepDefinitions/dépôtGarantiesFinancières.given.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/dépôt/stepDefinitions/helper.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/helper.ts
- packages/specifications/src/tâche/acheverTâche.feature
Création de fonctions helpers pour déterminer les variables (exemple vs default) à envoyer aux usecase dans les steps GFs.
> ♻️ refacto des steps de scénario specs gf

- packages/specifications/src/projet/lauréat/achèvement/attestationConformité/transmettreAttestationConformité.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/échoirGarantiesFinancièresActuelles.feature
- packages/specifications/src/raccordement/transmettreDateMiseEnService.feature
- packages/specifications/src/raccordement/transmettreDemandeComplèteDeRaccordement.feature
- packages/specifications/src/raccordement/transmettrePropositionTechniqueEtFinancière.feature
Juste les scénarios ajoutés en NotImplemented
> 🧪 Ajout des scénarios (not implemented pour le moment) dans le cas du raccordement ou achèvement si projet éliminé / abandonné

- packages/domain/lauréat/src/garantiesFinancières/mainlevée/demander/demanderMainlevéeGarantiesFinancières.behavior.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/stepDefinitions/garantiesFinancièresActuelles.given.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/mainlevée/demanderMainlevéeGarantiesFinancières.feature
Modifier du scénario pour que le test puisse passer
> ✅ Pass test Impossible de demander la mainlevée des garanties financières si le projet dispose de garanties financières échues

- package-lock.json
- package.json
- packages/applications/scheduler/package.json
Modification du package.json scheduler
> 📦️ Update scheduler package json

- packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/helpers/getDépôtActions.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/helpers/getGarantiesFinancièresActuellesActions.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/helpers/getHistoriqueMainlevéeRejetéesActions.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/helpers/getMainlevéeActions.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
- packages/applications/ssr/src/components/organisms/Timeline.tsx
- packages/applications/ssr/src/components/organisms/garantiesFinancières/types.ts
- packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.page.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/ArchivesGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/components/InfoBoxMainlevée.tsx
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/archivesGarantiesFinancières.entity.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/consulterArchives/consulterArchivesGarantiesFinancières.query.ts
- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/motifArchivageGarantiesFinancières.valueType.ts
- packages/domain/lauréat/src/garantiesFinancières/index.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/stepDefinitions/garantiesFinancièresActuelles.then.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/stepDefinitions/helper.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/dépôt/validerDépôtGarantiesFinancières.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/effacerHistorique/effacerHistoriqueGarantiesFinancières.feature
Ce fix de release comporte plusieurs élements : 
- Afficher la raison de l'archivage dans l'historique des gfs validées en cas de :
- changement de producteur 
- validation dépot gf suite avec gf échu existante 
- remplacement de gf validé
> 🎨 Retours de tests sur la release 3.28

- packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
> 🐛  Suppression de la projection archives GF au rebuild

- packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/consulterArchives/consulterArchivesGarantiesFinancières.query.ts
> 🎨 Lister les archives GF du plus récent au plus ancien

- packages/domain/lauréat/src/abandon/accorder/accorderAbandon.behavior.ts
- packages/domain/éliminé/src/recours/accorder/accorderRecours.behavior.ts
- packages/specifications/src/gestionnaireRéseau/stepDefinitions/gestionnaireRéseau.given.ts
- packages/specifications/src/gestionnaireRéseau/stepDefinitions/gestionnaireRéseau.when.ts
- packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.given.ts
- packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.when.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/stepDefinitions/garantiesFinancièresActuelles.given.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/stepDefinitions/garantiesFinancièresActuelles.when.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/dépôt/stepDefinitions/dépôtGarantiesFinancières.given.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/dépôt/stepDefinitions/dépôtGarantiesFinancières.when.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/effacerHistorique/stepDefinitions/effacerHistoriqueGarantiesFinancières.when.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/en-attente/stepDefinitions/garantiesFinancièresEnAttente.given.ts
- packages/specifications/src/projet/lauréat/garantiesFinancières/mainlevée/stepDefinitions/mainlevéeGarantiesFinancières.when.ts
- packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.given.ts
- packages/specifications/src/utilisateur/stepDefinitions/utilisateur.given.ts
Suppression des utilisations inutiles de la fonction sleep dans les specs afin de gagner du temps dans les checks de la CI
-  Refacto de code
> 🔥 Suppression des utilisations inutiles de la fonction sleep

- packages/domain/candidature/src/candidature.aggregate.ts
- packages/domain/candidature/src/candidatureDéjàImporter.error.ts
- packages/domain/candidature/src/importer/importerCandidature.behavior.ts
- packages/domain/candidature/src/importer/importerCandidature.command.ts
- packages/domain/candidature/src/statutCandidature.valueType.ts
- packages/specifications/src/candidature/importerCandidature.feature
- packages/specifications/src/candidature/stepDefinitions/candidature.given.ts
- packages/specifications/src/candidature/stepDefinitions/candidature.when.ts
Impossible d'importer 2 fois la même candidature
> ✨ Impossible d'importer 2 fois la même candidature

- packages/domain/candidature/src/importer/importerCandidature.behavior.ts
- packages/domain/candidature/src/importer/importerCandidature.command.ts
- packages/domain/candidature/src/importer/importerCandidature.usecase.ts
> ♻️  La propriété `détails` ne doit pas être optionnelle

- packages/applications/ssr/src/components/atoms/form/Form.tsx
- packages/applications/ssr/src/components/atoms/form/FormFeedback.stories.tsx
- packages/applications/ssr/src/components/atoms/form/FormFeedback.tsx
- packages/applications/ssr/src/components/atoms/form/FormFeedbackCsvErrors.stories.tsx
- packages/applications/ssr/src/components/atoms/form/FormFeedbackCsvErrors.tsx
La position est différente en fonction de :
- si c'est des erreurs liés à un fichier CSV on positionne le composant après le formulaire
- pour les autres cas on le met au dessus du formulaire
> 🚸 Split en deux composants les feedback formulaire de type CSV et les autres

- packages/applications/ssr/src/components/molecules/ListItem.stories.tsx
- packages/applications/ssr/src/components/molecules/ListItem.tsx
- packages/applications/ssr/src/components/molecules/réseau/gestionnaireRéseau/GestionnaireRéseauListItem.tsx
- packages/applications/ssr/src/components/pages/abandon/lister/AbandonListItem.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/dépôt/lister/ListItemDépôtEnCoursGarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/en-attente/lister/ListItemProjetAvecGarantiesFinancièresEnAttente.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/lister/ListItemDemandeMainlevée.tsx
- packages/applications/ssr/src/components/pages/tâche/TâcheListItem.tsx
Afin d'uniformiser les listes, ajout d'un composant pour structurer un List Item
> ♻️ Ajout d'un composant générique ListItem

- packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
> 🚸 Déplacer l'item "régénérer des attestations" dans le menu "candidatures"

- packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
- packages/applications/routes/src/lauréat/raccordement.routes.ts
- packages/applications/ssr/src/app/reseaux/raccordements/references:corriger/page.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/corriger/CorrigerRéférenceDossier.action.ts
- packages/applications/ssr/src/components/pages/réseau/raccordement/corriger/CorrigerRéférenceDossier.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/corriger/CorrigerRéférenceDossier.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/corriger/CorrigerRéférenceDossier.stories.tsx
- packages/domain/document/src/dossierProjet.valueType.ts
- packages/domain/document/src/déplacer/déplacerDocument.command.ts
NB: la story ne fonctionne pas en l'état, il y a le même soucis que sur les autres composants formulaire dont l'action utilise `withUtilisateur`, mais la résolution de ce problème n'a pas sa place dans cette PR
NB2 : le bouton "Corriger" est aligné à gauche. Une bonne partie des formulaires le met au centre, mais il semble que le consensus soit pour l'alignement à gauche
> ✨ Importer un fichier pour corriger les références dossier GRD

- packages/applications/ssr/src/app/candidatures/page.tsx
- packages/applications/ssr/src/components/molecules/ListLegend.stories.tsx
- packages/applications/ssr/src/components/molecules/ListLegend.tsx
- packages/applications/ssr/src/components/molecules/projet/ProjectListItemHeading.tsx
- packages/applications/ssr/src/components/pages/candidature/lister/CandidatureList.page.tsx
- packages/applications/ssr/src/components/pages/candidature/lister/CandidatureList.stories.tsx
- packages/applications/ssr/src/components/pages/candidature/lister/CandidatureListItem.tsx
- packages/applications/ssr/src/components/pages/candidature/lister/candidatureListLegendSymbols.ts
- packages/applications/ssr/src/components/templates/ListPage.template.tsx
- packages/applications/ssr/tailwind.config.ts
Mise à jour du ListItem des candidatures pour ressembler le plus possible à l'actuelle liste des projets.
Voici le résultat :
> 💄 Revue de l'affichage du CandidatureListItem

- packages/applications/cli/src/commands/raccordement/modifier-grd.ts
- packages/domain/réseau/src/gestionnaire/lister/listerGestionnaireRéseau.query.ts
> ♻️ Utilisation de Where entity pour lister gestionnaire query

- package-lock.json
- packages/applications/legacy/src/controllers/project/getProjectPage.ts
- packages/applications/legacy/src/dataAccess/newProjections/récupérerDétailDossiersRaccordements.ts
- packages/applications/scheduled-tasks/package.json
- packages/applications/scheduled-tasks/src/raccordement/supprimer-raccordement.ts
- packages/applications/scheduled-tasks/tsconfig.json
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
- packages/domain/réseau/src/raccordement/consulter/consulterRaccordement.query.ts
- packages/domain/réseau/src/raccordement/index.ts
- packages/specifications/src/raccordement/stepDefinitions/raccordement.then.ts
> ✨ Script de suppression des raccordements des projets déjà abandonnés

- package-lock.json
- packages/applications/legacy/package.json
- packages/infrastructure/email/package.json
Fixed in https://github.com/mailjet/mailjet-apiv3-nodejs/pull/272
> 🔒️ Fix CVE-2024-39338

- packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/importerDatesMiseEnService.form.tsx
Fix typo dans label suite retour démo import date MeS avec numéro CRE.
> ✏️ Fix typos formulaire import date de mise en service

- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeader.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeaderBadge.tsx
- packages/applications/ssr/.env.template
- packages/applications/ssr/src/components/atoms/form/FormFeedback.tsx
- packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.page.tsx
- packages/domain/lauréat/src/abandon/accorder/accorderAbandon.usecase.ts
- packages/domain/lauréat/src/garantiesFinancières/typeTâchePlanifiéeGarantiesFinancières.valueType.ts
- packages/domain/réseau/src/raccordement/supprimer/supprimerRaccordement.command.ts
- packages/domain/tâche/src/saga/tâcheGarantiesFinancières.saga.ts
- packages/domain/tâche/src/typeTâche.valueType.ts
- packages/specifications/src/projet/lauréat/abandon/accorderAbandon.feature
- packages/specifications/src/projet/lauréat/abandon/demanderAbandon.feature
- packages/specifications/src/projet/lauréat/abandon/stepDefinitions/abandon.when.ts
- packages/specifications/src/tâche/tâche.world.ts
Supprimer tâche planifiée liées à GFs quand abandon
> 🐛 Supprimer tâche planifiée échoir si abandon

- packages/applications/ssr/src/app/laureats/[identifiant]/achevement/attestation-conformite:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/achevement/attestation-conformite:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/date-mise-en-service:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/demande-complete-raccordement:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/proposition-technique-et-financiere:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/proposition-technique-et-financiere:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/gestionnaire:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
> ♻️ Utilisation des helpers pour vérifier que le projet est bien classé dans les pages concernées

- packages/applications/legacy/src/server.ts
- packages/applications/legacy/src/views/index.html.tsx
> 🔒️ Fix CSP

- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> 🐛 Fix prévisualiser attestation

- packages/domain/lauréat/src/abandon/abandon.aggregate.ts
- packages/domain/lauréat/src/abandon/index.ts
- packages/domain/lauréat/src/abandon/projetAbandonné.error.ts
- packages/domain/réseau/src/raccordement/formatRéférenceDossierRaccordementInvalide.error.ts
- packages/domain/réseau/src/raccordement/modifier/modifierDemandeComplèteRaccordement.behavior.ts
- packages/domain/réseau/src/raccordement/modifier/modifierRéférenceDossierRaccordement.behavior.ts
- packages/domain/réseau/src/raccordement/transmettre/transmettreDemandeComplèteRaccordement.behavior.ts
- packages/domain/réseau/src/raccordement/transmettre/transmettreDemandeComplèteRaccordement.command.ts
- packages/domain/réseau/src/raccordement/transmettre/transmettreDemandeComplèteRaccordement.usecase.ts
- packages/specifications/src/raccordement/transmettreDemandeComplèteDeRaccordement.feature
> ✅ Impossible de transmettre une demande complète de raccordement si le projet est abandonné

- packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.form.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.page.tsx
- packages/applications/ssr/src/components/pages/recours/demander/DemanderRecours.form.tsx
- packages/applications/ssr/src/components/pages/recours/détails/DétailsRecours.page.tsx
Fix suite retours démo recours
Abandon : 
Recours :
> 🐛 Fix suite retours démo recours

- package-lock.json
- packages/applications/feature-flags/package.json
- packages/applications/feature-flags/src/index.ts
- packages/applications/feature-flags/tsconfig.json
- packages/applications/legacy/.env.template
- packages/applications/legacy/package.json
- packages/applications/legacy/tsconfig.json
- packages/applications/ssr/.env.template
- packages/applications/ssr/package.json
- packages/applications/ssr/src/app/elimine/[identifiant]/recours/demander/page.tsx
- packages/applications/ssr/src/app/elimine/[identifiant]/recours/page.tsx
- packages/applications/ssr/src/app/recours/page.tsx
- packages/applications/ssr/tsconfig.json
Ajout d'un feature flag sur Recours en prévision de la prochaine release.
La gestion des menus sera faite dans une autre PR.
> ✨ Feature flags recours

- package-lock.json
- package.json
- packages/applications/legacy/src/controllers/userAccount/postSignup.ts
- packages/applications/legacy/src/views/pages/Signup.tsx
Cette PR empêche de pouvoir ajouter du contenu html dans les champs firstname / lastname du formulaire d'inscription
En local, j'ai aussi utilisé la liste complète des nom utilisateur de la db pour tester la regex
> 🔒️ Nettoyage des inputs du formulaire d'inscription

- package-lock.json
- packages/applications/legacy/src/controllers/upload.ts
- packages/applications/legacy/src/server.ts
- packages/applications/legacy/src/views/components/MissingOwnerProjectList.tsx
- packages/applications/legacy/src/views/components/UI/molecules/InputFile.tsx
- packages/applications/legacy/src/views/pages/UploadLegacyModificationFilesPage.tsx
- packages/applications/legacy/src/views/pages/changerFournisseurPage/ChangerFournisseur.tsx
- packages/applications/legacy/src/views/pages/changerProducteurPage/ChangerProducteur.tsx
- packages/applications/legacy/src/views/pages/demanderChangementPuissancePage/components/ChangementPuissance.tsx
- packages/applications/legacy/src/views/pages/délai/CorrigerDelaiAccordePage.tsx
- packages/applications/legacy/src/views/pages/délai/DemanderDelaiPage.tsx
- packages/applications/legacy/src/views/pages/modificationRequestPage/components/PuissanceForm.tsx
- packages/applications/legacy/src/views/pages/modificationRequestPage/components/UploadResponseFile.tsx
- packages/applications/legacy/src/views/pages/newModificationRequestPage/components/actionnaire/ChangementActionnaire.tsx
- packages/applications/legacy/src/views/pages/newModificationRequestPage/components/recours/DemandeRecours.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/AttachFile.tsx
- packages/applications/legacy/src/views/pages/signalerDemandeDelaiPage/SignalerDemandeDelai.tsx
- packages/applications/legacy/src/views/pages/signalerDemandeRecoursPage/SignalerDemandeRecours.tsx
- packages/applications/ssr/src/components/atoms/form/UploadDocument.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/actuelles/enregistrerAttestation/enregistrerAttestationGarantiesFinancières.action.ts
[TICKET](https://github.com/MTES-MCT/potentiel/pull/2222)
- composant simple et générique InputFile avec affichage du nombre max de Mo/fichier qui remplace un ancien non utilisé
- Remplacement dans le legacy
> ♻️ ETQ porteur je veux savoir la limite dun fichier

- packages/applications/ssr/src/app/garanties-financieres/depots-en-cours/page.tsx
- packages/applications/ssr/src/components/organisms/garantiesFinancières/GarantiesFinancières.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/dépôt/lister/ListerDépôtsEnCoursGarantiesFinancières.page.tsx
fin de ça => https://linear.app/startup-potentiel/issue/POT-653/%5Bpp%5D-en-tant-que-pp-je-dois-acceder-au-suivi-de-mes-gf-comme-la-dgec
> ✏️ Wording for gfs

- packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
- packages/applications/ssr/src/components/molecules/NavLinks.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
> 🚸 Souligner le menu actif

- packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
Changement ordre menu
Vite fait bien fait => https://linear.app/startup-potentiel/issue/POT-702/modification-de-lordre-des-sous-menu-du-menu-candidatures
> ✏️ Change l'ordre du menu

- packages/applications/projectors/src/infrastructure/updateProjection.ts
_NB: La méthode existante `updateProjection` n'étant jamais utilisé, j'ai remplacé son implémentation, mais on peut introduire un nouveau nom si c'est plus parlant._
La nouvelle méthode `updateProjection` permet de mettre à jour une (ou plusieurs) clé(s) d'une projection sans la charger préalablement, en utilisant `jsonb_set`. 
A discuter: pour moi le besoin est surtout de mettre à jour une clé unique, donc une signature du style `updateProjection(id, "colonne_à_modifier", "value")` serait ok, voire préférable, mais c'est plus difficile à typer. 
Options:
- accepter plusieurs valeurs et faire une query par clé (implem actuelle)
- throw une erreur si plusieurs clés (🤮 mais simple et peu risqué)
- changer la signature en `updateProjection(id, "colonne_à_modifier", "value")` 
- changer la …
> ✨ Mise à jour d'une clé d'une projection

- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
> 🎨 Vérifier que le projet est éliminé pour proposer bouton pour demande de recours

- packages/applications/ssr/src/components/molecules/projet/ProjectListItemHeading.tsx
- packages/applications/ssr/src/components/pages/candidature/lister/CandidatureListItem.tsx
- packages/applications/ssr/src/components/pages/période/PériodeListItem.tsx
- packages/applications/ssr/src/components/templates/ListPage.template.tsx
Mini améliorations (centrage bouton, texte mieux espacé...)
> 📱 Quelques améliorations user friendly

- packages/applications/legacy/src/views/components/UI/organisms/Footer.tsx
- packages/applications/ssr/src/components/organisms/Footer.tsx
🚧 https://github.com/MTES-MCT/potentiel-keycloak/pull/26, puis mise à jour git submodule
> 💬 Ministère chargé de l'énergie

- packages/applications/scheduled-tasks/src/garanties-financières/récupérer-fichier-gf-candidature-référentiel-dgec.ts
> 🎨 Exclure les projets éliminés du script pour récupérer les fichiers GFs

- packages/applications/legacy/src/controllers/project/getProjectPage.ts
- packages/applications/legacy/src/modules/project/queries/GetProjectDataForProjectPage.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeader.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx
> 🎨 Afficher les informations d'une demande de recours en cours ou passée sur la page projet

- packages/applications/legacy/src/config/eventHandlers/project.eventHandlers.ts
- packages/applications/legacy/src/infra/sequelize/queries/project/getLegacyProjetByIdentifiantProjet.ts
- packages/applications/legacy/src/modules/project/eventHandlers/handleProjectRawDataCorrected.ts
- packages/applications/legacy/src/modules/project/eventHandlers/index.ts
- packages/applications/legacy/src/modules/project/events/ProjectRawDataCorrected.ts
- packages/applications/legacy/src/modules/project/events/index.ts
- packages/applications/legacy/src/sagas/candidature.saga.ts
l'event legacy `ProjectRawDataCorrected` est créé afin de déclancher `correctData` sur le module `Project`. En effet cette fonction se base sur l'état précédent du projet pour calculer les champs modifiés
> ✨ Mise à jour du Projet après correction de la candidature

- package-lock.json
- packages/applications/legacy/package.json
- packages/applications/legacy/webpack.config.js
Fix l'erreur lors du build du legacy
> 🔧 Ajout de vm-browserify en fallback dans la config webpack

- packages/applications/projectors/src/subscribers/candidature/candidature.projector.ts
- packages/domain/candidature/src/candidature.entity.ts
- packages/domain/candidature/src/consulter/consulterCandidature.query.ts
- packages/domain/candidature/src/corriger/corrigerCandidature.behavior.ts
- packages/domain/candidature/src/corriger/corrigerCandidature.command.ts
- packages/domain/candidature/src/corriger/corrigerCandidature.usecase.ts
- packages/domain/candidature/src/importer/importerCandidature.usecase.ts
- packages/domain/candidature/src/lister/listerCandidatures.query.ts
- packages/specifications/src/candidature/candidature.world.ts
- packages/specifications/src/candidature/corrigerCandidature.feature
- packages/specifications/src/candidature/fixtures/corrigerCandidature.fixture.ts
- packages/specifications/src/candidature/fixtures/importerCandidature.fixture.ts
- packages/specifications/src/candidature/stepDefinitions/candidature.given.ts
- packages/specifications/src/candidature/stepDefinitions/candidature.then.ts
- packages/specifications/src/candidature/stepDefinitions/candidature.when.ts
- packages/specifications/src/période/stepDefinitions/période.then.ts
Au passage, correction d'un problème sur la projection candidature : si une candidature est corrigée après notification, elle repasse en "à notifier"
> ✨ Corriger candidature sans détails

- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/page.tsx
Carte => https://linear.app/startup-potentiel/issue/POT-732/etq-pp-je-ne-dois-plus-avoir-acces-au-bouton-annuler-dune-demande
> 🐛 ETQ PP je ne dois pas pouvoir annuler une demande d'abandon confirmée (front)

- packages/applications/document-builder/src/candidature/attestation/attestation.saga.ts
- packages/applications/projectors/src/subscribers/candidature/candidature.projector.ts
- packages/applications/ssr/src/components/pages/candidature/détails/DétailsCandidature.page.tsx
- packages/applications/ssr/src/components/pages/période/PériodeListItem.tsx
- packages/domain/candidature/src/candidature.entity.ts
- packages/domain/candidature/src/consulter/consulterCandidature.query.ts
Pour remplacer la date dans la frise legacy 👋
> 🎨 Ajout des informations de designation

- packages/applications/ssr/src/components/molecules/projet/ProjetBanner.template.tsx
- Fix affichage projet banner
- Front
> 🐛 Fix affichage banner

- packages/applications/ssr/src/components/pages/abandon/demander/demanderAbandon.action.ts
- packages/applications/ssr/src/utils/zod/documentTypes.ts
- utilisation union
- check si autres cas (non :) )
> 🐛 Fix: document optional when abandon with recandidature

- packages/applications/ssr/src/components/molecules/projet/ProjectListItemHeading.stories.tsx
- packages/applications/ssr/src/components/molecules/projet/ProjetBanner.stories.tsx
- packages/applications/ssr/src/components/molecules/projet/ProjetBanner.tsx
- packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.stories.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.stories.tsx
- packages/applications/ssr/src/components/pages/abandon/lister/AbandonList.stories.tsx
- packages/applications/ssr/src/components/pages/attestation-conformité/modifier/modifierAttestationConformité.stories.tsx
- packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/ProjetNonSoumisAuxGarantiesFinancières.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/actuelles/enregistrer/EnregistrerGarantiesFinancières.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/actuelles/enregistrerAttestation/EnregistrerAttestationGarantiesFinancières.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/actuelles/modifier/ModifierGarantiesFinancièresActuelles.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/dépôt/modifier/ModifierDépôtEnCoursGarantiesFinancières.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/dépôt/soumettre/ProjetADéjàUnDépôtEnCours.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/dépôt/soumettre/SoumettreGarantiesFinancières.stories.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.stories.tsx
- packages/applications/ssr/src/components/pages/période/PériodeList.stories.tsx
- packages/applications/ssr/src/components/pages/recours/demander/DemanderRecours.stories.tsx
- packages/applications/ssr/src/components/pages/recours/détails/DétailsRecours.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/gestionnaire/modifier/ModifierGestionnaireRéseau.page.tsx
- packages/applications/ssr/src/components/pages/réseau/gestionnaire/modifier/ModifierGestionnaireRéseau.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/détails/DétailsRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierPropositionTechniqueEtFinancière/ModifierPropositionTechniqueEtFinancière.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDateMiseEnService/TransmettreDateMiseEnService.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettrePropositionTechniqueEtFinancière/TransmettrePropositionTechniqueEtFinancière.stories.tsx
- petits fix
- fix match undefined quand logger
> 🐛  Fix storybook

- packages/applications/ssr/src/components/pages/représentant-légal/demander-changement/DemanderChangementReprésentantLégal.form.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/demander-changement/DemanderChangementReprésentantLégal.page.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/demander-changement/DemanderChangementReprésentantLégal.stories.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/demander-changement/demanderChangementReprésentantLégal.action.ts
> 💄 Page pour demander un changement de représentant légal

- package-lock.json
- packages/applications/bootstrap/src/middlewares/log.middleware.ts
- packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
- packages/applications/ssr/src/app/reseaux/raccordements/page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/lister/DossierRaccordementList.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/lister/DossierRaccordementList.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/lister/DossierRaccordementListItem.tsx
- packages/domain/réseau/src/raccordement/index.ts
- packages/domain/réseau/src/raccordement/lister/listerDossierRaccordement.query.ts
- packages/domain/réseau/src/raccordement/raccordement.entity.ts
- packages/domain/réseau/src/raccordement/raccordement.register.ts
- packages/domain/utilisateur/src/role.valueType.ts
Cette PR ajoute le listing des dossiers de raccordement pour les admins (dans un premier temps)
> ✨ Lister les dossiers de raccordement

- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/gestionnaire:modifier/page.tsx
- packages/applications/ssr/src/app/reseaux/raccordements/importer/page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/GestionnaireRéseauSelect.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/ImporterDatesMiseEnService.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/ImporterDatesMiseEnService.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/ImporterDatesMiseEnService.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.stories.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.form.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.page.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.stories.tsx
> ♻️ Refactor isomorphisme Raccordement - part 1

- packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
carte => https://linear.app/startup-potentiel/issue/POT-800/modification-du-wording-de-la-page-notifier-des-candidats-pour-les
> 🎨 Changement menu wording

- packages/specifications/src/setup.ts
- packages/specifications/src/utilisateur/fixtures/system.fixture.ts
- packages/specifications/src/utilisateur/utilisateur.world.ts
> ✨ Ajout d'une fixture pour l'utilisateur system (pour les tests)

- packages/applications/ssr/src/components/organisms/List.tsx
> 🐛 Tmp fix: list for période

- packages/applications/legacy/src/infra/mail/mailjet.ts
- packages/applications/notifications/src/subscribers/période/période.notification.ts
> 🎨 Bug email template

- packages/applications/ssr/src/components/pages/attestation-conformité/AttestationConformité.form.tsx
> 🎨 changement du wording lors du dépôt de l'attestation de conformité

- packages/specifications/src/projet/éliminé/stepDefinitions/éliminé.given.ts
- packages/specifications/src/projet/éliminé/éliminé.world.ts
> ✅ Refacto: projet eliminé est une candidature

- packages/applications/ssr/src/app/candidatures/[identifiant]/telecharger-attestation/route.ts
> 🔀 Intégration des modifications de la release 3.34

- packages/applications/document-builder/src/candidature/attestation/ppe2/v2/Laureat.tsx
> 🎨 Changement wording dans template ppe2.V2 pour AO Batiment période 8

- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.page.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/modifier/ModifierReprésentantLégal.form.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/modifier/steps/SaisieTypePersonne.step.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/modifier/steps/Validation.step.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/modifier/steps/_utils/getInfosBasedOnTypeReprésentant.tsx
> 💬 Représentant légal : wording après test sur la modification 

- packages/applications/legacy/src/views/components/MissingOwnerProjectList.tsx
Bug remonté par Mathieu, on ne pouvait plus réclamer de projets car tout les inputFile du form étaient requis.
> 🚑️ Les porteurs ne pouvaient plus réclamer leurs projets

- packages/applications/legacy/src/views/components/MissingOwnerProjectList.tsx
Mettre le bouton après le formulaire
> 🎨 Mettre le bouton d'action après le formulaire

- packages/domain/entity/src/find.ts
- packages/domain/entity/src/index.ts
- packages/domain/entity/src/selectOptions.ts
- packages/infrastructure/pg-projections/src/findProjection.test.ts
- packages/infrastructure/pg-projections/src/findProjection.ts
- packages/infrastructure/pg-projections/src/getSelectClause.ts
> ✨ select in findProjection

- packages/domain/entity/src/find.ts
> 🐛 Fix select

- packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
- packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
- packages/applications/ssr/src/app/reseaux/raccordements/page.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
- packages/domain/réseau/src/raccordement/lister/listerDossierRaccordement.query.ts
- packages/domain/réseau/src/raccordement/raccordement.entity.ts
- packages/domain/utilisateur/src/role.valueType.ts
Rebuild à prévoir sur raccordement
> ✨ Ajout menu raccordement pour DREAL

- docker-compose.yml
- docs/contributing/GETTING_STARTED.md
- keycloak/import/realm-dev.json
- packages/applications/cli/src/commands/users/invite.ts
- packages/domain/utilisateur/src/role.valueType.ts
```bash
cd packages/applications/cli
npx tsx -r dotenv/config ./bin/dev.js users invite new-user@test.test --role grd --group 17X100A100A0001A
```
voir l'interface d'emails sur http://localhost:8025/
> ✨ Inviter utilisateur

- cron.json
This reverts commit bb82c0d62debbd657adf9dae439eac699de363d6.
> Revert "🐛 Désactiver le cron de notification des GRD pour revenir à la limite scalingo (#2515)"

- packages/domain/inmemory-referential/src/appelOffre/PPE2/ppe2.neutre.ts
https://linear.app/startup-potentiel/issue/POT-922/ouverture-p3-ao-neutre
> ✨ Ouverture de la période 3 de l'appel d'offre PPE2 Neutre

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getAlertesRaccordement.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getGarantiesFinancières.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getRaccordement.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/index.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx
- packages/domain/utilisateur/src/role.valueType.ts
Porteur ou Admin, avec raccordement (NB: en fait, Admin ne voit pas `ou lever`, seul le PP le voit)
Porteur ou Admin sans raccordement
CRE avec raccordement
CRE sans raccordement
CRE sans GF ni raccordement
> 💬 Liens Raccordement et GF de la page projet, par role

- package-lock.json
- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/projectors/src/subscribers/lauréat/changement-actionnaire/handleDemandeChangementActionnaireAnnulée.ts
- packages/applications/projectors/src/subscribers/lauréat/changement-actionnaire/index.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.aggregate.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.register.ts
- packages/domain/lauréat/src/actionnaire/annulerDemandeChangement/annulerDemandeChangement.behavior.ts
- packages/domain/lauréat/src/actionnaire/annulerDemandeChangement/annulerDemandeChangement.command.ts
- packages/domain/lauréat/src/actionnaire/annulerDemandeChangement/annulerDemandeChangement.usecase.ts
- packages/domain/lauréat/src/actionnaire/errors.ts
- packages/domain/lauréat/src/actionnaire/index.ts
- packages/specifications/src/projet/lauréat/actionnaire/actionnaire.world.ts
- packages/specifications/src/projet/lauréat/actionnaire/annulerDemandeChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/demanderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/fixtures/annulerDemandeChangementActionnaire.fixture.ts
- packages/specifications/src/projet/lauréat/actionnaire/fixtures/demanderChangementActionnaire.fixture.ts
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.given.ts
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.then.ts
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.when.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/demanderChangementReprésentantLégal.feature
> ✨ Annuler demande changement actionnaire

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getReprésentantLégal.ts
> 🐛 Ne pas déclencher l'appel query de la demande de représentant légal si la feature n'est pas activée

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/handleChangementActionnaireDemandé.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/handleDemandeChangementActionnaireAccordée.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/handleDemandeChangementActionnaireRejetée.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/index.ts
- packages/domain/lauréat/src/actionnaire/accorderDemandeChangement/accorderDemandeChangement.behavior.ts
- packages/domain/lauréat/src/actionnaire/accorderDemandeChangement/accorderDemandeChangement.command.ts
- packages/domain/lauréat/src/actionnaire/accorderDemandeChangement/accorderDemandeChangement.usecase.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.aggregate.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.entity.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.register.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.saga.ts
- packages/domain/lauréat/src/actionnaire/consulterDemandeChangement/consulterChangementActionnaire.query.ts
- packages/domain/lauréat/src/actionnaire/demanderChangement/demandeChangement.behavior.ts
- packages/domain/lauréat/src/actionnaire/index.ts
- packages/domain/lauréat/src/actionnaire/rejeterDemandeChangement/rejeterDemandeChangement.behavior.ts
- packages/domain/lauréat/src/actionnaire/rejeterDemandeChangement/rejeterDemandeChangement.command.ts
- packages/domain/lauréat/src/actionnaire/rejeterDemandeChangement/rejeterDemandeChangement.usecase.ts
- packages/domain/lauréat/src/actionnaire/statutChangementActionnaire.valueType.ts
- packages/specifications/src/projet/lauréat/actionnaire/accorderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/actionnaire.world.ts
- packages/specifications/src/projet/lauréat/actionnaire/annulerDemandeChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/demanderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/fixtures/accorderChangementActionnaire.fixture.ts
- packages/specifications/src/projet/lauréat/actionnaire/fixtures/rejeterDemandeChangementActionnaire.fixture.ts
- packages/specifications/src/projet/lauréat/actionnaire/rejeterDemandeChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.given.ts
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.then.ts
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.when.ts
Rejeter demande actionnaire
Specs
> ✨ Rejeter demande changement actionnaire

- packages/applications/projectors/src/subscribers/lauréat/actionnaire/handleChangementActionnaireDemandé.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/handleDemandeChangementActionnaireAnnulée.ts
- packages/domain/lauréat/src/actionnaire/statutChangementActionnaire.valueType.ts
- packages/specifications/src/projet/lauréat/actionnaire/accorderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/actionnaire.world.ts
- packages/specifications/src/projet/lauréat/actionnaire/demanderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/rejeterDemandeChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.then.ts
- Problème de projection
- Nouveaux tests
- Nouveau set up test (// abandon) plus juste
SPECs
> 🐛 Actionnaire : fix annuler et permettre nouvelle demande

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/handleActionnaireTransmis.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/index.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.aggregate.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.register.ts
- packages/domain/lauréat/src/actionnaire/errors.ts
- packages/domain/lauréat/src/actionnaire/index.ts
- packages/domain/lauréat/src/actionnaire/transmettre/transmettreActionnaire.behavior.ts
- packages/domain/lauréat/src/actionnaire/transmettre/transmettreActionnaire.command.ts
- packages/domain/lauréat/src/actionnaire/transmettre/transmettreActionnaire.usecase.ts
- packages/specifications/src/projet/lauréat/actionnaire/actionnaire.world.ts
- packages/specifications/src/projet/lauréat/actionnaire/fixtures/transmettreActionnaire.fixture.ts
- packages/specifications/src/projet/lauréat/actionnaire/modifierActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.when.ts
- packages/specifications/src/projet/lauréat/actionnaire/transmettreActionnaire.feature
- packages/specifications/src/projet/lauréat/stepDefinitions/lauréat.given.ts
nouveau usecase
specs
Sera utile dans le cas où une candidature sans société mère a été notifiée
> ✨ Transmettre actionnaire

- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/handleChangementReprésentantLégalAccordé.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/handleChangementReprésentantLégalRejeté.ts
- packages/applications/ssr/src/components/pages/représentant-légal/changement/détails/accorder/accorderChangementReprésentantLégal.action.ts
- packages/applications/ssr/src/components/pages/représentant-légal/changement/détails/rejeter/rejeterChangementReprésentantLégal.action.ts
- packages/domain/lauréat/src/représentantLégal/changement/accorder/accorderChangementReprésentantLégal.behavior.ts
- packages/domain/lauréat/src/représentantLégal/changement/accorder/accorderChangementReprésentantLégal.command.ts
- packages/domain/lauréat/src/représentantLégal/changement/accorder/accorderChangementReprésentantLégal.usecase.ts
- packages/domain/lauréat/src/représentantLégal/changement/rejeter/rejeterChangementReprésentantLégal.behavior.ts
- packages/domain/lauréat/src/représentantLégal/changement/rejeter/rejeterChangementReprésentantLégal.command.ts
- packages/domain/lauréat/src/représentantLégal/changement/rejeter/rejeterChangementReprésentantLégal.usecase.ts
- packages/domain/lauréat/src/représentantLégal/index.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/accorderChangementReprésentantLégal.feature
- packages/specifications/src/projet/lauréat/représentant-légal/changement/rejeterChangementReprésentantLégal.feature
- packages/specifications/src/projet/lauréat/représentant-légal/changement/stepDefinitions/changemementReprésentantLégal.when.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/stepDefinitions/changementReprésentantLégal.given.ts
> 🎨 Notifier la dreal suite à une instruction automatique de changement de représentant légal

- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/handleChangementReprésentantLégalRejeté.ts
- packages/applications/ssr/src/components/pages/représentant-légal/changement/détails/DétailsChangementReprésentantLégal.page.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/changement/détails/rejeter/RejeterChangementReprésentantLégal.form.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/changement/détails/rejeter/rejeterChangementReprésentantLégal.action.ts
- packages/domain/lauréat/src/représentantLégal/changement/changementReprésentantLégal.entity.ts
- packages/domain/lauréat/src/représentantLégal/changement/consulter/consulterChangementReprésentantLégal.query.ts
- packages/domain/lauréat/src/représentantLégal/changement/rejeter/rejeterChangementReprésentantLégal.behavior.ts
- packages/domain/lauréat/src/représentantLégal/changement/rejeter/rejeterChangementReprésentantLégal.command.ts
- packages/domain/lauréat/src/représentantLégal/changement/rejeter/rejeterChangementReprésentantLégal.usecase.ts
- packages/domain/lauréat/src/représentantLégal/saga/handleTâchePlanifiéeGestionAutomatiqueDemandeChangementExecutée.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/changementReprésentantLégal.world.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/fixtures/rejeterChangementReprésentantLégal.fixture.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/stepDefinitions/changemementReprésentantLégal.when.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/stepDefinitions/changementReprésentantLégal.given.ts
> ✨ Ajout d'un motif obligatoire lors de rejet d'un changement de représentant légal

- packages/applications/ssr/.storybook/main.ts
- packages/applications/ssr/.storybook/mockedWithUtilisateur.js
- packages/applications/ssr/.storybook/preview.tsx
Hack pour withUtilisateur qui fait planter storybook
> 🐛 Correction Storybook

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/notifications/src/index.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/handleActionnaireModifié.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/handleChangementActionnaireDemandé.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/handleDemandeChangementActionnaireAccordée.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/handleDemandeChangementActionnaireAnnulée.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/handleDemandeChangementActionnaireRejetée.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/index.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/templateIds.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/handleDemandeChangementActionnaireAnnulée.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.aggregate.ts
- packages/domain/lauréat/src/actionnaire/changement/annuler/annulerChangementActionnaire.behavior.ts
- packages/domain/lauréat/src/actionnaire/index.ts
- packages/specifications/src/projet/lauréat/actionnaire/accorderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/annulerDemandeChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/demanderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/modifierActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/rejeterDemandeChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.then.ts
Toutes les notifications actionnaires
[Détails de la carte](https://linear.app/startup-potentiel/issue/POT-903/[actionnaire]-etq-dreal-ou-pp-je-suis-alerte-lors-des-diverses-actions)
Les templates ont été crées dans mailjet
Test
> ✨ Notification actionnaire

- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoActionnaire.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
- packages/applications/ssr/src/components/pages/actionnaire/modifier/modifierActionnaire.action.ts
- packages/domain/lauréat/src/actionnaire/changement/demander/demandeChangementActionnaire.behavior.ts
- packages/domain/lauréat/src/actionnaire/changement/demander/demandeChangementActionnaire.command.ts
- packages/domain/lauréat/src/actionnaire/errors.ts
- packages/domain/lauréat/src/actionnaire/modifier/modifierActionnaire.behavior.ts
- packages/domain/lauréat/src/actionnaire/modifier/modifierActionnaire.command.ts
- packages/domain/lauréat/src/actionnaire/modifier/modifierActionnaire.usecase.ts
- packages/specifications/src/projet/lauréat/actionnaire/demanderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/modifierActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.when.ts
ISO actuel
- Bloquer le bouton Demande ou Modification pour le porteur si conditions sur CDC
- Bloquer le lien vers Demande ou Modification sur la page projet pour le porteur si conditions sur CDC
- Back => bloqué pour abandon / attestation de conformité
- Front => à mutualiser avec ce qu'à fait Hub, j'attends qu'il merge
> 🎨 Ajout règle CDC pour actionnaire

- package-lock.json
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/handleChangementReprésentantLégalRejeté.ts
- packages/domain/lauréat/src/représentantLégal/saga/handleTâchePlanifiéeGestionAutomatiqueDemandeChangementExecutée.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/accorderChangementReprésentantLégal.feature
- packages/specifications/src/projet/lauréat/représentant-légal/changement/changementReprésentantLégal.world.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/fixtures/rejeterChangementReprésentantLégal.fixture.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/rejeterChangementReprésentantLégal.feature
- packages/specifications/src/projet/lauréat/représentant-légal/changement/stepDefinitions/changemementReprésentantLégal.when.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/stepDefinitions/changementReprésentantLégal.given.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/stepDefinitions/changementReprésentantLégal.then.ts
- packages/specifications/src/projet/lauréat/représentant-légal/modifierReprésentantLégal.feature
- packages/specifications/src/projet/lauréat/représentant-légal/stepDefinitions/représentantLégal.then.ts
- packages/specifications/src/shared/customParameters.ts
- packages/specifications/src/tâche-planifiée/fixtures/ajouterTâchePlanifiée.fixture.ts
- packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.given.ts
- packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.then.ts
- packages/specifications/src/tâche-planifiée/stepDefinitions/tâchePlanifiée.when.ts
- packages/specifications/src/tâche-planifiée/tâchePlanifiée.world.ts
- packages/specifications/src/utilisateur/stepDefinitions/utilisateur.given.ts
Ajout de tests pour vérifier l'exécution de la tâche planifiée
> ✨  Couvrir par des tests l'accord / rejet automatique d'un changement de représentant légal

- packages/applications/cli/src/commands/actionnaire/migration-actionnaire.sql
- packages/applications/cli/src/commands/actionnaire/migrer.ts
```
cd packages/applications/cli
npx tsx ./bin/dev.js actionnaire migrer
```
> 🚧 Migration actionnaire

- packages/applications/ssr/src/components/pages/actionnaire/demanderChangement/DemanderChangementActionnaire.form.tsx
- packages/applications/ssr/src/components/pages/actionnaire/demanderChangement/DemanderChangementActionnaire.page.tsx
- packages/applications/ssr/src/components/pages/actionnaire/demanderChangement/InfoxBoxDemandeActionnaire.tsx
- packages/applications/ssr/src/components/pages/actionnaire/modifier/ModifierActionnaire.form.tsx
> 🎨 Feat: ajout d'une infobox pour éolien

- packages/applications/ssr/src/components/pages/représentant-légal/changement/demander/DemanderChangementReprésentantLégal.form.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/changement/demander/DemanderChangementReprésentantLégal.page.tsx
[Ticket](https://linear.app/startup-potentiel/issue/POT-1009/faire-le-lien-vers-filigrane-depuis-la-demande-de-modification-du-rl)
> 💬 Ajout lien vers filigrane facile pour le stepper demander changement représentant légal

- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalAccordé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalAnnulé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalDemandé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalRejeté.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalSupprimé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/index.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/rebuildTriggered.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/représentantLégalImporté.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/représentantLégalModifié.projector.ts
https://mattermost.incubateur.net/fabnum-mte/pl/j8pdizgax7nwdn1wngzo5m1hwo
> 🚚 Appliquer la convention pour les event handlers des projectors de représentant légal

- packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger-par-lot/CorrigerCandidatures.page.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.page.tsx
- packages/applications/ssr/src/components/pages/candidature/détails/DétailsCandidature.page.tsx
Première carte du projet => https://linear.app/startup-potentiel/issue/POT-929/remettre-menu-correction-dans-candidatures
> 🎨 Quelques demandes pour la correction

- packages/specifications/src/raccordement/demandeComplèteRaccordement.world.ts
- packages/specifications/src/raccordement/modifierGestionnaireRéseauRaccordement.feature
- packages/specifications/src/raccordement/propositionTechniqueEtFinancière.world.ts
- packages/specifications/src/raccordement/raccordement.world.ts
- packages/specifications/src/raccordement/stepDefinitions/dateMiseEnService.given.ts
- packages/specifications/src/raccordement/stepDefinitions/dateMiseEnService.then.ts
- packages/specifications/src/raccordement/stepDefinitions/dateMiseEnService.when.ts
- packages/specifications/src/raccordement/stepDefinitions/demandeComplèteRaccordement.given.ts
- packages/specifications/src/raccordement/stepDefinitions/demandeComplèteRaccordement.then.ts
- packages/specifications/src/raccordement/stepDefinitions/demandeComplèteRaccordement.when.ts
- packages/specifications/src/raccordement/stepDefinitions/propositionTechniqueEtFinancière.given.ts
- packages/specifications/src/raccordement/stepDefinitions/propositionTechniqueEtFinancière.then.ts
- packages/specifications/src/raccordement/stepDefinitions/propositionTechniqueEtFinancière.when.ts
- packages/specifications/src/raccordement/stepDefinitions/raccordement.given.ts
- packages/specifications/src/raccordement/stepDefinitions/raccordement.then.ts
- packages/specifications/src/raccordement/stepDefinitions/raccordement.when.ts
suite aux remarques sur https://github.com/MTES-MCT/potentiel/pull/2630
> 🚚 Séparer les steps de raccordement en plusieurs fichiers

- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoActionnaire.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
> 🎨 Amélioration affichage actionnaire si actionnaire vide

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getActionnaire.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
> 🎨 Bloquer le front si abandon / achevement ETQ PP

- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalAccordé.notification.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/accorderChangementReprésentantLégal.feature
- packages/specifications/src/projet/lauréat/représentant-légal/changement/stepDefinitions/changemementReprésentantLégal.when.ts
> 🎨 Notification différente si l'administration corrige avant accord de la demande de changement de représentant légal 

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getActionnaire.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoActionnaire.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
> 🐛 Fix comportement ETQ PP

- packages/applications/notifications/src/subscribers/lauréat/actionnaire/changementActionnaireAnnulé.notifications.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/changementActionnaireDemandé.notifications.ts
- packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
- packages/domain/période/src/notifier/notifierPériode.command.ts
- packages/specifications/src/projet/lauréat/actionnaire/modifierActionnaire.feature
- packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/échoirGarantiesFinancièresActuelles.feature
- packages/specifications/src/projet/lauréat/représentant-légal/modifierReprésentantLégal.feature
- packages/specifications/src/période/notifierPériode.feature
- packages/specifications/src/période/stepDefinitions/période.given.ts
- packages/specifications/src/tâche-planifiée/exécuterTâchePlanifiée.feature
- Dreal manquantes pour des mails
- projection mainlevée mal fichue => ça devrait être refacto plus en profondeur à mon avis
- specs garanties financière échoir pas 100% testée
- tâche planifiée => meilleure conditions pour que la tâche existe vraiment
> 🧹 Nettoyage des erreurs dans les specs

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getActionnaire.ts
- packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/actionnaire/modifier/page.tsx
- packages/applications/ssr/src/app/laureats/changements/actionnaire/page.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
- packages/applications/ssr/src/components/pages/actionnaire/changement/ChangementActionnaireListItem.tsx
- packages/applications/ssr/src/components/pages/actionnaire/changement/détails/DétailsActionnaire.page.tsx
- packages/applications/ssr/src/components/pages/actionnaire/changement/détails/DétailsChangementActionnaire.tsx
- packages/applications/ssr/src/components/pages/actionnaire/demanderChangement/DemanderChangementActionnaire.page.tsx
- packages/applications/ssr/src/components/pages/actionnaire/modifier/ModifierActionnaire.form.tsx
- packages/applications/ssr/src/components/pages/actionnaire/modifier/ModifierActionnaire.page.tsx
- packages/applications/ssr/src/components/pages/actionnaire/modifier/modifierActionnaire.action.ts
[wording](https://linear.app/startup-potentiel/issue/POT-1030/modifications-wording)
[filtre](https://linear.app/startup-potentiel/issue/POT-1034/supprimer-filtre-annuler-de-la-liste-demande)
> 🎨 Review retirer filtre annuler filtre et modification de wording

- packages/applications/ssr/src/app/laureats/[identifiant]/representant-legal/changement/[date]/page.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/changement/détails/DétailsChangementReprésentantLégal.page.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/changement/détails/InfoBoxDemandeEnCours.tsx
- packages/specifications/src/notification/stepDefinitions/notification.then.ts
> 🎨 Ajout d'une info box avec lien vers demande si en cours

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getReprésentantLégal.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalAccordé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalCorrigé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/tâche-planifiée/garantiesFinancièresRappelÉchéance.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/tâche-planifiée/index.ts
- packages/applications/notifications/src/subscribers/lauréat/tâche-planifiée/représentantLégalRappelInstructionÀDeuxMois.notification.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/_utils/getInfosReprésentantLégal.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalAccordé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalAnnulé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalCorrigé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalRejeté.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/représentant-légal/changement/changementReprésentantLégalSupprimé.projector.ts
- packages/domain/lauréat/src/représentantLégal/changement/consulter/consulterChangementReprésentantLégalEnCours.query.ts
- packages/domain/lauréat/src/représentantLégal/index.ts
- packages/domain/lauréat/src/représentantLégal/représentantLégal.register.ts
- création d'une query pour récupérer demande de changement en cours
- utilitaire au niveau du projector
> ♻️ Récupérer la demande de changement de réprésentant légal en cours

- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
- **🔥 Retirer lien redondant Actionnaire (#2685)**
- **💚 Fix build on release 3.38 (#2686)**
> 🔀 Intégration des modifications de la release 3.38

- packages/applications/document-builder/src/candidature/attestation/ppe2/v2/Introduction.tsx
- packages/applications/document-builder/src/candidature/attestation/ppe2/v2/Laureat.tsx
- packages/applications/legacy/src/views/pages/changerFournisseurPage/ChangerFournisseur.tsx
- packages/applications/legacy/src/views/pages/demanderChangementPuissancePage/DemanderChangementPuissance.tsx
- packages/applications/legacy/src/views/pages/demanderChangementPuissancePage/components/ChangementPuissance.tsx
- packages/applications/legacy/src/views/pages/modificationRequestPage/components/DemandeDetails.tsx
- packages/applications/legacy/src/views/pages/modificationRequestPage/components/PuissanceForm.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
- packages/domain/appel-offre/src/appelOffre.entity.ts
Le type n'a plus de raison d'exister
> 🔥 Supprimer le type d'AO biométhane

- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.form.tsx
> 🎨 Ajouter label "aucun" si pas de type d'actionnariat

- packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDateMiseEnService/TransmettreDateMiseEnService.page.tsx
> 💬 Ajouter une définition de la date de Mise en service

- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalAccordé.notification.ts
- packages/domain/lauréat/src/représentantLégal/changement/accorder/accorderChangementReprésentantLégal.behavior.ts
- packages/specifications/src/projet/lauréat/représentant-légal/changement/accorderChangementReprésentantLégal.feature
- packages/specifications/src/setup.ts
[Erreur sentry](https://sentry.incubateur.net/organizations/betagouv/issues/147461/?query=is%3Aunresolved&referrer=issue-stream&stream_index=4) (problème d'utilisation d'une query dans le handler notif => la projection a déjà été updaté et donc plus de demande en cours)
> 🐛 Ajout à l'event d'une indication de correction avant validation pour demande changement RL

- docs/contributing/DEVELOPMENT_FLOW.md
- package-lock.json
- package.json
- packages/applications/document-builder/package.json
- packages/applications/ssr/package.json
> 🐛 Fix storybook documents + remove old SSR storybook mentions

- package-lock.json
- package.json
- turbo.json
https://turbo.build/repo/docs/crafting-your-repository/upgrading#upgrading-to-20
> ⬆️ Upgrade turbo to 2.4.1

- package-lock.json
- packages/applications/legacy/package.json
https://github.com/react-icons/react-icons/releases
> ⬆️ React-icons to 5.4.0

- package-lock.json
- packages/applications/legacy/package.json
https://github.com/FullHuman/purgecss/releases
> ⬆️ Postcss purgecss 7.0.2

- package-lock.json
Corrige 4 vulnérabilités liées à dompurify
voir https://github.com/MTES-MCT/potentiel/security/dependabot/127
> 🔒️ Mises à jour de sécurité lié à la vulnérabilité `dompurify`

- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.form.tsx
- packages/applications/ssr/src/components/pages/garanties-financières/TypeGarantiesFinancièresSelect.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/TypeReprésentantLégalSelect.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/GestionnaireRéseauSelect.tsx
L'utilisation de `defaultValue` ne fonctionne plus. Voir https://github.com/codegouvfr/react-dsfr/issues/387
> 🐛 Valeur par défaut dans le Select dsfr

- packages/applications/legacy/src/infra/sequelize/queries/project/getLegacyProjetByIdentifiantProjet.ts
- packages/applications/legacy/src/sagas/candidature.saga.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/EditProjectData.tsx
- packages/applications/ssr/src/app/candidatures/[identifiant]/corriger/page.tsx
- packages/applications/ssr/src/components/atoms/form/FormAlertError.tsx
- packages/applications/ssr/src/components/atoms/form/FormFeedback.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger-par-lot/CorrigerCandidatures.page.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.page.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/ModifierLauréat.form.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/modifierLauréat.action.ts
- packages/applications/ssr/src/utils/zod/candidature/candidatureNotifiée.schema.ts
- amélioration des refine pour les erreurs de validation dans le formulaire candidature,
- fix saga legacy suite à correction candidature (individuelle ou par lot)
- information sur ces 2 pages pour l'utilisateur admin
- Cas éliminé pour lauréat form
Pas mal de tests fonctionnel
> 🐛 Correction candidature saga legacy

- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/page.tsx
- packages/applications/ssr/src/components/molecules/historique/timeline/abandon/mapToAbandonPasséEnInstructionTimelineItemProps.tsx
- packages/applications/ssr/src/components/molecules/historique/timeline/abandon/mapToAbandonTimelineItemProps.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.page.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/passerEnInstruction/PasserAbandonEnInstruction.tsx
- packages/applications/ssr/src/components/pages/abandon/détails/passerEnInstruction/passerAbandonEnInstruction.action.ts
- packages/domain/utilisateur/src/role.valueType.ts
- bouton instruire
- filtre par le statut en instruction dans la liste
- historique et détails revisités 
> ✨ Instruction abandon front

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getReprésentantLégal.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/EditProjectData.tsx
- packages/applications/ssr/src/app/candidatures/[identifiant]/corriger/page.tsx
- packages/applications/ssr/src/app/candidatures/[identifiant]/page.tsx
- packages/applications/ssr/src/app/candidatures/_helpers/getCandidature.ts
- packages/applications/ssr/src/app/candidatures/_helpers/getCandidatureActions.ts
- packages/applications/ssr/src/app/candidatures/_helpers/getCandidatureListActions.ts
- packages/applications/ssr/src/app/candidatures/page.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger-par-lot/CorrigerCandidatures.page.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.form.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.page.tsx
- packages/applications/ssr/src/components/pages/candidature/détails/DétailsCandidature.page.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/fields/ModifierLauréatFields.tsx
cf [carte](https://linear.app/startup-potentiel/issue/POT-1183/test-release-343) 
Quelques simplifications pour gagner en cohérence
> 🐛 Amélioration lien et infobox des formulaire de correction candidature et projet

- packages/applications/ssr/src/components/pages/lauréat/modifier/fields/LocalitéField.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/fields/ModifierLauréatFields.tsx
> 🎨 Amélioration du comportement du cadenas si valeur projet modifiée

- packages/applications/ssr/src/components/pages/lauréat/modifier/fields/LocalitéField.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/fields/ModifierLauréatFields.tsx
> 🔀 Intégration des modifications de la release 3.43

- packages/applications/ssr/src/components/pages/candidature/corriger-par-lot/CorrigerCandidatures.page.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.page.tsx
> 🎨 Derniers correctifs sur infobox pour les pages de correction de candidature

- package-lock.json
- packages/applications/ssr/package.json
- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.form.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/fields/ActionnariatField.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/fields/TechnologieField.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/TypeReprésentantLégalSelect.tsx
- packages/applications/ssr/src/components/pages/réseau/raccordement/GestionnaireRéseauSelect.tsx
Suite à la résolution de https://github.com/codegouvfr/react-dsfr/issues/387
> ⬆️ Mise à jour DSFR + retirer le fix temporaire

- package-lock.json
- packages/applications/legacy/package.json
- packages/applications/legacy/src/views/components/UI/atoms/icons.ts
- packages/applications/legacy/src/views/components/UI/organisms/Header.tsx
- packages/applications/ssr/src/components/molecules/UserHeaderQuickAccessItem.tsx
> 💄 Ajout d'un badge pour le nombre des tâches à faire dans le header

- packages/domain/entity/src/where/include.ts
- packages/domain/entity/src/where/index.ts
- packages/domain/entity/src/where/notInclude.ts
- packages/domain/entity/src/whereOptions.ts
- packages/infrastructure/pg-projections/src/getWhereClause.ts
- packages/infrastructure/pg-projections/src/listProjection.test.ts
Cet opérateur permet de vérifier la présence d'un élement dans un array.
Fait suite au renommage dans #2823
> ✨ Include operator

- packages/applications/ssr/src/app/auth/signIn/page.tsx
- packages/applications/ssr/src/components/organisms/auth/LoginMethodTile.tsx
> 🐛 Correction de l'affichage des tiles des methodes de login

- packages/applications/ssr/src/components/pages/attestation-conformité/AttestationConformité.form.tsx
- packages/applications/ssr/src/components/pages/attestation-conformité/modifier/modifierAttestationConformité.action.ts
- packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.action.ts
- packages/applications/ssr/src/components/pages/représentant-légal/changement/corriger/corrigerChangementReprésentantLégal.action.ts
- packages/applications/ssr/src/utils/zod/document/keepOrUpdateDocument.ts
> ✨ Feat enable multi docs upload for attestation de conformité

- packages/applications/ssr/src/components/pages/abandon/détails/passerEnInstruction/passerAbandonEnInstruction.action.ts
- packages/applications/ssr/src/components/pages/recours/détails/passerEnInstruction/passerRecoursEnInstruction.action.ts
> 🐛  Fix redirection pour instruction recours ou abandon

- packages/domain/candidature/src/corriger/corrigerCandidature.behavior.ts
> 🐛 Apply candidature corrigée

- packages/applications/cli/src/commands/users/migrer.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact.tsx
- packages/applications/ssr/src/app/reclamer/page.tsx
- packages/applications/ssr/src/components/pages/réclamer-projets/RéclamerProjetsListItem.tsx
- packages/domain/candidature/tsconfig.json
- packages/domain/utilisateur/src/lister/listerProjetsÀRéclamer.query.ts
- packages/domain/utilisateur/src/réclamer/réclamerProjet.behavior.ts
- packages/domain/utilisateur/src/réclamer/réclamerProjet.command.ts
- packages/specifications/src/utilisateur/réclamerProjet.feature
- packages/specifications/src/utilisateur/stepDefinitions/utilisateur.when.ts
& fix dans le script de migration pour gérér les utilisateurs en doublon dans le legacy
& fix UI dans la liste des projets à réclamer (ajouter AO et Période)
> 🐛 Impossible de réclamer un projet non notifiés + retours staging

- packages/specifications/src/projet/lauréat/puissance/accorderChangementPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/annulerChangementPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/demanderChangementPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/enregistrerChangementPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/importerPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/modifierPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/rejeterChangementPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/supprimerChangementPuissance.feature
Specs backend puissance
Commentaires pour aider pour les fixtures
> ✨ Specs puissance

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/legacy/src/sagas/puissance.saga.ts
- packages/applications/legacy/src/sagas/registerSagas.ts
- packages/applications/legacy/src/views/pages/modificationRequestPage/components/PuissanceForm.tsx
- packages/applications/projectors/src/subscribers/lauréat/puissance/index.ts
- packages/applications/projectors/src/subscribers/lauréat/puissance/puissanceModifiée.projector.ts
- packages/domain/lauréat/src/puissance/errors.ts
- packages/domain/lauréat/src/puissance/importer/importerPuissance.behavior.ts
- packages/domain/lauréat/src/puissance/index.ts
- packages/domain/lauréat/src/puissance/modifier/modifierPuissance.behavior.ts
- packages/domain/lauréat/src/puissance/modifier/modifierPuissance.command.ts
- packages/domain/lauréat/src/puissance/modifier/modifierPuissance.usecase.ts
- packages/domain/lauréat/src/puissance/puissance.aggregate.ts
- packages/domain/lauréat/src/puissance/puissance.register.ts
- packages/specifications/src/projet/lauréat/puissance/fixture/modifierPuissance.fixture.ts
- packages/specifications/src/projet/lauréat/puissance/modifierPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/puissance.world.ts
- packages/specifications/src/projet/lauréat/puissance/stepDefinitions/puissance.then.ts
- packages/specifications/src/projet/lauréat/puissance/stepDefinitions/puissance.when.ts
cf specs
cf carte dans Linéar
Specs
> ✨ Puissance ETQ admin je peux modifier la puissance (domain)

- packages/applications/legacy/.env.template
- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getPuissance.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoPuissance.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
- packages/applications/routes/src/index.ts
- packages/applications/routes/src/lauréat/index.ts
- packages/applications/routes/src/lauréat/puissance.routes.ts
- packages/applications/ssr/.env.template
- packages/domain/utilisateur/src/role.valueType.ts
- consulter puissance sur la page projet
- feature flag
- Intégration du bouton modifier, avec une route "vide" pour le moment
> ✨ Consulter puissance (page projet) et FF

- packages/applications/ssr/src/components/molecules/historique/HistoriqueTimeline.tsx
- packages/applications/ssr/src/components/molecules/historique/timeline/représentant-légal/index.tsx
- packages/applications/ssr/src/components/molecules/historique/timeline/représentant-légal/mapToChangementReprésentantLégalCorrigéTimelineItemProps.tsx
- packages/applications/ssr/src/components/molecules/historique/timeline/représentant-légal/mapToChangementReprésentantLégalDemandéTimelineItemProps.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/_utils/steps/SaisiePièceJustificative.step.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/_utils/steps/SaisieType.step.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/_utils/steps/SaisieTypeSociété.step.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/_utils/steps/Validation.step.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/changement/corriger/CorrigerChangementReprésentantLégal.form.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/changement/corriger/corrigerChangementReprésentantLégal.action.ts
- packages/applications/ssr/src/components/pages/représentant-légal/changement/demander/DemanderChangementReprésentantLégal.form.tsx
- packages/applications/ssr/src/components/pages/représentant-légal/changement/demander/demanderChangementReprésentantLégal.action.ts
- packages/applications/ssr/src/components/pages/représentant-légal/modifier/ModifierReprésentantLégal.form.tsx
- packages/applications/ssr/src/utils/zod/blob/mergePdfDocuments.ts
> ✨ Différencier les sociétés constituées des sociétés en cours  pour le type de RL "personne morale"

- packages/applications/ssr/src/app/laureats/[identifiant]/puissance/modifier/page.tsx
- packages/applications/ssr/src/components/pages/puissance/modifier/ModifierPuissance.form.tsx
- packages/applications/ssr/src/components/pages/puissance/modifier/ModifierPuissance.page.tsx
- packages/applications/ssr/src/components/pages/puissance/modifier/modifierPuissance.action.ts
- Formulaire de modification du formulaire
- Je n'ai pas mis le feature flag sur le formulaire de modification du lauréat, car cela va créer trop d'incohérences sur la valeur de puissance
> ✨ V1 puissance formulaire de modification

- packages/applications/projectors/src/subscribers/lauréat/puissance/puissanceRebuildTrigerred.projector.ts
- packages/domain/lauréat/src/puissance/changement/changementPuissance.entity.ts
- packages/domain/lauréat/src/puissance/changementPuissance.ts
- packages/domain/lauréat/src/puissance/index.ts
- packages/domain/lauréat/src/puissance/statutChangementPuissance.valueType.ts
> 🎨 puissance v2 Initialisation puissance entity et statut

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/projectors/src/subscribers/lauréat/actionnaire/changementActionnaireAnnulé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/puissance/changementPuissanceAnnulé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/puissance/index.ts
- packages/domain/lauréat/src/puissance/changement/annuler/annulerChangementPuissance.behavior.ts
- packages/domain/lauréat/src/puissance/changement/annuler/annulerChangementPuissance.command.ts
- packages/domain/lauréat/src/puissance/changement/annuler/annulerChangementPuissance.usecase.ts
- packages/domain/lauréat/src/puissance/changement/demander/demanderChangementPuissance.behavior.ts
- packages/domain/lauréat/src/puissance/changement/errors.ts
- packages/domain/lauréat/src/puissance/errors.ts
- packages/domain/lauréat/src/puissance/index.ts
- packages/domain/lauréat/src/puissance/puissance.aggregate.ts
- packages/domain/lauréat/src/puissance/puissance.register.ts
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.given.ts
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.when.ts
- packages/specifications/src/projet/lauréat/puissance/annulerChangementPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/fixture/annulerChangementPuissance.fixture.ts
- packages/specifications/src/projet/lauréat/puissance/puissance.world.ts
- packages/specifications/src/projet/lauréat/puissance/stepDefinitions/puissance.then.ts
- packages/specifications/src/projet/lauréat/puissance/stepDefinitions/puissance.when.ts
> ✨ Annuler demande changement puissance - domain

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/projectors/src/subscribers/lauréat/puissance/changementPuissanceSupprimé.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/puissance/index.ts
- packages/domain/lauréat/src/actionnaire/actionnaire.aggregate.ts
- packages/domain/lauréat/src/actionnaire/changement/supprimer/supprimerChangementActionnaire.command.ts
- packages/domain/lauréat/src/puissance/changement/supprimer/supprimerChangementPuissance.behavior.ts
- packages/domain/lauréat/src/puissance/changement/supprimer/supprimerChangementPuissance.command.ts
- packages/domain/lauréat/src/puissance/index.ts
- packages/domain/lauréat/src/puissance/puissance.aggregate.ts
- packages/domain/lauréat/src/puissance/puissance.register.ts
- packages/domain/lauréat/src/puissance/saga/abandonAccordé.saga.ts
- packages/domain/lauréat/src/puissance/saga/index.ts
- packages/specifications/src/projet/lauréat/puissance/stepDefinitions/puissance.then.ts
- packages/specifications/src/projet/lauréat/puissance/supprimerChangementPuissance.feature
> ✨ Supprimer demande puissance lorsqu'un abandon est accordé

- packages/applications/legacy/src/infra/keycloak/attachUserToRequestMiddleware.ts
Résolution pour [POTENTIEL-D0](https://sentry.incubateur.net/organizations/betagouv/issues/136353/?environment=production&project=155) et [POTENTIEL-W5](https://sentry.incubateur.net/organizations/betagouv/issues/164760/?environment=production&project=155)
> 🐛 Ignorer certains paths dans l'authentification legacy

- packages/applications/ssr/src/app/elimine/[identifiant]/recours/modele-reponse/route.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/modele-reponse/route.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/actionnaire/changement/modele-reponse/route.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/modele-mise-en-demeure/route.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/modele-reponse-mainlevee/route.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/puissance/changement/modele-reponse/route.ts
- packages/applications/ssr/src/utils/modèle-document/getDocumentHeader.ts
- packages/applications/ssr/src/utils/modèle-document/getDocxDocumentHeader.ts
> ♻️ Utilitaire pour harmoniser les nom des modèles de réponse

- packages/applications/legacy/src/modules/modificationRequest/dtos/ModificationRequestListItemDTO.ts
- packages/applications/legacy/src/views/components/timeline/components/ModificationReceivedItem.tsx
- packages/applications/legacy/src/views/components/timeline/components/ModificationRequestItem.tsx
- packages/applications/legacy/src/views/components/timeline/helpers/extractModificationRequestsItemProps.ts
- packages/applications/legacy/src/views/pages/modificationRequestListPage/ModificationRequestList.tsx
- Lien dans la frise (difficile de mettre le bon lien)
- demande liste
> 🐛 Fix: puissance legacy a supprimer avant MEP

- packages/applications/legacy/src/sagas/puissance.saga.ts
Bon mapping par rapport aux evenement legacy 
> 🐛 Fix saga puissance

- packages/applications/ssr/src/app/laureats/[identifiant]/puissance/changement/demander/page.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissance.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissance.page.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissanceFormErrors.tsx
- packages/domain/lauréat/src/puissance/valueType/helpers/dépassePuissanceMaxDuVolumeRéservé.ts
- packages/domain/lauréat/src/puissance/valueType/helpers/dépassePuissanceMaxFamille.ts
- packages/domain/lauréat/src/puissance/valueType/helpers/dépasseRatiosChangementPuissance.ts
- packages/domain/lauréat/src/puissance/valueType/helpers/getRatiosChangementPuissance.ts
- packages/domain/lauréat/src/puissance/valueType/helpers/récupérerVolumeRéservé.ts
- packages/domain/lauréat/src/puissance/valueType/ratioChangementPuissance.valueType.ts
Pour comparaison : `packages/applications/legacy/src/views/pages/demanderChangementPuissancePage/components/ChangementPuissance.tsx`
> ✨  Implémentation des règles de ratios dans le formulaire de demande

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getPuissance.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeader.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoPuissance.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissance.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissance.page.tsx
> 🎨 Amélioration des conditions d'affichage et de wording de puissance

- packages/applications/legacy/src/views/components/UI/organisms/menuLegacy/DrealMenuLegacy.tsx
- packages/applications/ssr/src/app/laureats/changements/puissance/page.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
- packages/domain/utilisateur/src/role.valueType.ts
> 🎨 Ajout filtre autorité instructrice pour dreal

- packages/applications/ssr/src/components/molecules/ModalWithForm.tsx
- packages/applications/ssr/src/components/pages/actionnaire/demanderChangement/DemanderChangementActionnaire.form.tsx
- packages/applications/ssr/src/components/pages/actionnaire/enregistrerChangement/EnregistrerChangementActionnaire.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissance.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissanceFormErrors.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/détails/accorder/AccorderChangementPuissance.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/détails/rejeter/RejeterChangementPuissance.form.tsx
> 🎨 Suppression des validations pre submit

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getPuissance.ts
- packages/applications/legacy/src/views/components/UI/organisms/menuLegacy/DrealMenuLegacy.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeader.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoPuissance.tsx
- packages/applications/ssr/src/app/laureats/changements/puissance/page.tsx
- packages/applications/ssr/src/components/molecules/ModalWithForm.tsx
- packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
- packages/applications/ssr/src/components/pages/actionnaire/demanderChangement/DemanderChangementActionnaire.form.tsx
- packages/applications/ssr/src/components/pages/actionnaire/enregistrerChangement/EnregistrerChangementActionnaire.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissance.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissance.page.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissanceFormErrors.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/détails/accorder/AccorderChangementPuissance.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/détails/rejeter/RejeterChangementPuissance.form.tsx
- packages/domain/utilisateur/src/role.valueType.ts
> 🔀 Intégration des modifications de la release 3.48

- packages/applications/notifications/src/subscribers/lauréat/actionnaire/actionnaireModifié.notifications.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/changementActionnaireAccordé.notifications.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/changementActionnaireAnnulé.notifications.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/changementActionnaireDemandé.notifications.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/changementActionnaireEnregistré.notifications.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/changementActionnaireRejeté.notifications.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/constant.ts
- packages/applications/notifications/src/subscribers/lauréat/actionnaire/templateIds.ts
- packages/applications/notifications/src/subscribers/lauréat/puissance/changement/changementPuissanceAccordé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/puissance/changement/changementPuissanceAnnulé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/puissance/changement/changementPuissanceDemandé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/puissance/changement/changementPuissanceEnregistré.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/puissance/changement/changementPuissanceRejeté.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/puissance/constant.ts
- packages/applications/notifications/src/subscribers/lauréat/puissance/puissanceModifiée.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalAccordé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalAnnulé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalCorrigé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalDemandé.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/changementReprésentantLégalRejeté.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/constant.ts
- packages/applications/notifications/src/subscribers/lauréat/représentant-légal/représentantLégalModifié.notification.ts
- packages/specifications/src/projet/lauréat/actionnaire/enregistrerChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/puissance/changement/demanderChangementPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/changement/enregistrerChangementPuissance.feature
- packages/specifications/src/projet/lauréat/puissance/modifierPuissance.feature
> 🎨 ETQ PP, je dois être prévenu en cas de MAJ d'actionnaire, puissance ou RL

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getPuissance.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissance.form.tsx
- packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissanceFormErrors.tsx
=> https://linear.app/startup-potentiel/issue/POT-1419/quelques-modifications-de-wording
> 🎨 détails de wording puissance

- packages/applications/legacy/src/controllers/modificationRequest/délai/getDemanderDélaiPage.ts
- packages/applications/legacy/src/controllers/modificationRequest/fournisseur/getChangerFournisseurPage.ts
- packages/applications/legacy/src/controllers/modificationRequest/getDemandePage.ts
- packages/applications/legacy/src/controllers/modificationRequest/producteur/getChangerProducteurPage.ts
- packages/applications/legacy/src/views/pages/changerFournisseurPage/ChangerFournisseur.tsx
- packages/applications/legacy/src/views/pages/changerProducteurPage/ChangerProducteur.tsx
- packages/applications/legacy/src/views/pages/délai/DemanderDelaiPage.tsx
- packages/applications/legacy/src/views/pages/newModificationRequestPage/NewModificationRequest.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
Désactiver les liens plutot que de rediriger vers la page choix du CDC, pour harmoniser avec les demandes migrées, et faciliter le changement à venir de cette page
> ✨ Harmonisation du choix du CDC dans le legacy

- packages/applications/projectors/src/subscribers/lauréat/puissance/puissanceImportée.projector.ts
- packages/domain/lauréat/src/puissance/puissance.entity.ts
> ♻️ Supprimer champs inutile puissance

- packages/applications/bootstrap/src/setupRéseau.ts
- packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
- packages/domain/lauréat/src/raccordement/supprimer/supprimerDateMiseEnService.behavior.ts
Co-authored-by: Sylvain PONTOREAU <pontoreau.sylvain@gmail.com>
> 🔀 Intégration des modifications de la release 3.49

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/projectors/src/subscribers/lauréat/producteur/changementProducteurEnregistré.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/producteur/index.ts
- packages/domain/lauréat/src/garantiesFinancières/index.ts
- packages/domain/lauréat/src/producteur/changement/changementProducteur.entity.ts
- packages/domain/lauréat/src/producteur/changement/consulter/consulterChangementProducteur.query.ts
- packages/domain/lauréat/src/producteur/changement/enregistrerChangement/enregistrerChangementProducteur.behavior.ts
- packages/domain/lauréat/src/producteur/changement/enregistrerChangement/enregistrerChangementProducteur.command.ts
- packages/domain/lauréat/src/producteur/changement/enregistrerChangement/enregistrerChangementProducteur.usecase.ts
- packages/domain/lauréat/src/producteur/changement/enregistrerChangement/helper/renouvelerGarantiesFinancières.ts
- packages/domain/lauréat/src/producteur/changement/enregistrerChangement/helper/retirerTousLesAccèsAuxPorteursDuProjet.ts
- packages/domain/lauréat/src/producteur/changement/errors.ts
- packages/domain/lauréat/src/producteur/index.ts
- packages/domain/lauréat/src/producteur/producteur.aggregate.ts
- packages/domain/lauréat/src/producteur/producteur.register.ts
- packages/domain/lauréat/src/producteur/typeDocumentProducteur.valueType.ts
- packages/domain/utilisateur/src/index.ts
- packages/specifications/src/projet/lauréat/producteur/enregistrerChangementProducteur.feature
- packages/specifications/src/projet/lauréat/producteur/fixture/enregistrerChangementProducteur.fixture.ts
- packages/specifications/src/projet/lauréat/producteur/producteur.world.ts
- packages/specifications/src/projet/lauréat/producteur/stepDefinitions/producteur.then.ts
- packages/specifications/src/projet/lauréat/producteur/stepDefinitions/producteur.when.ts
- packages/specifications/src/projet/lauréat/puissance/changement/stepDefinitions/changementPuissance.then.ts
- raison : optionnel, PJ : obligatoires, cf carte dans linéar
- entity changement
- consulterChangement
- Pas fait : saga legacy
> ✨ ETP PP, je peux enregistrer un changement de producteur

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/legacy/src/sagas/producteur.saga.ts
- packages/applications/legacy/src/sagas/registerSagas.ts
- packages/applications/projectors/src/subscribers/lauréat/producteur/index.ts
- packages/applications/projectors/src/subscribers/lauréat/producteur/producteurModifié.projector.ts
- packages/domain/lauréat/src/producteur/changement/consulter/consulterChangementProducteur.query.ts
- packages/domain/lauréat/src/producteur/index.ts
- packages/domain/lauréat/src/producteur/modifier/modifierProducteur.behavior.ts
- packages/domain/lauréat/src/producteur/modifier/modifierProducteur.command.ts
- packages/domain/lauréat/src/producteur/modifier/modifierProducteur.usecase.ts
- packages/domain/lauréat/src/producteur/producteur.aggregate.ts
- packages/domain/lauréat/src/producteur/producteur.register.ts
- packages/specifications/src/projet/lauréat/producteur/fixture/enregistrerChangementProducteur.fixture.ts
- packages/specifications/src/projet/lauréat/producteur/fixture/modifierProducteur.fixture.ts
- packages/specifications/src/projet/lauréat/producteur/modifierProducteur.feature
- packages/specifications/src/projet/lauréat/producteur/producteur.world.ts
- packages/specifications/src/projet/lauréat/producteur/stepDefinitions/producteur.then.ts
- packages/specifications/src/projet/lauréat/producteur/stepDefinitions/producteur.when.ts
- CF les specs :) 
- Bonus : Création de la saga producteur legacy 
- A faire ensuite : notifications, call à ce usecase dans ModifierLauréat (l'attends l'implem du FF)
> ✨  Modifier producteur ETQ admin

- packages/applications/legacy/src/views/components/UI/organisms/ProjectList.tsx
- packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.form.tsx
- packages/applications/ssr/src/components/pages/candidature/détails/DétailsCandidature.page.tsx
- packages/applications/ssr/src/components/pages/candidature/lister/candidatureListLegendSymbols.ts
- packages/applications/ssr/src/components/pages/lauréat/modifier/ModifierLauréat.form.tsx
> 🎨 Modification nom candidat en nom producteur dans les formulaires

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getCandidature.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact.tsx
- packages/domain/utilisateur/src/role.valueType.ts
> 🐛 Correction bug affichage data projet au lieu de candidature

- packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeader.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/DemandeImpossibleInfoBox.tsx
> 🎨 InfoBox si demande impossible

- packages/applications/ssr/src/components/organisms/Timeline.tsx
> 🐛 Fix MUI Timeline

- packages/applications/bootstrap/src/setupLauréat.ts
- packages/applications/notifications/src/index.ts
- packages/applications/notifications/src/subscribers/lauréat/producteur/changementProducteurEnregistré.notification.ts
- packages/applications/notifications/src/subscribers/lauréat/producteur/constant.ts
- packages/applications/notifications/src/subscribers/lauréat/producteur/index.ts
- packages/applications/notifications/src/subscribers/lauréat/producteur/producteurModifié.notification.ts
- packages/specifications/src/notification/notification.world.ts
- packages/specifications/src/projet/lauréat/producteur/enregistrerChangementProducteur.feature
- packages/specifications/src/projet/lauréat/producteur/modifierProducteur.feature
Détails dans la carte linéar, 2 templates crées sur MJ
> ✨ Producteur notifications

- packages/applications/legacy/src/modules/modificationRequest/dtos/ModificationRequestListItemDTO.ts
> 🎨 Filter l'ancienne liste legacy

- packages/applications/projectors/src/subscribers/lauréat/producteur/producteurRebuildTrigerred.projector.ts
- packages/applications/ssr/src/components/pages/producteur/changement/lister/ChangementProducteurList.page.tsx
- packages/applications/ssr/src/utils/zod/candidature/candidatureNotifiée.schema.ts
> 🐛 rebuild producteur

- packages/applications/projectors/src/subscribers/lauréat/producteur/producteurRebuildTrigerred.projector.ts
- packages/applications/ssr/src/components/pages/producteur/changement/lister/ChangementProducteurList.page.tsx
- packages/applications/ssr/src/utils/zod/candidature/candidatureNotifiée.schema.ts
> 🔀 Intégration des modifications de la release 3.50

- packages/applications/ssr/src/components/molecules/CopyButton.tsx
- packages/applications/ssr/src/components/molecules/projet/ProjetBanner.template.tsx
- packages/applications/ssr/src/components/molecules/projet/ProjetBanner.tsx
- packages/applications/ssr/src/components/pages/utilisateur/lister/PorteurListItem.tsx
> 🧑‍💻 Amélioration DX : Accès rapide à l'identifiant projet depuis l'interface

- packages/domain/inmemory-referential/src/appelOffre/index.ts
- packages/domain/inmemory-referential/src/appelOffre/test.ts
This reverts commit 890f751db07aea33d1cba488655f12d7fd64c586.
> Ajout de l'appel d'offre Test

- packages/applications/ssr/src/components/pages/utilisateur/désactiver/désactiverUtilisateur.action.ts
- packages/applications/ssr/src/components/pages/utilisateur/lister/UtilisateurListItem.tsx
- packages/applications/ssr/src/components/pages/utilisateur/réactiver/réactiverUtilisateur.action.ts
le header fonctionne en local mais comportement différent une fois déployé
> 🐛 Redirection après dés-/ré-activation d'un utilisateur

- packages/applications/ssr/src/components/atoms/form/document/UploadDocument.tsx
- packages/applications/ssr/src/components/molecules/projet/ProjetBanner.template.tsx
- **💄 Improve projetBanner css**
- **💄 Fix scroll horizontal sur input file avec long nom de fichier**
> 💄 Fix problème CSS 

- packages/domain/lauréat/src/raccordement/supprimer/supprimerDateMiseEnService.behavior.ts
- packages/specifications/src/helpers/waitForSagasNotificationsAndProjectionsToFinish.ts
- packages/specifications/src/raccordement/dateDeMiseEnService/stepDefinitions/dateMiseEnService.when.ts
- packages/specifications/src/raccordement/dateDeMiseEnService/supprimerDateMiseEnService.feature
`waitForSagasNotificationsAndProjectionsToFinish` loggera désormais le message qui pose problème, qu'il soit en erreur ou non
> 🧑‍💻 Réduction des logs inutiles et amélioration de l'utilitaire `waitFor...ToFinish`

- packages/applications/bootstrap/src/setupProjet/setupLauréat/setupFournisseur.ts
- packages/applications/notifications/src/index.ts
- packages/applications/notifications/src/subscribers/lauréat/fournisseur/changementFournisseurEnregistré.notifications.ts
- packages/applications/notifications/src/subscribers/lauréat/fournisseur/constant.ts
- packages/applications/notifications/src/subscribers/lauréat/fournisseur/index.ts
- packages/applications/notifications/src/subscribers/lauréat/fournisseur/évaluationCarboneSimplifiéeModifiée.notifications.ts
- packages/applications/projectors/src/subscribers/lauréat/fournisseur/changementFournisseurEnregistré.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/fournisseur/index.ts
- packages/domain/projet/src/lauréat/fournisseur/changement/changementFournisseur.entity.ts
- packages/domain/projet/src/lauréat/fournisseur/changement/consulter/consulterChangementFournisseur.query.ts
- packages/domain/projet/src/lauréat/fournisseur/changement/enregistrerChangement/enregistrerChangement.command.ts
- packages/domain/projet/src/lauréat/fournisseur/changement/enregistrerChangement/enregistrerChangement.event.ts
- packages/domain/projet/src/lauréat/fournisseur/changement/enregistrerChangement/enregistrerChangement.option.ts
- packages/domain/projet/src/lauréat/fournisseur/changement/enregistrerChangement/enregistrerChangement.usecase.ts
- packages/domain/projet/src/lauréat/fournisseur/fournisseur.aggregate.ts
- packages/domain/projet/src/lauréat/fournisseur/fournisseur.error.ts
- packages/domain/projet/src/lauréat/fournisseur/fournisseur.event.ts
- packages/domain/projet/src/lauréat/fournisseur/fournisseur.register.ts
- packages/domain/projet/src/lauréat/fournisseur/index.ts
- packages/domain/projet/src/lauréat/fournisseur/typeDocumentFournisseur.valueType.ts
- packages/domain/projet/src/lauréat/fournisseur/typeFournisseur.valueType.ts
- packages/infrastructure/pg-projection-write/src/updateOneProjection.ts
- packages/specifications/src/projet/lauréat/fournisseur/enregistrerChangementFournisseur.feature
- packages/specifications/src/projet/lauréat/fournisseur/fixtures/enregistrerChangementFournisseur.fixture.ts
- packages/specifications/src/projet/lauréat/fournisseur/fournisseur.world.ts
- packages/specifications/src/projet/lauréat/fournisseur/modifierÉvaluationCarbone.feature
- packages/specifications/src/projet/lauréat/fournisseur/stepDefinitions/fournisseur.then.ts
- packages/specifications/src/projet/lauréat/fournisseur/stepDefinitions/fournisseur.when.ts
> ✨ Enregistrer changement de fournisseur ETQ porteur

- packages/applications/projectors/src/subscribers/lauréat/fournisseur/fournisseurRebuildTrigerred.projector.ts
- packages/applications/ssr/src/components/molecules/CopyButton.tsx
- packages/applications/ssr/src/components/molecules/projet/ProjetBanner.template.tsx
- packages/applications/ssr/src/components/pages/projet/éliminé/détails/DétailsProjetÉliminé.page.tsx
- packages/domain/utilisateur/src/role.valueType.ts
- meilleur design bouton copier (plus petit)
- quelques typos
- rebuild fournisseurs
> 🐛 Fix build fournisseur et divers front

- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/EtapesProjet.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/historique/page.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/achèvement/events/mapToAttestationConformitéTransmiseTimelineItemProps.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/garanties-financières/events/mainlevée/mapToDemandeMainlevéeGarantiesFinancièresAccordéeTimelineItemsProps.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/raccordement/events/gestionnaire-réseau/mapToGestionnaireRéseauAttribuéTimelineItemProps.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/raccordement/events/gestionnaire-réseau/mapToGestionnaireRéseauRaccordementModifiéTimelineItemProps.tsx
* 🐛 Ordonner correctement les éléments de l'historique avant leur mapping
* ✨ Affichage du courrier de main levée accordée
* 💄 Ne pas afficher le liens pour accéder au référentiel de gestionnaire de réseau
* 💄 Ajout du lien pour accéder à la preuve de transmission au cocontractant
* 💄 Meilleure identification du dernier élément des étapes du projet
>  🔀 Intégration des modifications de la release 3.53

- packages/specifications/src/projet/lauréat/actionnaire/demanderChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/enregistrerChangementActionnaire.feature
- packages/specifications/src/projet/lauréat/actionnaire/modifierActionnaire.feature
> ✅ Ajout des tests cahier des charges pour actionnaire

- package-lock.json
- packages/applications/legacy/package.json
- packages/applications/legacy/webpack.config.js
resolves https://github.com/MTES-MCT/potentiel/security/dependabot/148 and https://github.com/MTES-MCT/potentiel/security/dependabot/149
> ➖ Suppression de la dépendance à ``crypto-browserify``

- packages/applications/legacy/src/views/components/UI/molecules/Section.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact/InfoProducteur.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact/InfoReprésentantLégal.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact/index.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoActionnaire.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoPuissance.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/MaterielsEtTechnologies.tsx
- packages/applications/ssr/src/components/organisms/Timeline.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/mapToÉtapeInconnueOuIgnoréeTimelineItemProps.ts
- Alignement des espaces et des comportements dans les sections
- Etape inconnu de l'historique : alignement du comportement selon les env
> 🎨 Petites améliorations front

- packages/applications/ssr/src/app/laureats/[identifiant]/_helpers/getLauréat.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/modifier/page.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/ModifierLauréat.form.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/modifierLauréat.action.ts
- packages/applications/ssr/src/utils/candidature/candidatureNotifiée.schema.ts
- packages/domain/utilisateur/src/role.valueType.ts
> 🔀 Intégration des modifications de la release 3.53

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/checkLauréatNonAbandonné.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getAlertesRaccordement.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getFournisseur.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getRaccordement.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
- packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoRaccordement.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
- packages/applications/legacy/src/views/pages/projectDetailsPage/sections/MaterielsEtTechnologies.tsx
> ♻️ Refacto getFournisseur et getRaccordement

- packages/applications/legacy/src/views/components/UI/organisms/menuLegacy/CreMenuLegacy.tsx
- packages/domain/utilisateur/src/role.valueType.ts
> 🎨 Fix review fournisseur

- packages/applications/ssr/src/app/laureats/[identifiant]/_helpers/getLauréat.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/modifier/page.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/ModifierLauréat.form.tsx
- packages/applications/ssr/src/components/pages/lauréat/modifier/modifierLauréat.action.ts
- packages/applications/ssr/src/utils/candidature/candidatureNotifiée.schema.ts
> 🐛 Modifier fournisseur dans le porjet ETQ DGEC

- packages/applications/bootstrap/src/setupProjet/index.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/historique/page.tsx
- packages/applications/ssr/src/components/pages/lauréat/historique/HistoriqueLauréat.page.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/délai/events/mapToDélaiAccordéTimelineItemProps.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/délai/mapToDélaiTimelineItemProps.ts
- packages/applications/ssr/src/utils/historique/mapToProps/raccordement/events/dossier/dcr/mapToAccuséRéceptionDemandeComplèteRaccordementTransmisTimelineItemProps.tsx
- packages/domain/projet/src/lauréat/délai/délai.events.ts
- packages/domain/projet/src/lauréat/délai/index.ts
- packages/domain/projet/src/lauréat/délai/lister/listerHistoriqueDélaiProjet.query.ts
- packages/domain/projet/src/lauréat/historique/lister/listerHistoriqueProjet.query.ts
- packages/infrastructure/domain-adapters/src/délai/délai.adapter.ts
- packages/infrastructure/domain-adapters/src/délai/listerDélaiAccordé/_utils/index.ts
- packages/infrastructure/domain-adapters/src/délai/listerDélaiAccordé/_utils/récupérerÉvénementCovidDelayGranted.ts
- packages/infrastructure/domain-adapters/src/délai/listerDélaiAccordé/_utils/récupérerÉvénementDemandeDelaiSignaled.ts
- packages/infrastructure/domain-adapters/src/délai/listerDélaiAccordé/_utils/récupérerÉvénementDélaiAccordé.ts
- packages/infrastructure/domain-adapters/src/délai/listerDélaiAccordé/_utils/récupérerÉvénementLegacyModificationRawDataImported.ts
- packages/infrastructure/domain-adapters/src/délai/listerDélaiAccordé/_utils/récupérerÉvénementProjectCompletionDueDateSetDélaiCdc2022.ts
- packages/infrastructure/domain-adapters/src/délai/listerDélaiAccordé/listerDélaiAccordéProjet.adapter.ts
> 🔀 Intégration des modifications de la release 3.54

- packages/applications/ssr/src/components/atoms/form/Form.tsx
> 🎨 Ajout d'un UseEffect pour les erreurs de valdiations

- packages/applications/ssr/src/components/pages/candidature/détails/DétailsCandidature.page.tsx
- packages/applications/ssr/src/components/pages/fournisseur/changement/ListeFournisseurs.tsx
> 🎨 Affichage des détails de fournisseur dans la page candidature

- docs/contributing/GETTING_STARTED.md
- packages/domain/projet/src/lauréat/raccordement/raccordement.aggregate.ts
- packages/specifications/package.json
- packages/specifications/src/candidature/stepDefinitions/candidature.given.ts
- packages/specifications/src/potentiel.world.ts
- packages/specifications/src/projet/lauréat/abandon/stepDefinitions/abandon.when.ts
- packages/specifications/src/projet/lauréat/achèvement/attestationConformité/stepDefinitions/attestationConformité.when.ts
- packages/specifications/src/projet/lauréat/actionnaire/stepDefinitions/actionnaire.when.ts
- packages/specifications/src/projet/lauréat/producteur/stepDefinitions/producteur.when.ts
- packages/specifications/src/projet/lauréat/puissance/changement/stepDefinitions/changementPuissance.when.ts
- packages/specifications/src/projet/lauréat/puissance/stepDefinitions/puissance.when.ts
- packages/specifications/src/projet/éliminé/recours/stepDefinitions/recours.given.ts
- packages/specifications/src/projet/éliminé/recours/stepDefinitions/recours.then.ts
- packages/specifications/src/projet/éliminé/recours/stepDefinitions/recours.when.ts
- packages/specifications/src/projet/éliminé/stepDefinitions/éliminé.given.ts
- packages/specifications/src/raccordement/dateDeMiseEnService/transmettreDateMiseEnService.feature
- packages/specifications/src/raccordement/demandeComplèteDeRaccordement/stepDefinitions/demandeComplèteRaccordement.when.ts
- packages/specifications/src/raccordement/demandeComplèteDeRaccordement/transmettreDemandeComplèteDeRaccordement.feature
- packages/specifications/src/raccordement/propositionTechniqueEtFinancière/stepDefinitions/propositionTechniqueEtFinancière.when.ts
- packages/specifications/src/raccordement/propositionTechniqueEtFinancière/transmettrePropositionTechniqueEtFinancière.feature
- packages/specifications/src/tâche/stepDefinitions/tâche.then.ts
- packages/specifications/src/utilisateur/stepDefinitions/utilisateur.given.ts
- packages/specifications/src/utilisateur/stepDefinitions/utilisateur.then.ts
- packages/specifications/src/utilisateur/stepDefinitions/utilisateur.when.ts
> ✅ Tests pour raccordement

- docs/contributing/diagrams/aggregate-root.drawio.svg
> 📝 Schéma Aggregate Root

- packages/applications/bootstrap/src/setupProjet/setupLauréat/setupDélai.ts
- packages/applications/notifications/src/subscribers/lauréat/délai/constant.ts
- packages/applications/notifications/src/subscribers/lauréat/délai/demandeDélaiAnnuléeNotification.ts
- packages/applications/notifications/src/subscribers/lauréat/délai/index.ts
- packages/applications/projectors/src/subscribers/lauréat/délai/demandeDélaiAnnulée.projector.ts
- packages/applications/projectors/src/subscribers/lauréat/délai/registerDélaiProjectors.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/DétailsDemandeDélai.page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/annuler/AnnulerDemandeDélai.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/annuler/annulerDemandeDélai.action.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/page.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/délai/events/mapToDemandeDélaiAnnuléeTimelineItemProps.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/délai/mapToDélaiTimelineItemProps.ts
- packages/domain/projet/src/lauréat/délai/demande/annuler/annulerDemandeDélai.command.ts
- packages/domain/projet/src/lauréat/délai/demande/annuler/annulerDemandeDélai.event.ts
- packages/domain/projet/src/lauréat/délai/demande/annuler/annulerDemandeDélai.options.ts
- packages/domain/projet/src/lauréat/délai/demande/annuler/annulerDemandeDélai.usecase.ts
- packages/domain/projet/src/lauréat/délai/délai.aggregate.ts
- packages/domain/projet/src/lauréat/délai/délai.event.ts
- packages/domain/projet/src/lauréat/délai/délai.register.ts
- packages/domain/projet/src/lauréat/délai/errors.ts
- packages/domain/projet/src/lauréat/délai/index.ts
- packages/domain/utilisateur/src/role.valueType.ts
- packages/specifications/src/projet/lauréat/délai/annulerDemandeDélai.feature
- packages/specifications/src/projet/lauréat/délai/délai.world.ts
- packages/specifications/src/projet/lauréat/délai/fixtures/annulerDemandeDélai.fixture.ts
- packages/specifications/src/projet/lauréat/délai/stepDefinitions/délai.then.ts
- packages/specifications/src/projet/lauréat/délai/stepDefinitions/délai.when.ts
- **🧪 Annuler la demande de délai d'un projet lauréat failing test**
- **🚧 WIP**
> 🎨 Annuler la demande de délai

- packages/specifications/src/setup.ts
> 🧑‍💻 Ajout du nom du scenario dans les meta des logs des specs

- packages/applications/ssr/src/app/_helpers/récupérerLauréat.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/abandon/demander/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/demander/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/proposition-technique-et-financiere:modifier/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
- packages/domain/projet/src/lauréat/raccordement/raccordement.aggregate.ts
- packages/specifications/src/raccordement/demandeComplèteDeRaccordement/transmettreDemandeComplèteDeRaccordement.feature
- packages/specifications/src/raccordement/propositionTechniqueEtFinancière/modifierPropositionTechniqueEtFinancière.feature
[carte
](https://linear.app/startup-potentiel/issue/POT-1723/raccordement-ar-questions-metier#comment-bf503334)
> ✅ Ajout specs raccordement

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getDateAchèvementPrévisionnel.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/DétailsDemandeDélai.page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/accorder/AccorderDemandeDélai.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/modele-reponse/route.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/demander/DemanderDélai.action.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/demander/DemanderDélai.form.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/demander/DemanderDélai.page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/demander/page.tsx
- packages/applications/ssr/src/utils/historique/mapToProps/délai/mapToDélaiTimelineItemProps.ts
- packages/domain/projet/src/lauréat/achèvement/achèvement.aggregate.ts
- packages/domain/projet/src/lauréat/achèvement/consulter/consulterAchèvement.query.ts
- packages/domain/projet/src/lauréat/achèvement/dateAchèvementPrévisionnel.valueType.ts
- packages/domain/projet/src/lauréat/achèvement/index.ts
- packages/specifications/src/projet/lauréat/achèvement/stepDefinitions/achèvement.then.ts
- **🚧 Branchement dans l'app**
- **🚧 Ajout du value type DateAchevementPrévisionnel**
> ♻️ Ajout du value type DateAchevementPrévisionnel

- packages/applications/ssr/src/app/projets/[identifiant]/(détails)/DétailsProjetÉliminé.page.tsx
mise à jour du wording du lien
pour tester se mettre sur un projet éliminé (et qui n'a pas de recours accordé)
> 💄 (détail projet éliminé): wording lien avis rejet

- .github/workflows/pr.yml
- docs/contributing/GETTING_STARTED.md
- lancement app en local
- lancement tests
> 📝 (update doc): getting started

- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/DétailsDemandeDélai.page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/accorder/accorderDemandeDélai.action.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/corriger/CorrigerDemandeDélai.page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/passer-en-instruction/passerEnInstructionDemandeDélai.action.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/rejeter/rejeterDemandeDélai.action.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/demander/DemanderDélai.page.tsx
- packages/domain/appel-offre/src/appelOffre.entity.ts
- packages/domain/projet/src/lauréat/délai/autoritéCompétente.valueType.ts
- packages/domain/projet/src/lauréat/délai/demande/accorder/accorderDemandeDélai.command.ts
- packages/domain/projet/src/lauréat/délai/demande/accorder/accorderDemandeDélai.options.ts
- packages/domain/projet/src/lauréat/délai/demande/accorder/accorderDemandeDélai.usecase.ts
- packages/domain/projet/src/lauréat/délai/demande/passer-en-instruction/passerEnInstructionDemandeDélai.command.ts
- packages/domain/projet/src/lauréat/délai/demande/passer-en-instruction/passerEnInstructionDemandeDélai.option.ts
- packages/domain/projet/src/lauréat/délai/demande/passer-en-instruction/passerEnInstructionDemandeDélai.usecase.ts
- packages/domain/projet/src/lauréat/délai/demande/rejeter/rejeterDemandeDélai.command.ts
- packages/domain/projet/src/lauréat/délai/demande/rejeter/rejeterDemandeDélai.options.ts
- packages/domain/projet/src/lauréat/délai/demande/rejeter/rejeterDemandeDélai.usecase.ts
- packages/domain/projet/src/lauréat/délai/délai.aggregate.ts
- packages/domain/projet/src/lauréat/délai/index.ts
- packages/domain/projet/src/lauréat/délai/lister/listerDemandeDélai.query.ts
- packages/specifications/src/projet/lauréat/délai/accorderDemandeDélai.feature
- packages/specifications/src/projet/lauréat/délai/passerEnInstructionDemandeDélai.feature
- packages/specifications/src/projet/lauréat/délai/rejeterDemandeDélai.feature
- packages/specifications/src/projet/lauréat/délai/stepDefinitions/délai.when.ts
- vérification
- value type
- test
> ✨ Autorité instructice pour délai

- packages/applications/ssr/src/app/laureats/[identifiant]/delai/InfoBoxDemandeDélai.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/[date]/DétailsDemandeDélai.page.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/demander/DemanderDélai.form.tsx
- packages/applications/ssr/src/app/laureats/[identifiant]/delai/demander/DemanderDélai.page.tsx
> 🎨 Infobox demande délai

- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getActionnaire.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getFournisseur.ts
- packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
- packages/applications/legacy/src/views/components/UI/organisms/menuLegacy/AdminMenuLegacy.tsx
- packages/applications/legacy/src/views/components/UI/organisms/menuLegacy/DrealMenuLegacy.tsx
- packages/applications/routes/src/lauréat/abandon.routes.ts
- packages/applications/routes/src/lauréat/délai.routes.ts
- packages/applications/ssr/src/app/laureats/[identifiant]/fournisseur/changement/enregistrer/EnregistrerChangementFournisseur.form.tsx
- packages/applications/ssr/src/components/organisms/header/UserBasedRoleNavigation.tsx
- **🐛 Correction de la valeur actuelle de l'évaluation carbone (#3471)**
- **🐛  Fix fournisseur et actionnaire affichage pour aos (#3473)**
- **🎨 Préfiltrage des listes d'abandon + délai par role autorité instructrice (#3475)**
> 🔀 Intégration des modifications de la release 3.61

- packages/applications/ssr/src/app/utilisateurs/(liste)/UtilisateurListItem.tsx
- packages/applications/ssr/src/components/molecules/ListItem.tsx
correction bug activer/désactiver utilisateur, et affichage de la liste
> 🐛 Affichage liste Utilisateur + activer/désactiver

- packages/applications/ssr/src/app/elimine/[identifiant]/recours/(détails)/DétailsRecours.page.tsx
> 🔀 Intégration des modifications de la release 3.62
