src/config/emails.config.ts
src/infra/mail/mailjet.ts

The mailjet module tried reading `process.env` but failed to do so because it was loaded before `dotenv` could load up the `.env` file. The mailjet API keys were therefor empty which resulted in emails not being sent.
I refactored the mailjet module to accept the dependant keys as arguments. Env variables are injected at the config layer, which calls `dotenv`.

Fix mailjet api key injection from env variables

---

src/config/queries.config.ts
src/controllers/getNotificationListPage.ts
src/infra/sequelize/projections/notification/queries/getFailedNotificationDetails.integration.ts
src/infra/sequelize/projections/notification/queries/getFailedNotificationDetails.ts
src/infra/sequelize/projections/notification/queries/index.ts
src/modules/notification/dtos/FailedNotificationDTO.ts
src/modules/notification/dtos/index.ts
src/modules/notification/index.ts
src/modules/notification/queries/GetFailedNotificationDetails.ts
src/modules/notification/queries/index.ts
src/views/pages/notificationList.tsx

This page was disabled in a previous refactoring of the `Notification` module.

Enable the failed emails page

---

src/dataAccess/inMemory/appelsOffres/commonDataFields.ts
src/useCases/importProjects.spec.ts
src/useCases/importProjects.ts

I noticed that importProjects accepted csv files with familleId that did not exist for the appel d'offre. 
This adds a check that throws an error if such a line is in the file.

:star2:  importProjects should check familleId

---

src/dataAccess/db/project.ts

Avec la mise en place de postgres, le script qui fait la mise à jour de l'instance projet essayait de mettre à jour les champs uuid qui sont vides avec des chaines de caractère vides.
Ceci est un correctif qui assure que lors d'une mise à jour, on essaye simplement de mettre à jour les champs concernés et pas un delta calculé à la volée par sequelize.

:bug:  User should be able to upload GF and DCR

---

src/controllers/postSendCandidateNotifications.ts
src/views/pages/adminNotifyCandidates.tsx

After an admin notifies a period, they are redirected to the notification page and if the
page is not up to date (periode notification is an async process), they shouldn't be able to re-notify the
same period. In order to avoid this situation, hide the 'notify' button when there is a success message.

After period notification, hide notification button to avoid double-notify

---

src/controllers/authentication.ts

In the passport auth middleware, when `userResult` was `None`, the method called the `done` callback but continued to call `done` a second time because the `return` statement was missing.

Authentification should fail safe if db unavailable

---

src/controllers/postProjects.ts
src/views/pages/importCandidates.tsx

Previous version redirected to projects or notification pages after import was a
success, leading to unpredictable behaviour. It's simpler to stay on the import
page after success and let the user navigate afterwards.

Do not redirect after importing

---

src/controllers/project/getProjectPage.ts
src/infra/sequelize/projections/project/project.model.ts
src/infra/sequelize/projections/userProjects/userProjects.model.ts
src/infra/sequelize/queries/getProjectDataForProjectPage.integration.ts
src/infra/sequelize/queries/getProjectDataForProjectPage.ts
src/infra/sequelize/queries/index.ts
src/modules/project/dtos/ProjectDataForProjectPage.ts
src/modules/project/dtos/index.ts
src/modules/project/queries/GetProjectDataForProjectPage.ts
src/modules/project/utils/makeCertificateFilename.ts
src/routes.ts
src/views/components/actions/admin.ts
src/views/components/actions/porteurProjet.ts
src/views/components/projectActions.tsx
src/views/pages/projectDetails/components/NoteElement.tsx
src/views/pages/projectDetails/index.tsx
src/views/pages/projectDetails/sections/EditProjectData.tsx
src/views/pages/projectDetails/sections/ProjectFrise.tsx
src/views/pages/projectDetails/sections/ProjectHeader.tsx

Instead of sending the complete Project object to the view, create a DTO from a query packed with all necessary data.
This approach moves the logic from the old architecture to the new, enabling the addition of more data to this project page (PTF,...) without adding more code on the legacy side.

Refacto Project Page data query

---

src/dataAccess/db/project.ts

This table had varchar fields that would result in errors when the content is too long. It has been effectively replaced by event sourcing.
[Example](https://sentry.io/organizations/potentiel-prod/issues/2219194579/events/a2349525e4aa41f2b31184c57817ad11/)

:bug:  Remove creation of legacy ProjectEvents

---

src/core/utils/index.ts
src/core/utils/wrapInfra.ts
src/infra/file/S3FileStorageService.ts
src/infra/sequelize/eventStore/sequelizeEventStore.ts
src/infra/sequelize/queries/getFailedNotificationDetails.ts
src/infra/sequelize/queries/getFailedNotificationsForRetry.ts
src/infra/sequelize/queries/getFileProject.ts
src/infra/sequelize/queries/getInfoForModificationRequested.ts
src/infra/sequelize/queries/getModificationRequestDetails.ts
src/infra/sequelize/queries/getModificationRequestInfoForStatusNotification.ts
src/infra/sequelize/queries/getModificationRequestListForUser.ts
src/infra/sequelize/queries/getModificationRequestStatus.ts
src/infra/sequelize/queries/getProjectDataForProjectPage.ts
src/infra/sequelize/queries/getProjectIdForAdmissionKey.ts
src/infra/sequelize/queries/getStats.ts
src/infra/sequelize/queries/getUnnotifiedProjectsForPeriode.ts
src/infra/sequelize/repos/fileRepo.ts
src/infra/sequelize/repos/notificationRepo.ts
src/modules/authorization/useCases/cancelInvitationToProject.ts
src/modules/authorization/useCases/revokeRightsToProject.ts
src/modules/eventStore/BaseEventStore.ts
src/modules/file/loadFileForUser.ts
src/modules/notification/eventHandlers/handleProjectCertificateUpdatedOrRegenerated.ts
src/modules/project/useCases/removeStep.ts
src/modules/project/useCases/submitStep.ts

In order to transform a `Promise` coming from third-party libs, what we did was use `ResultAsync.fromPromise`.
Example:
```ts
const res = ResultAsync.fromPromise(project.findById(projectId), (e: Error) => { logger.error(e); return new InfraNotAvailableError(); })
```
This code was repetitive, verbose and sometimes we could forget the `logger.error(e)` part.
`wrapInfra` is a wrapper that does exactly the same thing, but factored in.
Updated example:
```ts
const res = wrapInfra(project.findById(projectId))
```

Add wrapInfra helper to make safer calls to infra layers (db, apis, ...)

---

src/dataAccess/db/project.ts
src/infra/sequelize/migrations/20210301132653-remove-full-text-search.js

PG's full text search (FTS) was not allowing us to do partial search (e.g : `ello wor` for `hello world`). We could only perform a search providing a radical (e.g : `hell` for `hello`). This commit replaces the use of the FTS to the iLike operator. It will allow us to
provide a better yet simpler search engine.
Closes #380

:star2:  Replace Postgres' full text search to iLike method

---

src/infra/sequelize/queries/getProjectDataForProjectPage.ts

This is necessary to enable the correctProjectData use-case which compares this date to the latest version

:bug:  Project page should have a valid updatedAt value

---

src/__tests__/fixtures/aggregates/makeFakeModificationRequest.ts
src/config/useCases.config.ts
src/controllers/modificationRequest/postReplyToModificationRequest.ts
src/infra/sequelize/projections/modificationRequest/updates/index.ts
src/infra/sequelize/projections/modificationRequest/updates/onModificationRequestStatusUpdated.integration.ts
src/infra/sequelize/projections/modificationRequest/updates/onModificationRequestStatusUpdated.ts
src/modules/modificationRequest/ModificationRequest.ts
src/modules/modificationRequest/ModificationRequest.updateStatus.spec.ts
src/modules/modificationRequest/events/ModificationRequestStatusUpdated.ts
src/modules/modificationRequest/events/index.ts
src/modules/modificationRequest/useCases/index.ts
src/modules/modificationRequest/useCases/updateModificationRequestStatus.spec.ts
src/modules/modificationRequest/useCases/updateModificationRequestStatus.ts
src/public/scripts.js
src/views/pages/modificationRequestDetails/index.tsx

L'idée est que l'administrateur peut passer le statut d'une demande à acceptée/rejetée sans déclencher le changement sur le projet ni l'envoi d'une nouvelle attestation au porteur de projet.
Pour cela, j'ai créé un nouvel événement `ModificationRequestStatusUpdated` qui est déclenché lors de l'appel à la nouvelle commande `ModificationRequest.updateStatus`. 
Cette commande est appelée par le use-case `updateModificationRequestStatus` (qui fait aussi la vérification du role de l'utilisateur et du numéro de version de la `ModificationRequest` - pour être sur que la demande n'a pas été mise à jour entre temps).
J'ai rajouté une case à cocher sur le formulaire de réponse à une demande pour que le controller `postReplyToModificationRequest` sache qu'il doit appeler …

388 je peux valider les demandes traitées en dehors du processus de validation des demandes

---

src/views/pages/projectDetails/sections/ProjectFrise.tsx

This caused the project page to crash when no dcr is due

:bug:  ProjectFrise should include case where project has no dcr 

---

src/controllers/auth/postSignup.ts
src/dataAccess/db/projectAdmissionKey.ts

The repo should not call the ProjectAdmissionKey constructor which could crash if the database has a
different shape.

:bug:  Sometimes getting a projectAdmissionKey crashed

---

src/controllers/admin/getAppelOffreCsv.ts
src/controllers/admin/getPeriodesCsv.ts
src/modules/appelOffre/useCases/importAppelOffreData.spec.ts
src/modules/appelOffre/useCases/importAppelOffreData.ts
src/modules/appelOffre/useCases/importPeriodeData.spec.ts
src/modules/appelOffre/useCases/importPeriodeData.ts

Plutôt que d'utiliser `appelOffreId` et `periodeId` comme en-têtes de colonne, conserver `Appel d'offres` et `Période` comme dans les fichiers circulants dans le drive.

473 entetes appel offre periode

---

src/server.ts

Pour avoir des liens de suivi  personnalisés sur mailjet, il faut que les utilisateurs puissent passer par un lien de type `http://lien.potentiel.beta.gouv.fr/lnk/...` or la politique HSTS actuelle sur le site force le passage à `https` immédiatement, ce qui casse ce genre de lien (pour lesquels il n'y a pas de certification ssl).
En rajoutant `includeSubdomains: false` sur `helmet`, la politique http=>https ne devrait pas s'appliquer sur le sous-domaine `lien.potentiel.beta.gouv.fr`.

:wrench:  Disable HSTS for subdomains to allow http redirections

---

RECIPES.md
src/config/projections.config.ts
src/helpers/isObject.ts
src/infra/sequelize/helpers/index.ts
src/infra/sequelize/helpers/projector.spec.ts
src/infra/sequelize/helpers/projector.ts
src/infra/sequelize/helpers/tests/describeProjector.ts
src/infra/sequelize/helpers/tests/index.ts
src/infra/sequelize/index.ts
src/infra/sequelize/models.ts
src/infra/sequelize/projections/appelOffre/appelOffre.model.ts
src/infra/sequelize/projections/appelOffre/periode.model.ts
src/infra/sequelize/projections/appelOffre/updates/onAppelOffreCreated.integration.ts
src/infra/sequelize/projections/appelOffre/updates/onAppelOffreCreated.ts
src/infra/sequelize/projections/appelOffre/updates/onAppelOffreRemoved.integration.ts
src/infra/sequelize/projections/appelOffre/updates/onAppelOffreRemoved.ts
src/infra/sequelize/projections/appelOffre/updates/onAppelOffreUpdated.integration.ts
src/infra/sequelize/projections/appelOffre/updates/onAppelOffreUpdated.ts

Cette PR est une proposition de refactoring des projections sequelize.
Actuellement, chaque mise à jour de projections est une méthode qui prend les `models` et qui utilise les méthodes de sequelize pour effectuer un changement.
J'ai remarqué que les projections sont en général des opérations simples de type Create/Update/Delete. Le code d'implémentation des projections est très répétitif et il en est de même pour le code des tests d'intégration qui vont avec.
Dans cette PR, je propose un projecteur générique qui mets en oeuvre les trois opérations typiques.
En utilisant ce projecteur générique, le code d'implémentation de chaque projection se limite aux éléments nécessaires pour chaque opération et devient très rapide à coder.
Chaque projection dispose de son projecteur (singleton) qui …

Refactor projections

---

src/views/pages/newModificationRequest.tsx

As the new cahier des charges is not active yet, demandes of type puissance|producteur|actionnaire|fournisseur should be disabled
Closes #504

504 Disable new modification request submit button and display msg

---

src/__tests__/fixtures/project.ts
src/controllers/garantiesFinancieres/getModeleMiseEnDemeure.ts
src/dataAccess/db/project.ts
src/entities/project.ts
src/infra/sequelize/queries/getModificationRequestDataForResponseTemplate.integration.ts
src/infra/sequelize/queries/getProjectDataForProjectPage.ts
src/modules/project/dtos/ProjectDataForProjectPage.ts
src/modules/project/utils/makeCertificateFilename.ts
src/routes.ts
src/useCases/relanceGarantiesFinancieres.spec.ts
src/useCases/relanceGarantiesFinancieres.ts
src/views/components/actions/admin.ts
src/views/components/projectList.tsx
src/views/pages/candidateCertificate.tsx
src/views/pages/projectDetails/sections/ProjectHeader.tsx

Before this PR, `routes.ts` (which is imported by multiple views), imports `makeProjectIdentifier` which relies `crypto` which itself only exists on `nodejs`.
In order to have views that can be run on the clientside, we need to have an isomorphic `routes.ts`.
To achieve this, I removed the dependency to `makeProjectIdentifier` and instead included the `potentielIdentifier` in the DTOs passed to the views.

Make sure routes.ts can be imported on frontend and backend

---

src/infra/sequelize/projections/project/project.model.ts
src/infra/sequelize/queries/project/getProjectDataForProjectPage.integration.ts

Previously displayed all invitation for the project owner's email, regardless of the fact that the invitations were for a specific project

Fix project page list of invitations

---

src/infra/sequelize/migrations/20211013142007-fix-completionDueDate-one-day-offset.js
src/modules/project/Project.notify.spec.ts
src/modules/project/Project.setNotificationDate.spec.ts
src/modules/project/Project.ts

Le bon calcul est date de notification + délai de réalisation - 1 jour.
Cette PR corrige cette règle + corrige les dates d'achèvement de tous les projets existants.

518 Calcul date d'achèvement

---

src/controllers/candidateNotification/getCandidateCertificatePreview.ts

`toProjectDataForCertificate` requires a `notifiedOn` date, which is obviously not available for unnotified projects for which we want to preview the certificate. 
Replace `project.notifiedOn` by `Date.now()` in this case.

644 Fix bug: impossible de voir un aperçu d'attestation

---

src/infra/sequelize/migrations/20211105173514-fix-user-created-email-case.js
src/modules/project/utils/parseProjectLine.spec.ts
src/modules/project/utils/parseProjectLine.ts

Lors de l'import d'un projet, l'adresse du candidat est gardée telle quelle (avec majuscules et minuscules), or quand nous créons le compte sur keycloak, nous passons l'email en minuscules.
Ainsi lors de la prochaine connexion, nous cherchons un utilisateur avec cet email et ne le trouvons pas (coté keycloak en minuscules et coté Potentiel avec majuscules). La connexion échoue.
Pour remédier à celà, `parseProjectLine` est corrigé pour passer l'email du candidat en minuscules dès l'entrée.
J'ai aussi rajouté un script de migration pour corriger l'état de la base de données.

646 Fix email case for imported candidates

---

src/controllers/candidateNotification/getCandidateCertificatePreview.ts
src/controllers/candidateNotification/getProjectCertificateFile.ts
src/controllers/project/getProjectFile.ts
src/controllers/project/getProjectsLaureatsCsv.ts

Certains utilisateurs n'arrivent pas à ouvrir leur attestation pdf dans le navigateur parce que ce n'est pas reconnu comme du pdf. 
Je pense que ça vient du header `Content-Type` qui n'est pas affecté pour les attestations.
J'en profite pour fixer le type pour toutes les requêtes qui envoient un fichier.

:bug: 652 Fix http response Content-Type for files

---

src/__tests__/fixtures/aggregates/makeFakeProject.ts
src/modules/project/Project.abandonLegacy.spec.ts
src/modules/project/Project.ts
src/modules/project/eventHandlers/handleLegacyModificationImported.spec.ts
src/modules/project/eventHandlers/handleLegacyModificationImported.ts

Je corrige un comportement erroné. Lorsqu'un projet a une demande historique de type abandon, cela doit se refléter sur son statut actuel (qui doit être "abandonné"). Actuellement, ce n'est pas le cas.
J'ai fait:
- Rajout d'une méthode `abandonLegacy` dans l'agrégat `Project` (il y a déjà un `abandon` mais j'ai préféré séparer les cas de figure).
- `handleLegacyModificationImported` appelle `abandonLegacy` sur le projet s'il y a une modification de type `abandon`.

:bug: 663 Lorsqu'un projet historique a été abandonné, son statut doit être "abandonné" lors de son import

---

src/__tests__/fixtures/aggregates/makeFakeProject.ts
src/controllers/project/postCorrectProjectData.ts
src/modules/project/Project.ts
src/modules/project/useCases/correctProjectData.spec.ts
src/modules/project/useCases/correctProjectData.ts

Il y avait une vérification coté controlleur sur `notificationDate` qui est un champ qui n'existe pas quand le projet est historique. Il était donc impossible de modifier un projet historique.
J'ai relaxé cette vérification dans `postCorrectProjectData` et j'ai renforcé également le comportement de `correctProjectData` pour s'assurer qu'on ne peut pas modifier la date de notification d'un projet historique (on ne peut pas dépendre uniquement du masquage du champ coté front).

:bug: 655 fix Impossible de modifier les données d'un projet historique

---

src/controllers/project/postCorrectProjectData.ts
src/modules/project/Project.correctData.spec.ts
src/modules/project/events/ProjectDataCorrected.ts
src/modules/project/useCases/correctProjectData.spec.ts
src/modules/project/useCases/correctProjectData.ts
src/views/pages/projectDetailsPage/sections/EditProjectData.tsx

On désactive temporairement les champs numéro CRE, Famille, appel d'offres et période du formulaire de correction des projets car de tels changements ont des impacts métier qui ne sont actuellement pas traités (conception à faire).

671 as admin i should not be able to modify project datas part of the potentiel identifier

---

src/modules/project/utils/parseProjectLine.spec.ts
src/modules/project/utils/parseProjectLine.ts

Cette PR rend possible l'import d'un fichier avec aucune valeur dans les colonnes evaluation carbone: l'erreur retournée en cas de valeur manquante est lisible.

:bug:  721 Fix import de l'historique éolien

---

package.json
tsconfig.migrations.json

This is a necessary step before being able to build/rebuild projections during migration.

:wrench:  706 Compile migrations scripts before executing them

---

src/infra/sequelize/queries/project/getProjectDataForProjectPage.integration.ts
src/infra/sequelize/queries/project/getProjectDataForProjectPage.ts

Il est possible d'accéder à la page d'un projet non-notifié (à condition d'avoir l'url).
Cette PR ajoute une vérification pour nous assurer que ça n'arrive pas.

:bug: 753 Do not return project page if not admin and not notified

---

src/infra/sequelize/migrations/20211216153606-catchup-on-project-claimed-project-certificateFileId.js
src/infra/sequelize/projections/project/updates/onProjectClaimed.integration.ts
src/infra/sequelize/projections/project/updates/onProjectClaimed.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/index.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectClaimed.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectClaimed.ts

Lorsque le porteur de projet réclame un projet, il upload une attestation.  Jusqu'ici cette attestation n'était pas accessible.
Cette PR mets à jour `project.certificateFileId` avec l'attestation uploadée par le porteur si celle-ci n'existe pas encore.
J'en profite pour créer une ligne sur la projection `projectEvents`.

🌟 594 update project certificate on project claimed

---

src/infra/sequelize/eventStore/loadAggregateEventsFromStore.ts

Lors du chargement des évènnements pour un aggregat depuis l'event store il faut préciser l'ordre dans lequel les récupérer. En effet postgre (et tout moteur de DB) ne retourne pas forcément dans l'ordre d'insertion.
Nous avions donc un bug sur plusieurs projet pour lesquels l'évènnement ProjectDataCorrected était traité avant ProojectImported et donc les données corrigées étaient à nouveau ecrasées avec les mauvaises. Ceci engendrait un bug lors de la génération d'attestation.

🐛 Fix the order of events when loading an aggregate from the event store

---

src/views/components/actions/admin.spec.ts
src/views/components/actions/dreal.spec.ts
src/views/components/actions/porteurProjet.spec.ts

suite à un bug dû a un refacto de la fonction porteurProjetActions on ajoute des tests pour éviter de futures régressions

:bug: 770 add tests on action per role

---

src/core/utils/Projection.ts
src/infra/sequelize/helpers/makeSequelizeProjector.spec.ts
src/infra/sequelize/helpers/makeSequelizeProjector.ts
src/infra/sequelize/migrations/20211130153044-add-project-events.js
src/infra/sequelize/migrations/20220104135530-add-eventPublishedAt-column-to-project-events-table.js
src/infra/sequelize/projectionsNext/projectEvents/projectEvent.model.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCertificateGenerated.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCertificateGenerated.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCertificateRegenerated.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCertificateRegenerated.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCertificateUpdated.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCertificateUpdated.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectClaimed.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectClaimed.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectGFSubmitted.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectImported.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectImported.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectNotified.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectNotified.ts
src/infra/sequelize/queries/frise/getProjectEvents.integration.ts
src/infra/sequelize/queries/frise/getProjectEvents.ts

- Le script src/infra/sequelize/migrations/20211130153044-add-project-events.js a été modifié car sinon on aurait une erreur lors de la migration depuis zéro (à cause du script éxécutant les handlers nécessitant maintenant la colonne eventPublishedAt)
- Dans le nouveau script on ajoute la colonne seulement si elle n'existe pas

775 Add eventPublishedAt column and fill with event occuredAt date in project_events projection

---

package.json

Ca ne posait aucun soucis en prod ou en CI parce que ça part de zéro mais en local, si.

:wrench:  migration starts by removing previously compiled migrations

---

src/core/utils/typeguards.ts
src/modules/frise/dtos/ProjectEventListDTO.ts
src/views/components/timeline/helpers/extractDCRItemProps.ts
src/views/components/timeline/helpers/extractDesignationItemProps.ts
src/views/components/timeline/helpers/extractGFItemProps.ts
src/views/components/timeline/helpers/extractImportItemProps.ts

Je trouvais redondant cette déclaration explicite de tous les `isProjectNotified`, etc...
Je me suis dit qu'on pouvait faire mieux avec typescript et voila un résultat que je trouve élégant (mais pas forcément évident à comprendre le type). Qu'en pensez-vous ?
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/304"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Utiliser un typeguard plus efficace pour discriminer les types de DTO

---

src/infra/fakeAuth/index.ts

Quand on relance un serveur de dev et qu'on a un cookie de fausse authentification avec un email qui n'est pas présent en base, le fakeAuth part en boucle: il essaye de rediriger vers /logout mais sans succès parce qu'il est intercepté par le middleware d'authentification.
Au lieu de rediriger vers /logout, maintenant ça retire tout de suite le cookie et redirige vers /login
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/307"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

:bug: 794 FakeAuth retire cookie erroné

---

src/infra/sequelize/migrations/20220128094158-add-UserRightsToProjectRevoked-in-history.js
src/infra/sequelize/migrations/20220128103139-add-UserRightsToProjectGranted-in-history.js
src/modules/authZ/eventHandlers/handleUserCreated.ts

J'insère dans l'historique une série d'événements `UserRightsToProjectRevoked` et `UserRightsToProjectGranted` pour correspondre avec les requêtes sql brutes que j'ai fait en live lors de la crise.
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

738 Nettoyer historique suite à erreur de notification Bat 13 famille 2

---

src/infra/sequelize/migrations/20220125162859-projects-adresseProjet-as-text.js
src/infra/sequelize/migrations/20220128093007-fix-projects-with-too-long-address.js

Il y a trois projets qui n'ont pas pu être importés dans l'historique parce que leur adresse dépassait 255 caractères de long (limite d'une colonne de type `VARCHAR` dans postgres). 
Les projecteurs pour les événements `ProjectImported` ont échoué à rajouter une ligne à la table `projects`. Du coup, les projecteurs suivants (`onProjectNotificationDateSet`, `onProjectGFDueDateSet`, etc.) ont également échoués, puisqu'ils essayaient de mettre à jour des lignes inexistantes dans la table `projects`. 
J'ai donc rajouté un script de migration qui rejoue les projections qui ont échoué.
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/333"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

729 Le champ adresseProjet doit accepter des chaines de plus de 255 caractères

---

.vscode/tasks.json

J'ai créé un petit script pour lancer les tests (unitaires ou integration suivant le fichier de test) en mode watch sur le fichier en cours.
C'est un raccourci pour éviter de devoir taper à la main `npm run test:watch --` puis le nom du test. 
Pour lancer, deux possibilités:
- Ouvrir la palette de commande, puis "Run Task" puis "Test - Run test on this file"
- Ajouter un raccourci clavier associé à cette tâche:
- Palette de commande,  "Open Keyboard Shortcuts (JSON)", puis rajouter 
```json
{
"key": "ctrl+alt+t",
"command": "workbench.action.tasks.runTask",
"args": "Test - Run test on this file",
"when": "editorTextFocus && resourceFilename =~ /.spec.ts$|.integration.ts$/"
}
```
Ça lancera les tests lorsqu'on a un fichier de test ouvert et qu'on fait CTRL+ALT+T.
<a …

DX: Add VSCode task to run test on current file

---

src/controllers/admin/index.ts
src/controllers/admin/specialBatiment13.ts
src/modules/project/Project.ts

Some projects could not submit GF/DCR/CA because they were reimported with a different status.
This add a special `/admin/special-batiment13` entry point which will be called once before being removed.
After this is merged and the entry point called, we can revert this commit.
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/340"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

:star2: 860 Add a special temporary entry point to fix bat13-2 projects

---

src/dataAccess/inMemory/appelsOffres/CRE4/innovation.ts
src/dataAccess/inMemory/appelsOffres/PPE2/ppe2.innovation.ts
src/entities/appelOffre.ts
src/infra/sequelize/queries/modificationRequest/getModificationRequestDataForResponseTemplate.ts
src/views/certificates/cre4.v0.tsx
src/views/certificates/cre4.v1.tsx
src/views/certificates/ppe2/components/Laureat.tsx
src/views/legacy-pages/candidateCertificate.tsx
src/views/pages/projectDetailsPage/ProjectDetails.tsx

Ceci permet d'éviter de filtrer les appels d'offres sur leur id pour savoir s'il sont de type innovation et donc d'oublier certains cas d'utilisations
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/345"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

:sparkles: 901 Ajout d'une propriété innovation pour identifier les appels d'offre

---

.github/workflows/ci.build.yml
.github/workflows/ci.integration-tests.yml
jest.unit.config.js
scripts/postInstall.ts
src/modules/modificationRequest/helpers/isModificationPuissanceAuto.ts
src/modules/project/Project.ts
src/views/certificates/helpers/getNoteThreshold.ts
tsconfig.json

Pour les parties utilisée côté front il faut faire des imports direct sur `@entities/periode` pour utiliser `isNotifiedPeriode`. Sinon tous le module `@entities` sera chargé inutilement par webpack
Le job de build a été modifié pour construire l'application en environnement de production et afin d'avoir une erreur si le build du front, par exemple, échoue
Certaines fonctions ou objets ne devraient pas être utilisés dans les composants visuels. Des données devraient être récupérées depuis les controleurs et passée en props aux pages. À prévoir dans une prochaine PR ou pendant la refonte UX
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/364"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

:recycle: Use direct import on @entities/periode to use isNotifiedPeriode

---

src/views/components/timeline/helpers/extractModificationRequestsItemProps.spec.ts
src/views/components/timeline/helpers/extractModificationRequestsItemProps.ts

Dans le cas où une demande de modification autre que délai, abandon ou recours est instruite alors on a une erreur lors de l'extraction des props car dans ces cas nous n'avons pas l'évennement `ModificationRequested`.
Cette erreur empêche pour les projets concerné l'affichage de la page projet.
Ici je filtre donc les groupes dans lesquels ne figure pas d'évennements de type `ModificationRequested` pour l'extract.
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/367"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

:bug: La page projet ne s'affiche plus après la validation d'un changement de puissance

---

src/config/useCases.config.ts
src/infra/sequelize/migrations/20220301152345-add-modificationRequest-puissanceAuMomentDuDepot-column.js
src/infra/sequelize/projections/modificationRequest/modificationRequest.model.ts
src/infra/sequelize/projections/modificationRequest/updates/onModificationReceived.ts
src/infra/sequelize/projections/modificationRequest/updates/onModificationRequested.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onModificationRequested.ts
src/infra/sequelize/queries/modificationRequest/getModificationRequestDetails.ts
src/infra/sequelize/queries/modificationRequest/getPuissanceProjet.integration.ts
src/infra/sequelize/queries/modificationRequest/getPuissanceProjet.ts
src/infra/sequelize/queries/modificationRequest/index.ts
src/modules/modificationRequest/dtos/ModificationRequestPageDTO.ts
src/modules/modificationRequest/events/ModificationReceived.ts
src/modules/modificationRequest/events/ModificationRequested.ts
src/modules/modificationRequest/useCases/requestFournisseursModification.spec.ts
src/modules/modificationRequest/useCases/requestProducteurModification.spec.ts
src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
src/modules/modificationRequest/useCases/requestPuissanceModification.ts
src/modules/notification/eventHandlers/handleModificationReceived.ts
src/views/pages/modificationRequestPage/components/DemandeDetails.tsx

Parfois la puissance a changé entre le moment où le PP a déposé sa demande et le moment où on ouvre cette demande.
Cette PR permet d'afficher la puissance au moment où la demande a été déposée.
Pour cela, j'ai du rajouter cette valeur dans le payload des événements `ModificationRequested` et `ModificationReceived` (non rétroactif) et aussi, une colonne `puissanceAuMomentDuDepot` sur la projection `modificationRequest`.
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/362"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

527 Afficher la puissance lors de la demande sur la page de la demande

---

src/controllers/project/getProjectListPage.ts
src/controllers/project/postInviteUserToProject.ts

Quand on est admin, après avoir invité quelqu'un via la page listing de project, on est redirigés vers la route qui correspond à la page listing de projets des porteurs de projets. Celle-ci ayant un `ensureRole` qui ne contient pas le role admin, cela fait une erreur "access denied".
Cette PR corrige ce comportement de deux manières:
- Rediriger vers la route admin après l'invitation
- Autoriser les admins à accéder au listing de projets via la route des porteurs de projet
- ça peut servir si on PP nous copie son URL pour qu'on teste 
- c'est branché sur le même contrôler donc aucun risque
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/391"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Bug: Admin reçoit "access denied" après avoir invité à des projets

---

src/controllers/modificationRequest/postRequestModification.ts
src/views/components/actions/porteurProjet.spec.ts
src/views/components/actions/porteurProjet.ts
src/views/pages/newModificationRequestPage/NewModificationRequest.tsx
src/views/pages/newModificationRequestPage/components/producteur/ChangementProducteur.tsx
src/views/pages/projectDetailsPage/components/ProjectActions.tsx

La règle est que le PP éolien ne peut pas changer de producteur avant la date d'achèvement. 
Or aujourd'hui nous n'avons pas cette date dans Potentiel.
Pour le moment le PP éolien ne doit donc jamais pouvoir changer de producteur sur Potentiel.
Ce que j'ai fait  pour le PP éolien : 
- Lien "changer de producteur" retiré de la liste des actions
- Formulaire de changement de producteur désactivé
- Controlleur posrRequestModification : erreur si changement de producteur
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/396"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

1006 as eolien pp i cannot change project producteur

---

src/views/legacy-pages/listProjects.tsx

Sans compteur, le lien pour télécharger les projets en CSV n'est pas top. Du coup je l'ai changer en bouton avec un intitulé aligné à droite

:lipstick: 1011 Masquer le compteur des projets pour les DREALs

---

README.md
docs/BUNDLE_FRONT.md
package.json
src/__tests__/matchers/toHavePublishedWithPayload.ts
src/controllers/modificationRequest/postRequestModification.ts
src/dataAccess/db/helpers/truncateTables.ts
src/dataAccess/inMemory/appelOffre.ts
src/entities/project.ts
src/helpers/buildMakeEntity.ts
src/infra/sequelize/__tests__/projections/describeProjector.ts
src/infra/sequelize/helpers/projector.ts
src/modules/appelOffre/AppelOffre.ts
src/modules/appelOffre/dtos/AppelOffreDTO.ts
src/modules/project/Project.ts
webpack.config.js

Dans l'optique de réduire la taille des bundles qui sont envoyés au front:
- `sideEffects: false` dans `package.json`
- placer `moment` dans le bundle commun
- utiliser les packages spécifiques de lodash plutot que le général
- ajouter un document pour expliquer comme faire une analyse
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/413"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

1016 Optimize js bundle

---

src/views/pages/newModificationRequestPage/components/delai/DemandeDelai.tsx

La date théorique de mise en service dans le formulaire de demande de délai était la date initiale de mise en service. Or on veut la date de mise en service à jour (avec les précédentes demandes de délai accordées), qui est la date "completionDueOn".

:bug: fix delay request form

---

src/controllers/modificationRequest/getModificationRequestListPage.ts
src/views/pages/modificationRequestListPage/ModificationRequestList.tsx

J'ai remarqué après avoir mergé le filtre DGEC sur la liste des demandes  que celui-ci n'était pas "gardé" lorsqu'on appliquait d'autres filtre. Cette PR corrgie le comportement en s'assurant d'avoir le filtre dans l'url à chaque fois
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/432"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

:bug: Correction du comportement du filtre DGEC

---

src/infra/sequelize/migrations/20220412094942-remove-legacy-modification-events-without-status.js

Les modifications historiques importée en 2021 sont toutes des modifications acceptées à l'exception de certains abandons pour lesquels le payload comporte une propriété "accepted". 
Le réimport qui va être fait de toutes ces modifications va aussi inclure en plus les modifications "Acceptées" et en "Accord de principe". Toutes les modifications historiques auront maintenant un statut obligatoire. 
Le problème est qu'avec les anciens imports, nous avons dans l'event store des événement concernant des modifications historiques avec un statut undefined, ce qui entraine un affichage erroné dans la frise. 
Dans cette PR, nous supprimons tous ces événement.
Ils seront ensuite réimportés avec un statut. 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/437"><img …

:bug: remove legacy modification events without status

---

src/config/logger.config.ts
src/modules/shared/errors/EmailAlreadyUsedError.ts
src/modules/users/User.ts

Régulièrement nous avons des erreurs à propos de compte déjà existant dans keycloak mais qui n'existe pas dans Potentiel. L'erreur logguée dans Sentry n'a cependant aucune info concernant le compte en question. 
Ici j'ai donc rajouté l'identifiant du compte en question afin de pouvoir investiguer sur ce problème.
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/458"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

:recycle: Ajout de details pour l'erreur sur la creation d'utilisateur

---

src/infra/sequelize/projections/appelOffre/updates/onPeriodeUpdated.ts
src/modules/appelOffre/AppelOffre.ts

Actuellement lorsque un AO est supprimé à l'issue d'un import, les donnèes projetées `AppelOffre` et `Periodes` sont supprimées pour cet AO. Cependant après réimport de ce même AO (et donc sa (re)création) les périodes ne sont pas (re)créées. 
Ceci est dû à l'aggrégat qui ne réinitialise pas ses périodes lors du traitement de l'evenement `AppelOffreRemoved`. Lors de la mise à jour des périodes des évenements `PeriodeUpdated` sont émis et une erreur survient dans le handler `onPeriodeUpdated` car ces pe'riodes avaient été supprimées précédemment.
PS : Les évenements `AppelOffreCreated` et `PeriodeUpdated` ayant la même date il est impossible d'en insérer entre de type `PeriodeCreated` pour corriger l'historique. D'où cette solution temporaire pour débloquer la situation et permettre la …

:bug: Correction de la gestion des periodes d'un AO apres suppression

---

src/infra/sequelize/queries/modificationRequest/getModificationRequestDataForResponseTemplate.integration.ts
src/infra/sequelize/queries/modificationRequest/getModificationRequestDataForResponseTemplate.ts

Erreur `Cannot read properties of null (reading 'toString')` dans la query `getModificationRequestDataForResponseTemplate`, dans la fonction locale `_makePreviousDelaiFromPreviousRequest.`
Dans la projection ModificationRequests nous avons 783 demandes de modification de type "délai" "acceptée" sans "delayInMonths" car ce sont des demandes legacy. 
Quand la valeur "delayInMonths" est nulle je la calcule à partir des dates données dans les `acceptanceParams`.

:bug:  calculer le délai en mois pour les demandes faites hors Potentiel

---

src/dataAccess/db/project.ts
src/infra/sequelize/projections/project/project.model.ts
src/infra/sequelize/projections/projectStep/updates/index.ts
src/infra/sequelize/projections/projectStep/updates/onProjectStepRemoved.integration.ts
src/infra/sequelize/projections/projectStep/updates/onProjectStepRemoved.ts
src/infra/sequelize/projections/projectStep/updates/onProjectStepSubmitted.integration.ts
src/infra/sequelize/projections/projectStep/updates/onProjectStepSubmitted.ts
src/infra/sequelize/queries/project/getProjectDataForProjectPage.integration.ts
src/infra/sequelize/queries/project/getProjectDataForProjectPage.ts
src/modules/project/dtos/ProjectDataForProjectPage.ts
src/views/pages/projectDetailsPage/ProjectDetails.stories.tsx

Le problème des projets en double/triple résulte de plusieurs entrées dans la projection `project_steps`. Celle-ci était utilisé afin d'afficher les étapes du projet avant que nous ne refassions totalement cette partie. Donc les éléments pour les dcr dans la projection ne sont plus du tout utilisés.
Comme nous avons encore des dépendances sur cette projection pour quelques queries on ne peut pas pas la supprimer directement. 
J'ai donc désactiver le rapatriement de cette info dans toutes les queries pour l'affichage de la liste et du détail des projets ainsi que des gestionnaire d'événement qui remplissait cette projection

🐛 Correction d'un problème d'affichage de certains projets en double/triple

---

.gitignore
src/dataAccess/inMemory/appelsOffres/CRE4/autoconsommationMetropole2016.ts
src/dataAccess/inMemory/appelsOffres/CRE4/autoconsommationZNI2017.ts
src/dataAccess/inMemory/appelsOffres/CRE4/zni2017.ts

Pour les noms des AO dans les filtres nous auront donc :
- CRE4 - Autoconsommation métropole
- CRE4 - Autoconsommation métropole 2016
- CRE4 - Autoconsommation ZNI
- CRE4 - Autoconsommation ZNI 2017
- CRE4 - ZNI 
- CRE4 - ZNI 2017
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

🐛 Renommage des titres courts de certains AOs pour les différencier

---

src/controllers/project/postSignalerDemandeDelai.ts

Formulaire de signalement d'une demande de délai, alors rediriger l'utilisateur vers ce même formulaire

🐛 Si erreur de validation, faire la bonne redirection

---

.eslintrc.json

Depuis la version 8 de eslint-conffig-prettier, toutes les extensions sont mergées en une :
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/558"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

:rotating_light: fusion des déclarations d'extensions eslint-prettier

---

src/infra/sequelize/migrations/20220823151651-Correction-ModificationRequests-responseFileId-manquants.ts

Avant [cette correction](https://github.com/MTES-MCT/potentiel/pull/578), dans le handler onDélaiRejeté, on n'enregistrait pas dans la projection modificationRequests l'id du fichier de réponse. Le porteur n'avait donc pas accès à ce fichier de réponse depuis la page de la demande de délai. 
Pour les événements "DélaiRejeté" déjà émis, j'ai créé un script de migration pour mettre modificationRequests à jour. 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/579"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

🐛 1065 - Ajout fichiers réponse manquants dans modificationRequests

---

.gitignore
.husky/pre-commit
.husky/prepare-commit-msg
package-lock.json
package.json
scripts/postInstall.ts

Le but de cette PR est d'automatiser l'installation des hooks husky lors de l'éxecution du `npm install`.
Les hooks sont les suivants :
- lint-staged
- hook gitmoji
L'installation et la configuration étant dans le script `prepare` il n'est plus nécessaire de stocker le repertoire `.husky` dans le dépôt. Ceci permet également de générer des scripts compatibles avec la machine (linux, macos) du developpeur
Accessoirement on copie désormais le fichier `.env` au `postInstall` pour ne plus avoir à le faire à la main lors du `clone` d'une copie propre du dépôt
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/588"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

🔨 Automatisation des hooks husky

---

src/infra/mail/mailjet.ts
src/modules/notification/Notification.ts
src/modules/notification/eventHandlers/modificationRequests/handleModificationReceived.spec.ts
src/modules/notification/eventHandlers/modificationRequests/handleModificationReceived.ts
src/views/components/UI/atoms/icons.ts
src/views/components/UI/molecules/AlertBox.tsx
src/views/components/UI/molecules/index.ts
src/views/pages/changerProducteurPage/ChangerProducteur.tsx
tailwind.config.js

En cas de changement de producteur, si le projet est soumis aux GF, dans le mail de confirmation de la modification on demande au PP d'envoyer de nouvelles GF. 
Dans cette PR on supprime la phrase concernant les GF du mail de confirmation de la modification. 
ET à la place du bouton "Consulter la demande" on a un bouton "Voir mes projets" (à ce stade le porteur à l'origine de la demande a perdu les droits sur le projet. 
On supprime aussi un warning du formulaire de changement de producteur (demande d'envoi de nouvelles GF sous un mois).
Création d'une AlertBox suivant le dsfr pour l'alerte qu'on garde dans le formulaire. 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/611"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

1105 Changement de producteur : supprimer demande GF de la confirmation PP

---

src/infra/sequelize/queries/modificationRequest/getModificationRequestDetails.ts
src/modules/modificationRequest/dtos/ModificationRequestPageDTO.ts
src/modules/modificationRequest/useCases/requestPuissanceModification.spec.ts
src/modules/modificationRequest/useCases/requestPuissanceModification.ts
src/views/pages/modificationRequestPage/ModificationRequest.stories.tsx
src/views/pages/modificationRequestPage/components/PuissanceForm.tsx
src/views/pages/newModificationRequestPage/components/puissance/ChangementPuissance.tsx

En attendant d'intégrer les seuils propres à chaque AO pour les CDC 2022
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/644"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

1146 - Suppression alerte puissance hors ratio pour CDC 2022

---

src/controllers/modificationRequest/fournisseur/postChangerFournisseur.ts

En cas de changement de fournisseur, l'évaluation carbone doit être optionnelle. 
yup.number() n'accepte pas de valeur nulle, alors on utilise transform pour retourner null ou la bonne valeur
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/648"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

🐛 (Contrôleur postChangerFournisseur): Passer l'éval carbone optionnelle

---

.github/workflows/deploy.prod.yml

Ici nous préparons la bascule de l'instance de production sur scalingo. Pour l'instant nous déployons en plus de CleverCloud l'instance sur Scalingo.
Une fois la bascule faite nous n'aurons plus qu'à supprimer la partie CleverCloud du workflow
PS: impossible de tester localement donc à monitorer une fois la PR mergée

👷 (1061): Ajout du déploiement sur l'instance scalingo de production

---

src/controllers/modificationRequest/postReplyToModificationRequest.ts
src/controllers/project/postCorrectProjectData.ts
src/modules/modificationRequest/errors/ProjetDéjàClasséError.ts
src/modules/modificationRequest/errors/index.ts
src/modules/modificationRequest/useCases/acceptModificationRequest.ts
src/modules/project/Project.grantClasse.spec.ts
src/modules/project/Project.ts
src/modules/project/useCases/correctProjectData.ts

Ne pas permettre à un admin d'accepter un recours pour un projet déjà "classé" retourner une erreur.
Retourner une erreur également si un admin tente de corriger un projet pour passer le statut en "classé" d'un projet déjà "classé". 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/719"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

1262  ETQ admin je ne peux pas accepter un recours si le projet est déjà "classé"

---

src/dataAccess/inMemory/appelsOffres/CRE4/eolien.ts
src/entities/periode.ts
src/infra/sequelize/queries/frise/getProjectEvents.ts

Les projets des périodes 1 et 3 de l'appel d'offres CRE4 Eolien ont une durée limite de GF de 57 mois si les projets ont postulé sans avoir d'autorisation environnementale. Dans les autres cas la durée est de 51 mois. 
On ajoute ici une propriété optionnelle dans les périodes pour cette particularité.
Et on met à jour la fonction qui permet de récupérer la durée de GF en mois passée à la page ProjectDetails. 
Pour appliquer cette règle il faudra réimporter le fichier des périodes concernées : cela permettra d'avoir l'info dans la propriété "details" de project. 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/713"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

1093 durées gf cre4 éolien p1 et p3

---

src/views/components/ProjectActions.tsx
src/views/components/ProjectList.tsx
src/views/components/actions/admin.ts

Problème : La prévisualisation de certains documents depuis la liste des projets retournait des pdfs en échec car la période du projet (situé dans l'AO) était legacy, donc sans certificat.
Solution : Cibler si le projet a une période legacy et empêcher de soumettre l'action de visualisation
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/744"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

🐛 (1295): Liste projets - empecher la de prévisualiser une attestation si projet a une période legacy

---

src/dataAccess/inMemory/appelsOffres/PPE2/ppe2.neutre.ts

Afin de permettre la notification des projets de l'AO ppe2 neutre nous avons commenté les familles utilisées uniquement pour les projets hydrauliques qui ne sont pas concernés par la notification actuelle.
L'intégration de  famille pour un type de technologie dans un AO pourra être conçue/implémentée plus tard
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/765"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

🗃️ (1300): Suppression (commentaire) des familles de l'AO ppe2 neutre

---

src/infra/sequelize/migrations/20221205144101-archivage-des-évènements-ignorés-dans-eventStores.ts

Les évènements suivants n'ont pas été supprimés lors d'une précédente PR :
- ProjectNewRulesOptedIn
- NouveauCahierDesChargesChoisi
- ProjectGFInvalidated
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/782"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

🗃️ (DB): Archivage des évènements ignorés

---

src/controllers/modificationRequest/postReplyToModificationRequest.ts
src/controllers/project/postChoisirCahierDesCharges.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onModificationRequestAccepted.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onModificationRequestAccepted.ts
src/modules/modificationRequest/ModificationRequest.ts
src/modules/modificationRequest/useCases/acceptModificationRequest.spec.ts
src/modules/modificationRequest/useCases/acceptModificationRequest.ts
src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx

Suite à la refacto faite sur la partie délai (cf  demandeModification/demandeDélai), j'ai viré le code legacy car plus utilisé aujourd'hui
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/809"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

🔥 (1345): supprimer 'delai' des params disponible pour modificationRequest

---

src/controllers/userAccount/postSignup.ts

On a des erreurs remontées sur sentry lorsque des utilisateurs tentent de créer un compte avec un email déjà utilisé. 
Dans cette PR on affiche le message d'erreur à l'utlisateur mais on ne log pas l'erreur. 
<a href="https://gitpod.io/#https://github.com/MTES-MCT/potentiel/pull/834"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

💄 (Erreur signup): si email déjà utilisé afficher erreur et ne pas logger

---

src/controllers/project/getProjectsLaureatsCsv.ts
src/views/pages/ListeProjetsPage.tsx

Depuis la page de la liste des projets, un lien permet d'exporter la liste des lauréats. Le contrôleur qui est appelé `getProjectsLaureatsCsv` utilise deux queries différentes selon l'état des projets de la période (notifiée ou non).: `listProjects` ou `listUnnotifiedProjects`. 
Suite à un changement du type de retour de listProjects dans une autre PR, nous avions une erreur venant du contrôleur. 
J'ai pris le parti de retirer ce lien de la liste des projet car fait doulon avec l'export de la liste.

🔥1477  (Liste Projets): Suppression export lauréats

---

src/controllers/modificationRequest/producteur/getChangerProducteurPage.ts
src/controllers/modificationRequest/producteur/postChangerProducteur.ts
src/controllers/modificationRequest/puissance/postDemanderChangementPuissance.ts
src/routes.ts
src/views/components/actions/porteurProjet.spec.ts
src/views/components/actions/porteurProjet.ts
src/views/pages/changerProducteurPage/ChangerProducteur.tsx
src/views/pages/projectDetailsPage/components/ProjectActions.tsx

- erreur de redirection : en cas d'erreur de validation pour un changement de producteur, la redirection pointait vers le formulaire de demande de délai
- harmonisation des pratiques de redirection : en cas d'erreur suite à une demande de changement de puissance, on redirigeait vers la page du projet, pour garder le même comportement que sur les autres demandes, j'ai simplement redirigé vers une page d'erreur

:bug: Corriger redirections demandes modification

---

src/views/components/Footer.tsx
src/views/components/Header.tsx
src/views/components/ProjectActions.tsx
src/views/components/UI/molecules/Alertes/Alerte.tsx
src/views/components/UI/molecules/BarreDeRecherche.tsx
src/views/components/UI/molecules/DownloadLink.tsx
src/views/components/UI/molecules/DownloadLinkButton.tsx
src/views/components/UI/molecules/DropdownMenu.tsx
src/views/components/UI/molecules/ExternalLink.tsx
src/views/components/UI/molecules/Section.tsx
src/views/components/UI/organisms/ProjectList.tsx
src/views/components/dropdowns/Dropdown.tsx
src/views/components/timeline/components/CurrentIcon.tsx
src/views/components/timeline/components/NextupIcon.tsx
src/views/components/timeline/components/PastIcon.tsx
src/views/components/timeline/components/WarningIcon.tsx
src/views/pages/ListeProjetsPage.tsx
src/views/pages/homePage/Home.tsx
src/views/pages/homePage/components/Benefices.tsx
src/views/pages/homePage/components/InscriptionConnexion.tsx
src/views/pages/homePage/components/PropositionDeValeur.tsx
src/views/pages/modificationRequestListPage/ModificationRequestList.tsx
src/views/pages/projectDetailsPage/components/ProjectActions.tsx

Ajouter un `title` aux icones qui apportent du sens au contenu, et masquer ceux qui ne sont que purement décoratifs.
Idem pour les images.

:lipstick: 1536 - Alternatives textuelles icones

---

src/controllers/modificationRequest/délai/getDemanderDélaiPage.ts
src/controllers/modificationRequest/délai/postDemanderDélai.ts
src/controllers/steps/postSubmitStep.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectDCRSubmitted.integration.ts
src/infra/sequelize/projectionsNext/raccordements/updates/onProjectDCRSubmitted.ts
src/modules/demandeModification/demandeDélai/demander/demanderDelai.ts
src/modules/demandeModification/demandeDélai/demander/demanderDélai.spec.ts
src/modules/project/Project.submitDemandeComplèteRaccordement.spec.ts
src/modules/project/Project.submitPropositionTechniqueFinancière.spec.ts
src/modules/project/Project.ts
src/modules/project/events/ProjectDCRSubmitted.ts
src/modules/project/useCases/submitDCR.spec.ts
src/modules/project/useCases/submitDCR.ts
src/views/components/timeline/components/DCRItem.tsx
src/views/pages/demanderDelaiPage/DemanderDelai.tsx

Suppression du champ "identifiant gestionnaire réseau" des formulaires de demande de délai et d'envoi de DCR.

:fire: (1173): retirer champs formulaire id gestionnaire non nécessaires

---

src/public/scripts.js
src/views/components/PageTemplate.tsx
src/views/components/ProjectActions.tsx
src/views/components/UI/molecules/DropdownMenu.tsx
src/views/components/UI/molecules/dropdowns/DropdownMenu.stories.tsx
src/views/components/UI/molecules/dropdowns/DropdownMenu.tsx
src/views/components/UI/molecules/dropdowns/DropdownSecondary.stories.tsx
src/views/components/UI/molecules/dropdowns/DropdownSecondary.tsx
src/views/components/UI/molecules/dropdowns/index.ts
src/views/components/UI/molecules/index.ts
src/views/components/UI/organisms/ProjectList.tsx

Dans cette PR j'ai retravaillé le composant `ProjectActions` pour remplacer le dropdown legacy par un nouveau composant `DropdownSecondary`. Son comportement est assez similaire à `DropdownMenu` mais il gère mieux le responsive et est plus adapté à ce genre de cas d'usage.
Au passage ça dégage la méthode legacy du script/public.js `addActionMenuHandlers()`

♻️  Utilisation d'un dropdown pour les actions possible par projet depuis la liste des projets

---

src/controllers/admin/inviterDgecValidateur/postInviterDgecValidateur.ts
src/controllers/admin/partnerUsers/postInvitePartnerUser.ts
src/controllers/userAccount/postSignup.ts

- ne pas logguer l'erreur dans sentry
- afficher le bon message d'erreur à l'utilisateur

 🚸 (1693): Creation de compte/invitation : notification si email déjà utilisé

---

package-lock.json
src/config/eventHandlers/notification.eventHandlers.ts
src/infra/sequelize/queries/project/index.ts
src/infra/sequelize/queries/project/récupérerDonnéesPorteursParProjet.integration.ts
src/infra/sequelize/queries/project/récupérerDonnéesPorteursParProjet.queryHandler.ts
src/modules/notification/eventHandlers/handleProjectCertificateUpdatedOrRegenerated.spec.ts
src/modules/notification/eventHandlers/handleProjectCertificateUpdatedOrRegenerated.ts
src/modules/project/queries/index.ts
src/modules/project/queries/récupérerDonnéesPorteursParProjet.ts
src/views/pages/AdminRegénérerPeriodeAttestationsPage.tsx

Bug remonté : porteurs  non notifiés suite à la re-génération des attestations de désignation d'une période. 
Constat : les emails de notification ne sont plus envoyés pour certains événements émis (trois handlers identifiés). 
Cela concerne les handlers qui utilisent le old project repo pour récupérer les données des utilisateurs, il ne retourne plus toutes les données des utilisateurs mais seulement leur id. 
Solution : ne plus utiliser ce code legacy. Dans un premier temps pour corriger rapidement le bug et permettre la regénération des attestation d'une période + envoi de l'email de notification, on introduit une nouvelle query qui est utlisée dans le handler concerné. 
Dans une seconde PR cette query sera utilisée pour les autres cas où les emails ne partent plus. 
Bonus : autre bug …

:bug: (1700): ETQ porteur je ne suis pas notifié en cas de regénération des attestations d'une période

---

src/config/eventHandlers/notification.eventHandlers.ts
src/config/eventHandlers/notifications/révocationsAccèsPorteurs.notifications.ts
src/dataAccess/db/project.ts
src/dataAccess/project.ts
src/modules/notification/eventHandlers/onProjectCompletionDueDateSet.ts
src/modules/notification/eventHandlers/révocationAccèsPorteurs/onToutAccèsAuProjetRevoqué.ts

Suite de la PR qui introduisait une query sequelize pour récupérer les users d'un projet pour les notifier en cas de regénération d'une attestation. 
Utilisation de la query pour récupérer les coordonnées des destinataires de notifications en cas de : 
- révocation de tous les droits sur un projet (changement de producteur)
- ajout du délai de 18 mois (CDC 2022) à un projet 
Suppression de l'ancien code qui n'est plus utilisé et ne fonctionne plus correctement (projectRepo.getUsers)

🐛 (1703): Notifications porteurs - fix queries

---

package-lock.json
src/infra/redis/helpers/fromRedisMessage.spec.ts
src/infra/redis/helpers/fromRedisMessage.ts

* 🔊 Logguer un warning si le type d'évènement n'est pas reconnu depuis Redis
* :arrow_up: Bump vm2 from 3.9.17 to 3.9.18
Bumps [vm2](https://github.com/patriksimek/vm2) from 3.9.17 to 3.9.18.
- [Release notes](https://github.com/patriksimek/vm2/releases)
- [Changelog](https://github.com/patriksimek/vm2/blob/master/CHANGELOG.md)
- [Commits](https://github.com/patriksimek/vm2/compare/3.9.17...3.9.18)
---
updated-dependencies:
- dependency-name: vm2 dependency-type: indirect ...
---------

🔀 Intégration des derniers changements de la version 3.2

---

src/controllers/raccordement/getAucunRaccordementAListerPage.ts
src/controllers/raccordement/getListeDossierRaccordementPage.ts
src/controllers/raccordement/index.ts
src/routes.ts
src/views/index.ts
src/views/pages/projectDetailsPage/ProjectDetails.tsx
src/views/pages/raccordement/AucunDossierAListerPage.tsx
src/views/pages/raccordement/components/Dossier.tsx
src/views/pages/raccordement/index.ts

La page raccordement était déjà accessible pour les rôles CRE et AO.
Cependant, si le projet n'a pas encore de dossier de raccordement dans Potentiel, alors on redirigeait vers le formulaire d'envoi de DCR. Les rôles AO et CRE n'ayant pas les droits de modification sur les données de raccordement, ces utilisateurs étaient redirigés vers une page d'erreur (accès non autorisé).
Dans cette PR j'ai ajouté une nouvelle page dédiée pour le cas d'un projet sans dossier de raccordement. La page affiche une liste vide.
J'ai pris le parti de ne pas utiliser la page existante pour éviter de passer toute une partie des props de la page optionnelles pour ce cas précis de projet sans dossier de raccordement, et éviter de complexifier le contrôleur getListeDossiersRaccordementPage.

:children_crossing: (1742): Accès aux données de raccordement pour les rôles CRE et AO

---

src/views/components/RequestList.tsx
src/views/components/UI/molecules/DownloadLink.tsx
src/views/components/UI/organisms/Footer.tsx
src/views/components/UI/organisms/Header.tsx
src/views/components/UI/organisms/ProjectList.tsx
src/views/components/timeline/components/ACItem.tsx
src/views/components/timeline/components/DemandeAbandonItem.tsx
src/views/components/timeline/components/DemandeAbandonSignaledItem.tsx
src/views/components/timeline/components/DemandeAnnulationAbandonItem.tsx
src/views/components/timeline/components/DemandeDelaiSignaledItem.tsx
src/views/components/timeline/components/DemandeDélaiItem.tsx
src/views/components/timeline/components/DemandeRecoursSignaledItem.tsx
src/views/components/timeline/components/LegacyModificationsItem.tsx
src/views/components/timeline/components/ModificationReceivedItem.tsx
src/views/components/timeline/components/ModificationRequestItem.tsx
src/views/pages/gestionaireReseau/components/Liste.tsx
src/views/pages/projectDetailsPage/sections/Contact.tsx
src/views/pages/projectDetailsPage/sections/EtapesProjet.tsx
src/views/pages/raccordement/listeDossiersRaccordement/ListeDossiersRaccordementPage.tsx
src/views/pages/raccordement/listeDossiersRaccordement/components/ÉtapeDemandeComplèteRaccordement.tsx
src/views/pages/raccordement/listeDossiersRaccordement/components/ÉtapeMiseEnService.tsx
src/views/pages/raccordement/listeDossiersRaccordement/components/ÉtapePropositionTechniqueEtFinancière.tsx

Objectif : les utilisateurs utilisant une technologie d'assistance peuvent vouloir afficher la liste des liens disponibles sur une page. Il faut donc que tous les liens aient un intitulé spécifique.Quand le titre du lien n'est pas assez spécifique, j'ajoute un attribue aria-label.

🚸 Intitulé des liens explicites

---

src/infra/sequelize/projectionsNext/garantiesFinancières/handlers/onProjectGFRemoved.integration.ts
src/infra/sequelize/projectionsNext/garantiesFinancières/handlers/onProjectGFRemoved.ts
src/infra/sequelize/projectionsNext/garantiesFinancières/handlers/onProjectGFWithdrawn.integration.ts
src/infra/sequelize/projectionsNext/garantiesFinancières/handlers/onProjectGFWithdrawn.ts

Lorsqu'on supprime des GF, il faut retirer la date de validation et l'identifiant du validateur de la projection garantiesFinancières.

🐛 (Suppression de GF): Définir la date de validation et l'id du validateur à null

---

src/infra/sequelize/queries/frise/getGarantiesFinancièresDTO.integration.ts
src/infra/sequelize/queries/frise/getGarantiesFinancièresDTO.ts
src/modules/frise/dtos/ProjectEventListDTO.ts
src/modules/project/Project.removeGarantiesFinancieres.spec.ts
src/modules/project/Project.ts
src/modules/project/Project.withdrawGarantiesFinancieres.spec.ts
src/modules/project/errors/SuppressionGFATraiterImpossibleError.ts
src/modules/project/errors/index.ts
src/views/components/timeline/components/GFItem.tsx

- autorisés à retirer des GF validées : cre, caisse des dépôts, admin, dreal, dgec-validateur
- autorisés à retirer des GF à traiter : porteur et caisse des dépôts
Application de ces règles + règles déplacé côté backend (query et méthodes agrégat projet)

Permissions sur la suppression de garanties financières selon leur statut 

---

src/infra/sequelize/queries/frise/getGarantiesFinancièresDTO.integration.ts
src/infra/sequelize/queries/frise/getGarantiesFinancièresDTO.ts
src/infra/sequelize/queries/frise/getProjectEvents.ts
src/modules/authN/Permission.ts
src/modules/frise/dtos/ProjectEventListDTO.ts
src/views/components/timeline/components/GFItem.tsx

Règle : 
Le porteur peut soumettre des GF pour les projets CRE4 (GF non soumises à la candidature), mais il ne peut pas enregistrer des GF  déjà validées.
Les autres rôles, dgec, dreal, cre, et caisse des dépôts peuvent enregistrer des GF déjà validées.

Permission enregistrer / soumettre des garanties financières

---

src/views/pages/AdminImporterCandidatsPage.tsx
src/views/pages/raccordement/miseEnService/ImporterDatesMiseEnServicePage.tsx

Il arrive que des admin tentent d'importer des fichiers excel à la place du csv attendu pour les fichiers : 
- dates de mise en service
- candidats pour notification
Pour guider les admin, on ajoute l'attribut "accept" avec la valeur .csv sur la balise input des deux formulaires.

🚸 (Import csv pour admin): ajout attribut accept sur la balise input

---

src/modules/project/useCases/importProjects.spec.ts
src/modules/project/useCases/importProjects.ts
src/views/pages/projectDetailsPage/sections/EditProjectData.tsx

Un admin souhaite importer dans Potentiel un projet dont la période à déjà été importée et notifiée dans Potentiel. 
Il s'agit d'un cas exceptionnel puisque tous les projets d'une période doivent être importés et notifiés en même temps. 
Deux projets concernés (deux AO différents). 
Le seul moyen d'importer des projets dans Potentiel sans avoir à déclencher une notification par un validateur est d'importer les projets avec une date de notification.
Or on ne peut pas importer des projets avec date de notification si l'appel d'offre n'est pas de type "legacy". 
Pour traiter le cas de ces deux projets on va : 
1. en tant que dev : supprimer la règle dans importProjects qui throw une erreur si le projet n'est pas legacy mais a une date de notification => PR actuelle 
2. en tant qu'admin : …

Permettre teporairement d'importer un projet dont la période est notifiée dans Potentiel

---

packages/domain/src/garantiesFinancières/actuelles/enregistrerGarantiesFinancièresComplètes.command.ts
packages/domain/src/garantiesFinancières/garantiesFinancières.error.ts
packages/specifications/src/garantiesFinancières/enregistrement/enregistrerGarantiesFinancières.feature
src/controllers/garantiesFinancieres/postDéposerGarantiesFinancières.ts
src/controllers/garantiesFinancieres/postEnregistrerGarantiesFinancières.ts
src/controllers/project/getProjectPage.ts
src/views/pages/projectDetailsPage/sections/GarantiesFinancières.tsx
src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx

Page projet : 
- contrôleur : pour déterminer si un dépôt de GF est attendu, on de base sur la query ConsulterSuiviDépôtGarantiesFinancières (et non plus sur l'AO qui ne fournissait pas des info suffisantes)
- Afficher les liens vers les formulaires de dépôt / enregistrement de GF seulement si le projet est classé
Contrôleur post enregistrer / déposer GF : 
- vérifier le statut du projet (le projet doit être classé)
Domain / métier : 
- un porteur ne peut pas enregistrer des GF si un dépôt est attendu

:sparkles: Mise à jour affichage formulaires GF + ajout règles métier

---

packages/domain-views/src/garantiesFinancières/dépôtGarantiesFinancières/lister/listerDépôtsGarantiesFinancières.query.ts
packages/domain-views/src/garantiesFinancières/garantiesFinancièresActuelles/garantiesFinancières.projector.ts
packages/domain/src/garantiesFinancières/dépôt/déposerGarantiesFinancières.command.ts
packages/domain/src/garantiesFinancières/dépôt/validerDépôtGarantiesFinancières.usecase.ts
packages/domain/src/permissions/garantiesFinancières.permissions.ts
packages/libraries/core-domain-views/src/readModel.ts
packages/libraries/pg-projections/src/listProjection.integration.ts
packages/libraries/pg-projections/src/listProjection.ts
packages/specifications/src/garantiesFinancières/dépôt/déposerGarantiesFinancières.feature
packages/specifications/src/garantiesFinancières/dépôt/stepDefinitions/dépôtGarantiesFinancières.given.ts
packages/specifications/src/garantiesFinancières/suiviDépôts/stepDefinitions/suiviDépôts.then.ts
src/controllers/garantiesFinancieres/getListeDépôtsGarantiesFinancièresÀValiderPage.ts
src/controllers/garantiesFinancieres/getModifierDépôtGarantiesFinancièresPage.ts
src/controllers/garantiesFinancieres/postModifierDépôtGarantiesFinancières.ts
src/controllers/garantiesFinancieres/postValiderDépôtGarantiesFinancières.ts
src/controllers/project/getProjectPage.ts
src/modules/authN/Permission.ts
src/routes.ts
src/views/pages/garantiesFinancières/DéposerGarantiesFinancièresPage.tsx
src/views/pages/garantiesFinancières/EnregistrerGarantiesFinancièresPage.tsx
src/views/pages/garantiesFinancières/ModifierDépôtGarantiesFinancièresPage.tsx
src/views/pages/garantiesFinancières/lister/ListeDépôtsGarantiesFinancièresÀValiderPage.tsx
src/views/pages/projectDetailsPage/sections/GarantiesFinancières.tsx

Suite à la migration des GF legacy, nous aurons des dépôts de GF sans type précisé. 
Afin de faciliter la validation de ces dépôts, on permet aux utilisateurs DREAL de compléter le type des dépôt depuis la liste des dépôts à valider.

:sparkles: Permission pour les DREAL et admin dgec de compléter un dépôt

---

src/config/useCases.config.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/demanderChangementDePuissance.spec.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/demanderChangementDePuissance.ts

Dans le use-case demanderChangementPuissance, on ne passait jamais l'AO du projet (n'existe pas dans l'agrégat passé) à la fonction exceedsRatiosChangementPuissance. On appliquait donc toujours les ratios par défaut, soit 0.9 et 1.1. 
Dans le use-case j'ai ajouté une dépendance au use-case qui permet de récupérer l'AO pour le passer à la fonction.

🐛 (changement puissance): récupérer l'AO pour vérifier les ratios d'auto-validation

---

packages/domain-views/src/projet/candidature/candidature.readmodel.ts
packages/libraries/infra-adapters/src/projet/récupérerCandidatureLegacy.adapter.ts
src/controllers/raccordement/getTransmettreDateMiseEnServicePage.ts
src/infra/mail/mailjet.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCompletionDueDateSet.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCompletionDueDateSet.ts
src/modules/notification/Notification.ts
src/modules/notification/eventHandlers/onProjectCompletionDueDateSet.spec.ts
src/modules/notification/eventHandlers/onProjectCompletionDueDateSet.ts
src/modules/project/Project.ts
src/modules/project/eventHandlers/onDateMiseEnServiceTransmise.spec.ts
src/modules/project/eventHandlers/onDateMiseEnServiceTransmise.ts
src/modules/project/events/ProjectCompletionDueDateSet.ts
src/views/pages/raccordement/miseEnService/TransmettreDateMiseEnServicePage.tsx

Si une nouvelle date de mise en service est saisie sur un projet qui a bénéficié du délai CDC 2022, et que cette date sort de l'intervalle d'application de ce délai, alors le projet perd les 18 mois les porteurs doivent être notifiés.

:sparkles: Nouvelle date de mise en service annulant le délai CDC 2022

---

src/config/eventHandlers/project.eventHandlers.ts
src/modules/project/eventHandlers/onCahierDesChargesChoisi.spec.ts
src/modules/project/eventHandlers/onCahierDesChargesChoisi.ts

Dans le contexte d'un projet qui a une/plusieurs date(s) de mise en service renseignée(s).
Lorsque le porteur choisit le CDC 2022, alors il devrait bénéficier automatiquement du délai de 18 mois si toutes les conditions sont remplies :
- il n'a pas déjà bénéficié du délai
- tous les dossiers de raccordement du projet ont une date de mise en service, et cette date est dans le bon intervalle

:sparkles: Appliquer règle ajout délai 18 mois au changement de CDC

---

src/config/eventHandlers/project.eventHandlers.ts
src/infra/mail/mailjet.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCompletionDueDateSet.integration.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/onProjectCompletionDueDateSet.ts
src/infra/sequelize/queries/project/getProjectDataForChoisirCDCPage.integration.ts
src/infra/sequelize/queries/project/getProjectDataForChoisirCDCPage.ts
src/modules/notification/Notification.ts
src/modules/notification/eventHandlers/onProjectCompletionDueDateSet.spec.ts
src/modules/notification/eventHandlers/onProjectCompletionDueDateSet.ts
src/modules/project/Project.ts
src/modules/project/eventHandlers/index.ts
src/modules/project/eventHandlers/onCahierDesChargesChoisi.spec.ts
src/modules/project/eventHandlers/onCahierDesChargesChoisi.ts
src/modules/project/eventHandlers/onDateMiseEnServiceTransmise.spec.ts
src/modules/project/eventHandlers/onDateMiseEnServiceTransmise.ts
src/modules/project/events/ProjectCompletionDueDateSet.ts
src/modules/project/queries/GetProjectDataForChoisirCDCPage.ts
src/views/components/UI/organisms/choisirCahierDesCharges/ChoisirCahierDesChargesFormulaire.tsx

**Cas 1 -  un changement de CDC annule le délai de 18 mois**
Dans le contexte d'un projet ayant déjà bénéficié du délai de 18 mois relatif au CDC 2022.
Si le porteur change de cahier de charges pour repasser sur le CDC 2021 ou le CDC initial, 
- le projet ne doit plus bénéficier du délai de 18 mois
- les porteurs + dreal de la région du projet doivent être notifiés par email
Dans cette PR nous avons : 
- une alerte sur la page du formulaire de changement de CDC
- un nouveau handler pour la mise à jour de la date d'achèvement du projet (legacy)
- mise à jour des notifications par mail
**Cas 2 - un changement de CDC vers le 2022 ajoute le délai de 18 mois**
Dans le contexte d'un projet qui a une/plusieurs date(s) de mise en service renseignée(s).
Lorsque le porteur choisit le CDC 2022, …

:sparkles: Impact délai CDC 2022 en cas de changement de CDC d'un projet

---

src/__tests__/fixtures/aggregates/makeFakeDemandeDélai.ts
src/infra/sequelize/migrations/20231031171802-add-columns-modification-requests-correction-delai.ts
src/infra/sequelize/migrations/20231102120000-add-columns-modification-requests-correction-delai.ts
src/infra/sequelize/projectionsNext/modificationRequest/modificationRequest.initializer.ts
src/infra/sequelize/projectionsNext/modificationRequest/modificationRequest.model.ts
src/infra/sequelize/projectionsNext/modificationRequest/updates/délai/onDélaiAccordéCorrigé.ts
src/infra/sequelize/projectionsNext/projectEvents/events/DemandeDélaiEvent.ts
src/infra/sequelize/projectionsNext/projectEvents/updates/délai/onDélaiAccordéCorrigé.ts
src/infra/sequelize/queries/frise/getProjectEvents.ts
src/infra/sequelize/queries/modificationRequest/getModificationRequestDetails.ts
src/modules/demandeModification/demandeDélai/DemandeDélai.ts
src/modules/demandeModification/demandeDélai/corrigerDélaiAccordé/NouvelleCorrectionDélaiAccordéImpossibleError.ts
src/modules/demandeModification/demandeDélai/corrigerDélaiAccordé/corrigerDélaiAccordé.spec.ts
src/modules/demandeModification/demandeDélai/corrigerDélaiAccordé/corrigerDélaiAccordé.ts
src/modules/frise/dtos/ProjectEventListDTO.ts
src/modules/modificationRequest/dtos/ModificationRequestPageDTO.ts
src/views/components/timeline/components/DemandeDélaiItem.tsx
src/views/pages/délai/CorrigerDelaiAccordePage.tsx
src/views/pages/délai/DetailsDemandeDelaiPage.tsx

Suite à la demo avec des DREAL/DEAL et nouvelle conception voici les modifications : 
- afficher la correction sur la page de la demande (délai accordé initialement et nouveau délai)
- afficher la correction sur la frise (seulement le nouveau délai)
- ne permettre qu'une seule correction
- informer l'utilisateur qu'il est libre de modifier le contenu du courrier de réponse pour l'adapter au cas précis du projet

:sparkles: Modifications sur la feature "corriger délai accordé"

---

packages/applications/ssr/src/app/laureat/abandon/[page]/page.tsx

Dans l'attente de filtres, on peut tester l'affichage en jouant avec les search params dans l'url.
Les tags ont un lien de redirection pour supprimer le search param correspondant.

:sparkles: Lister les abandons par statut et ajout d'un tag

---

packages/domain/lauréat/src/abandon/abandon.register.ts
packages/domain/lauréat/src/abandon/détecter/détecterAbandon.query.ts
packages/domain/lauréat/src/abandon/index.ts
src/controllers/project/getProjectPage.ts
src/views/pages/projectDetailsPage/ProjectDetails.tsx

Afficher l'abandon sur la page du projet + statut + lien vers le détail
Nécessite d'introduire une nouvelle query "détecterAbandon" pour détecter la présente d'un abandon, auquel cas on peut ensuite le consulter.

🚸 (Page projet): Afficher abandon

---

src/modules/project/useCases/importProjects.spec.ts
src/modules/project/useCases/importProjects.ts

Cette règle avait été supprimée temporairement afin d'importer un projet qui avait été par erreur omis dans un fichier de candidats de la CRE...

🎨 (import candidats): import avec date de notification ko pour les projets non-legacy

---

src/controllers/modificationRequest/puissance/getDemanderChangementDePuissancePage.ts
src/infra/sequelize/queries/modificationRequest/getModificationRequestDetails.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/demanderChangementDePuissance.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/helpers/exceedsPuissanceMaxDuVolumeReserve.spec.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/helpers/exceedsPuissanceMaxDuVolumeReserve.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/helpers/getVolumeReserve.ts
src/modules/modificationRequest/dtos/ModificationRequestPageDTO.ts
src/views/pages/demanderChangementPuissancePage/DemanderChangementPuissance.tsx
src/views/pages/demanderChangementPuissancePage/components/ChangementPuissance.tsx

Lorsqu'on vérifie si une demande de puissance dépasse le volume réservé, il faut vérifier que le projet est dans un volume réservé. Afin de vérifier cela nous ne vérifions que la puissance initiale du projet est dans le volume réservé. 
Dans cette PR on ajoute une vérification sur la note du projet : elle ne doit pas être inférieure à la note du dernier retenu du volume réservé.

✨ (Vérification volume réservé): prendre en compte la note du dernier retenu

---

src/views/helpers/ModificationRequestStatusTitle.ts
src/views/pages/modificationRequestListPage/ModificationRequestList.tsx

Le changement de wording n'est appliqué que sur les interfaces : page détail demande et filtres liste demandes.

🚸 (wording): information validée devient information enregistrée

---

packages/applications/ssr/src/components/molecules/abandon/DetailDemandeAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/DetailAbandonPage.tsx

Rubrique "preuve de recandidature" de la page projet à afficher seulement pour les abandons : 
- avec recandidature
- accordés

🐛 (page abandon): rubrique "preuve recandidature" seulement pour les projets concernés

---

packages/applications/ssr/src/app/laureats/[identifiant]/abandon/page.tsx
packages/applications/ssr/src/app/laureats/abandons/page.tsx
packages/applications/ssr/src/app/taches/page.tsx
packages/applications/ssr/src/components/molecules/projet/ProjetBanner.tsx
packages/applications/ssr/src/components/molecules/projet/StatutProjetBadge.tsx
packages/applications/ssr/src/components/molecules/tâche/TâcheListItem.tsx
packages/applications/ssr/src/components/organisms/ListFilters.tsx
packages/applications/ssr/src/components/organisms/ListHeader.tsx
packages/applications/ssr/src/components/pages/abandon/détails/DetailAbandonPage.tsx
packages/applications/ssr/src/components/pages/abandon/détails/DetailInstructionAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/détails/accorder/accorderAbandonAvecRecandidature.action.ts
packages/applications/ssr/src/components/pages/abandon/lister/AbandonListItem.tsx
packages/applications/ssr/src/components/pages/abandon/lister/AbandonListPage.tsx
packages/applications/ssr/src/components/pages/abandon/transmettrePreuveRecandidature/TransmettrePreuveRecandidatureForm.tsx
packages/applications/ssr/src/components/pages/abandon/transmettrePreuveRecandidature/TransmettrePreuveRecandidaturePage.tsx
packages/applications/ssr/src/components/pages/tâche/TâcheListPage.tsx
packages/applications/ssr/src/components/templates/DetailsAboutProjetPageTemplate.tsx
packages/applications/ssr/src/components/templates/ListPageTemplate.tsx
packages/applications/ssr/src/components/templates/ProjetPageTemplate.tsx
packages/infrastructure/document-builder/src/abandon/accordAbandonAvecRecandidature/buildDocument.ts
packages/infrastructure/document-builder/src/index.ts

Exporter les props des composants React afin de faciliter l'imbrication des composants (ne plus utiliser le type utilitaire Parameters)

:recycle: Exporter les props des composants React (vs utilisation type Parameters)

---

src/views/components/UI/molecules/dropdowns/DropdownMenuSecondaryButton.tsx
src/views/pages/projectDetailsPage/ProjectDetails.tsx
src/views/pages/projectDetailsPage/components/ProjectActions.stories.tsx
src/views/pages/projectDetailsPage/components/ProjectActions.tsx
src/views/pages/projectDetailsPage/components/ProjectHeader.tsx

Ajout de restrictions : 
- si le projet a déjà un abandon en cours : retirer "abandon" de la liste des modifications possibles
- si le CDC ne permet pas un abandon depuis potentiel : "abandon" non cliquable dans la liste + message info

🚸 Restriction affichage lien "demander abandon" depuis le projet

---

src/views/pages/demanderChangementPuissancePage/components/ChangementPuissance.tsx

Dans le cas d'une demande de changement de puissance supérieur à la puissance max du volume réservé, plusieurs alertes s'affichaient. 
L'objectif de cette PR est de n'afficher que l'alerte concernant ce cas précis.

🚸 (cas demande changement puissance hors puissance max vol réservé): afficher une seule alerte

---

src/infra/sequelize/migrations/20240125103501-add-col-project-designation-categorie.ts
src/infra/sequelize/migrations/20240126105000-apply-designationCategorie-to-projects.ts
src/infra/sequelize/projectionsNext/project/project.initializer.ts
src/infra/sequelize/projectionsNext/project/project.model.ts
src/infra/sequelize/queries/project/consulter/getProjectDataForProjectPage.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/demanderChangementDePuissance.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/helpers/exceedsPuissanceMaxDuVolumeReserve.spec.ts
src/modules/demandeModification/demandeChangementDePuissance/demander/helpers/exceedsPuissanceMaxDuVolumeReserve.ts
src/modules/project/Project.ts
src/modules/project/dtos/ProjectDataForCertificate.ts
src/modules/project/events/ProjectImported.ts
src/modules/project/events/ProjectRawDataImported.ts
src/modules/project/mappers/toProjectDataForCertificate.ts
src/modules/project/queries/GetProjectDataForProjectPage.ts
src/modules/project/types/désignationCatégorie.ts
src/modules/project/types/index.ts
src/modules/project/useCases/importProjects.spec.ts
src/modules/project/useCases/importProjects.ts
src/views/certificates/ppe2.v2/components/Laureat.tsx
src/views/pages/demanderChangementPuissancePage/DemanderChangementPuissance.tsx
src/views/pages/demanderChangementPuissancePage/components/ChangementPuissance.tsx
src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx

**Besoins métier :** 
- Tout porteur de projet dont la puissance du projet est inférieure ou égale à la puissance max du volume réservé doit savoir s'il est ou non dans le volume réservé. 
- Afficher l'appartenance à un volume réservé pour les prochaines désignations dans l'attestation de désignation.
**Tech**
- Ajout d'une colonne "désignationCatégorie" dans projects
- Script de migration pour mettre à jour les projets déjà importés

:children_crossing: Afficher info appartenance ou non au vol réservé si puissance inférieure au max du volume

---

src/infra/sequelize/migrations/20240207133000-add-col-project-historique-abandon.ts
src/infra/sequelize/projectionsNext/project/project.initializer.ts
src/infra/sequelize/projectionsNext/project/project.model.ts
src/modules/project/events/ProjectImported.ts
src/modules/project/events/ProjectRawDataImported.ts
src/modules/project/types/historiqueAbandon.ts
src/modules/project/types/index.ts
src/modules/project/useCases/importProjects.spec.ts
src/modules/project/utils/parseProjectLine.spec.ts
src/modules/project/utils/parseProjectLine.ts

Besoin : avec le fichier de candidats, on importe une nouvelle donnée correspondant à l'historique d'abandon du projet. 
Dans un premier temps cette information sera utile à des fins de statistiques. Elle sera utile plus tard pour le traitement des demandes d'abandon (reste à concevoir). 
Dans cette PR, on se contente de valider la donnée importée (nouvelle colonne obligatoire), et de l'enregistrer dans le projet.

:sparkles: Import historique abandon projet

---

packages/applications/bootstrap/src/setupLauréat.ts
packages/domain/lauréat/src/garantiesFinancières/enregistrer/enregistrerGarantiesFinancières.behavior.ts
packages/domain/lauréat/src/garantiesFinancières/enregistrer/enregistrerGarantiesFinancières.command.ts
packages/domain/lauréat/src/garantiesFinancières/enregistrer/enregistrerGarantiesFinancières.usecase.ts
packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.aggregate.ts
packages/domain/lauréat/src/garantiesFinancières/garantiesFinancières.register.ts
packages/domain/lauréat/src/garantiesFinancières/index.ts
packages/domain/utilisateur/src/role.valueType.ts
packages/infrastructure/notifications/src/lauréat/garantiesFinancières.notification.ts
packages/infrastructure/projectors/src/lauréat/garantiesFinancières.projector.ts
packages/specifications/src/projet/lauréat/garantiesFinancières/enregistrerGarantiesFinancières.feature
packages/specifications/src/projet/lauréat/garantiesFinancières/stepDefinitions/garantiesFinancières.given.ts
packages/specifications/src/projet/lauréat/garantiesFinancières/stepDefinitions/garantiesFinancières.when.ts

Pour rattraper l'historique, certains utilisateurs peuvent enregistrer les GF d'un projet. Elles sont alors automatiquement considérées comme validées.

:recycle: (migration domaine GF) : Enregistrer GF actuelles (validées)

---

packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordement.page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordement.stories.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/DétailsRaccordement.page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/DossierRaccordement.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/FormatFichierInvalide.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/Separateur.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/Étape.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapeDemandeComplèteRaccordement.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapeMiseEnService.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapePropositionTechniqueEtFinancière.tsx

J'ai repris la logique de GF et j'ai découpé en plusieurs composants contextuel (propre au détail de la page raccordement) pour faciliter la navigation dans le fichier.
Au passage j'ai extrait dans une page `AucunDossierDeRaccordement.page` pour le cas où il n'y a pas de raccordement pour le projet, c'est le page.tsx qui décide ou non d'afficher cette page, c'est pas au "front" de faire ce choix.
à merger après #1677

♻️ Découper en composants le détail de la page raccordement d'un projet

---

packages/applications/legacy/src/controllers/project/getProjectPage.ts
packages/applications/legacy/src/modules/project/queries/GetProjectDataForProjectPage.ts
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx

Afficher les GF en attente sur la page d'un projet : on va chercher les GF en attente dans la projection dédiée (et non plus par déduction).

✨ (Page projet): afficher GF en attente

---

packages/applications/legacy/src/views/components/UI/atoms/Button.tsx
packages/applications/legacy/src/views/components/UI/molecules/Accordeon.tsx
packages/applications/legacy/src/views/components/UI/molecules/Buttons/PrimaryButton.tsx
packages/applications/legacy/src/views/components/UI/molecules/dropdowns/DropdownMenuSecondaryButton.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx

- button in legacy were sometimes in Arial (button are known for badly handling app font)
- unknown tailwind classes spotted

🎨 Fix font for button and unknown tailwind class

---

packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/depot:modifier/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/dépôt/modifier/ModifierDépôtEnCoursGarantiesFinancières.page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/dépôt/modifier/ModifierDépôtEnCoursGarantiesFinancières.stories.tsx
packages/applications/ssr/src/components/pages/garanties-financières/dépôt/modifier/supprimer/SupprimerDépôtEnCoursGarantiesFinancières.tsx
packages/applications/ssr/src/components/pages/garanties-financières/dépôt/modifier/valider/validerDépôtEnCoursGarantiesFinancières.tsx
packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.stories.tsx
packages/applications/ssr/src/components/pages/garanties-financières/détails/components/GarantiesFinancièresDépôtEnCours.tsx

Les boutons "supprimer" et "valider" étaient accessibles depuis la page de modification du dépôt de GF. On les déplace sur la page du détail du dépôt.

:children_crossing: Déplacer les boutons d'action sur le détails du dépôt de GF 

---

packages/applications/ssr/src/components/pages/garanties-financières/FormulaireGarantiesFinancières.tsx

Juste un changement de route ciblée quand on cancel le formulaire de saisi d'une GF. On redirige sur le détail des GFs du projet, non pas le projet en lui même
Se rendre sur les formulaire pour : 
- soumettre des GFs
- modifer un dépot
- Enregistrer des gfs

💬 Le formulaire de saisie des gf doit avoir un bouton cancel qui retourne sur le détail des gfs du  projet

---

packages/applications/projectors/package.json
packages/applications/projectors/src/infrastructure/createProjection.ts
packages/applications/projectors/src/infrastructure/updateProjection.ts
packages/applications/projectors/src/infrastructure/upsertProjection.ts
packages/applications/projectors/tsconfig.json
packages/infrastructure/pg-projections/package.json
packages/infrastructure/pg-projections/src/countProjection.test.ts
packages/infrastructure/pg-projections/src/getOrderClause.ts
packages/infrastructure/pg-projections/src/getWhereClause.ts
packages/infrastructure/pg-projections/src/listProjection.ts
packages/infrastructure/pg-projections/src/listProjectionV2.test.ts
packages/infrastructure/pg-projections/src/listProjectionV2.ts
packages/infrastructure/pg-projections/tsconfig.json

Dans la partie projection les imports sur le package @potentiel-libraries/flat n'est pas le bon.
Il suffit de tester avec n'importe qu'elle partie de l'application qui a été migrée sur Next

🐛 Fix bad import on Potentiel Flat package

---

packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx
packages/applications/ssr/src/app/garanties-financieres/projets-en-attente/page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/en-attente/lister/ListerProjetsAvecGarantiesFinancièresEnAttente.page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/en-attente/lister/ListerProjetsAvecGarantiesFinancièresEnAttente.stories.tsx
packages/applications/ssr/src/components/pages/garanties-financières/getGarantiesFinancièresMotifLabel.ts
packages/domain/lauréat/src/garantiesFinancières/enAttente/lister/listerProjetsAvecGarantiesFinancièresEnAttente.query.ts
packages/domain/lauréat/src/garantiesFinancières/motifDemandeGarantiesFinancières.valueType.ts
packages/specifications/src/projet/lauréat/garantiesFinancières/enregistrerGarantiesFinancières.feature
packages/specifications/src/projet/lauréat/garantiesFinancières/soumettreGarantiesFinancières.feature
packages/specifications/src/projet/lauréat/garantiesFinancières/supprimerGarantiesFinancièresÀTraiter.feature
packages/specifications/src/projet/lauréat/garantiesFinancières/validerGarantiesFinancièresÀTraiter.feature

Ajout d'un filtre supplémentaire pour retrouver des projets en attente de transmission de gf par motif d'attente.
En local j'avais une base avec l'event stream des gfs déjà à jour.
Pour pouvoir bien tester le filtre par motif il faut : 
- test avec changement de producteur
- test avec recours accordé
- on peut pas tester gf arrivées à échéance pour le moment

🎨 Pouvoir filtrer la liste des projets en attente de gf par motif

---

packages/domain/core/src/domainError.ts

NotFoundError ne devrait plus être utilisé par les queries, il y a Option.none de dispo en retour pour ça. Du coup je propose de renommer NotFoundError en AggregateNotFound erreur pour ne plus créer de confusion et lever cette erreur uniquement si l'aggregate n'a pas pu être chargé.
La nouvelle erreur pourra être utilisée lors des prochains refacto lié à Option en retour de query.
N/A

🗑️ Mark NotFoundError as deprecated

---

docs/contributing/CODING_CONVENTION.md

Ajout clarification sur l'utilisation des Options et des Erreurs lors qu'un entité ou agrégat n'est pas récupérer.
N/A

📝 Update Coding convention

---

packages/domain/common/src/valueTypes/dateTime.valueType.ts
packages/domain/lauréat/src/garantiesFinancières/générerModèleMiseEnDemeure/générerModèleMiseEnDemeure.query.ts

Cette PR ajoute une méthode `ajouterNombreDeMois` au value type existant DateTime afin d'éviter de faire des `new Date().setMonth(...)` dans les query 
Génération du modèle de mise en demeure pour les gfs, en étant connecté en tant que DREAL sur la liste des projets en attente de GF en vérifiant que le calcul de la date est bien fonctionnel (utilisation d'un outil en ligne pour vérifier, par exemple : https://icalendrier.fr/outils/ajouter-retirer-date?startDate=2019-10-07&addOrSub=add&days=0&weeks=0&months=36&years=0)

✨ Ajout d'une méthode `ajouterNombreDeMois` au value type DateTime

---

packages/applications/ssr/src/app/garanties-financieres/depots-en-cours/page.tsx
packages/applications/ssr/src/app/garanties-financieres/projets-en-attente/page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/dépôt/lister/ListerDépôtsEnCoursGarantiesFinancières.page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/en-attente/lister/ListerProjetsAvecGarantiesFinancièresEnAttente.page.tsx
packages/domain/lauréat/src/garantiesFinancières/dépôt/lister/listerDépôtsEnCoursGarantiesFinancières.query.ts
packages/domain/lauréat/src/garantiesFinancières/enAttente/lister/listerProjetsAvecGarantiesFinancièresEnAttente.query.ts

Afin de faciliter l'instruction des GF, les DREALs et DGEC souhaitent pouvoir filtrer les listes de GF en attente et à traiter par cycle d'AO (PPE2 ou CRE4). 
ETQ admin, ou dreal, il est possible de filtrer les listes de GF en attente et à traiter par cycle d'AO.

:sparkles: [GF] Filtrer listes par cycle d'AO (PPE2 ou CRE4)

---

packages/applications/bootstrap/src/setupLauréat.ts
packages/applications/notifications/src/index.ts
packages/applications/notifications/src/subscribers/lauréat/achèvement.notification.ts
packages/applications/notifications/src/subscribers/lauréat/attestationConformité.notification.ts

⚠️  À merger après #1768 
Les utilisateurs "dreal" rattachés à la région d'un projet pour lequel une attestation de conformité a été déposée sont notifiées par mail. 
Pas possible à tester en local, on peut juste vérifier que le log est bien trigger (`Emailing mode set to logging-only so no email waq sent`)

✨ [Achèvement PR 2]: notification dreal en cas d'attestation de conformité transmise

---

packages/infrastructure/document-builder/src/abandon/accordAbandonAvecRecandidature/Header.tsx
packages/infrastructure/document-builder/src/abandon/modèlesRéponseDocx/buildDocument.ts
packages/infrastructure/document-builder/src/formatIdentifiantProjetForDocument.ts
packages/infrastructure/document-builder/src/garantiesFinancières/modèleMiseEnDemeureDocx/buildDocument.ts

Sur les modèles de réponse aux demandes d'abandon, demandes d'abandon avec recandidature et de mise en demeure (GF), le "**code Potentiel**" affiché est formaté avec des "#" en séparateur. Il faut les remplacer par des "-", et placer un "P" devant la période, et un "F" devant la famille afin de faciliter la compréhension des informations. 
ex : 
- `PPE2 - Eolien#1##24` devient `PPE2 - Eolien-P1-24`
- `CRE4 - Sol#1#2#25 `devient `CRE4 - Sol-P1-F2-25`
- en tant que PP, demander un abandon avec recandidature > en tant que dgec-validateur choisir l'option "accorder" > vérifier le courrier de réponse généré : le "code potentiel"  des références du courrier devrait être correctement formaté
- en tant que PP, demander un abandon …

:children_crossing: Formatage id potentiel courriers réponse

---

packages/domain/utilisateur/src/role.valueType.ts

Le rôle caisse des dépôts ne peut pas télécharger les docs d'achèvement d'un projet. 
Ajout de la permission manquante. 
Document téléchargeables depuis la frise d'un projet (il faut au préalable que le porteur les ait envoyés : projet > actions).

:bug: Fix permission achevement

---

packages/applications/bootstrap/src/setupLauréat.ts
packages/applications/notifications/src/subscribers/lauréat/garantiesFinancières.notification.ts

Lorsqu'un porteur dépose une demande de main-levée de GF dans Potentiel, nous devons envoyer un email de notification aux utilisateurs Dreal de la région du projet.

✨ (Main-levée demandée): notifier les DREALs

---

packages/applications/legacy/src/views/pages/modificationRequestPage/ModificationRequest.tsx
packages/applications/legacy/src/views/pages/modificationRequestPage/components/PuissanceALaHausseInfoBox.tsx
packages/applications/legacy/src/views/pages/modificationRequestPage/components/index.ts

Ajout d'une info box si certaines conditions sont respectées
Legacy => j'ai fait au plus simple
https://linear.app/startup-potentiel/issue/POT-285/info-box-a-destination-des-dreal-dans-le-cas-dun-changement-de
Test visuel des cas

👔 Afficher info box a dreal en cas de changement de puissance non prévue

---

packages/applications/ssr/src/app/laureats/[identifiant]/achevement/attestation-conformite:transmettre/page.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/FormulaireAttestationConformité.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.action.ts
packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.page.tsx

En tant que PP, je peux faire une demande automatique de mainlevée de mes GF quand je transmets mon attestation de conformité
Sur le formulaire de transmission de mon attestation de conformité + preuve de transmission au contractant, j'ai une case à cocher qui indique "Je souhaite demander une mainlevée de mes garanties financières"
Si la transmission est complète et donc validée, l'action demande de mainlevée se déclenche automatiquement 
- si le projet a des garanties financières actuelles validées 
- Il ne dispose pas de demande de renouvellement ou de modifications de garanties financières en cours. 
- Sinon, un message d'erreur s'affiche "Vous devez avoir des garanties financières actuelles validées sur Potentiel pour pouvoir faire cette demande de mainlevée"

✨ Demander la main levée lors de la transmission de l'attestation de conformité

---

packages/applications/ssr/src/components/pages/abandon/détails/accorder/AccorderAbandonSansRecandidature.tsx
packages/applications/ssr/src/components/pages/abandon/détails/demanderConfirmation/DemanderConfirmationAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/détails/rejeter/RejeterAbandon.tsx
packages/applications/ssr/src/components/pages/garanties-financières/en-attente/lister/ListItemProjetAvecGarantiesFinancièresEnAttente.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapeDemandeComplèteRaccordement.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapePropositionTechniqueEtFinancière.tsx

Cette PR ajoute le fait d'ouvrir les liens de téléchargement dans un nouvel onglet  pour enregistrer automatiquement sur le disque de l'utilisateur qui fait l'action + éviter de perdre la page courante (avant on avait une preview du fichier qui remplacait la page Potentiel) 
En parcourant les fichiers aux endroits où il y a des modifications

🚸 Composant Download - ouvrir les liens de téléchargement dans un nouvel onglet 

---

packages/applications/ssr/src/components/atoms/form/InputDownload.tsx
packages/applications/ssr/src/components/pages/abandon/détails/EtapesAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/détails/accorder/AccorderAbandonSansRecandidature.tsx
packages/applications/ssr/src/components/pages/abandon/détails/demanderConfirmation/DemanderConfirmationAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/détails/rejeter/RejeterAbandon.tsx
packages/applications/ssr/src/components/pages/garanties-financières/détails/components/GarantiesFinancièresActuelles.tsx
packages/applications/ssr/src/components/pages/garanties-financières/détails/components/GarantiesFinancièresDépôtEnCours.tsx
packages/applications/ssr/src/components/pages/garanties-financières/en-attente/lister/ListItemProjetAvecGarantiesFinancièresEnAttente.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapeDemandeComplèteRaccordement.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ÉtapePropositionTechniqueEtFinancière.tsx

Pour éviter que le navigateur fasse la preview d'un fichier alors qu'on lui a spécifié qu'on voulait uniquement le télécharger (attr download natif au composant dsfr) on ajout target _blank. Afin de garantir l'accessibilité on ajoute un aria-label pour que les lecteurs d'écrans puissent afficher l'information que le téléchargement se fera dans un nouvel onglet

🎨 Utilisation du target blank pour bypasser la preview navigateur

---

packages/applications/projectors/src/subscribers/lauréat/abandon.projector.ts
packages/domain/lauréat/src/abandon/abandon.entity.ts
packages/domain/lauréat/src/abandon/consulter/consulterAbandon.query.ts
packages/domain/lauréat/src/abandon/lister/listerAbandon.query.ts

Fait partie de ce ticket : https://linear.app/startup-potentiel/issue/POT-191/switch-domain-abandon-sur-listprojection-v2.
Nécessite un rebuild d'abandon
Il faut lancer les specs pour valider le bon fonctionnement du domain en lecture

♻️ Mise à plat des données d'Abandon

---

packages/applications/bootstrap/src/setupLauréat.ts
packages/applications/notifications/src/subscribers/lauréat/garantiesFinancières.notification.ts

Lors de la modification du statut de sa demande de GF (en instruction, validé, ou refusé),
Le PP est notifié par email 
Objet : Le statut de la demande de main-levée des garanties financière a été modifié [Nom du projet]
Contenu : Le statut de votre demande de main-levée des garanties financières pour le projet X a été modifié + Vous pouvez consulter cette demande sur Potentiel :  lien vers la page de la garantie financière

✨ Notifier les porteurs quand la demande de mainlevée change de statut

---

packages/applications/projectors/src/subscribers/lauréat/abandon.projector.ts
packages/applications/projectors/src/subscribers/lauréat/achèvement.projector.ts
packages/applications/projectors/src/subscribers/lauréat/garantiesFinancières.projector.ts
packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
packages/applications/projectors/src/subscribers/tâche/tâche.projector.ts
packages/applications/projectors/src/subscribers/éliminé/recours.projector.ts

Ce cas était traité comme une erreur mais n'en est pas une. Certains identifiants de projet sont valides sans pour autant permettre de récupérer les données de candidature associé. C'est le cas notament lorsqu'un projet a changé d'appel d'offre.

🐛 Remplacer les log d'erreurs dans les projecteurs par des warning lorsqu'un projet n'exsite pas

---

packages/domain/réseau/src/raccordement/référenceDossierRaccordement.valueType.ts
packages/specifications/src/gestionnaireRéseau/validerRéférenceDossierRaccordement.feature
packages/specifications/src/raccordement/modifierRéférenceDemandeComplèteDeRaccordement.feature

Fix de la validation des références qui bloquent la majeur partie des dossiers de raccordement en production
Rajout dans les specs de plan de scénario avec des valeurs non fonctionnelles actuellement en prod

🚑️ Fix validation qui bloque le chargement de certaines référence actuel

---

packages/specifications/package.json
packages/specifications/src/potentiel.world.ts
packages/specifications/src/setup.ts

Fix du script `spec:select` qui n'ignorait pas les `@NotImplemented` 
Ajout d'une vérification pour tous les tests que l'erreur n'est pas set, sauf s'il s'agit du test `devrait être informé que`

🧑‍💻 Vérifier l'absence d'erreur dans tous les "Alors", hors test d'erreur

---

packages/applications/ssr/src/app/laureats/[identifiant]/achevement/attestation-conformite:transmettre/page.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/FormulaireAttestationConformité.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/modifier/modifierAttestationConformité.page.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.page.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.stories.tsx

Auparavant pour savoir si on affichait la case à cocher pour demander une mainlevée on utilisait des `Option.isSome` or la projection des garanties financières n'utilise pas les `Option` mais encore des propriétés `optional` et donc le check n'était pas ok.
Maintenant pour la page de transmission d'attestation de conformité on affiche un warning s'il n'est pas possible de demander une mainlevée.
- Correction de bug
Un peu compliqué mais il faut des garanties financières actuelles incomplètes non validées et aller sur la page de transmission d'attestation de conformité/achèvement. Normalement dans ce cas nous devrions avoir la case à cocher pour demander la mainlevée  `disabled` avec un warning

🐛 Ne pas permettre de demander la mainlevée si pas de d'attestation de garanties financières

---

packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/modifierDemandeComplèteRaccordement.action.ts
packages/domain/réseau/src/raccordement/modifier/modifierRéférenceDossierRaccordement.command.ts
packages/domain/réseau/src/raccordement/modifier/modifierRéférenceDossierRaccordement.usecase.ts
packages/specifications/src/raccordement/modifierRéférenceDemandeComplèteDeRaccordement.feature
packages/specifications/src/raccordement/stepDefinitions/raccordement.when.ts

Le gestionnaire réseau est passé en input du use case, pour moi il s'agit d'une erreur:
- l'info est déjà disponible sur le raccordement
- c'est source d'erreur car on ne vérifie pas que le gestionnaire est le même que le raccordement

♻️ Retirer le paramètre inutile pour ModifierRéférenceDossierRaccordement

---

packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/gestionnaire:modifier/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
packages/applications/ssr/src/components/pages/réseau/gestionnaire/modifier/ModifierGestionnaireRéseau.page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/DétailsRaccordement.page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/DétailsRaccordement.stories.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/DossierRaccordement.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/components/ModifierGestionnaireRéseauDuRaccordement.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.page.tsx
packages/domain/réseau/src/gestionnaire/consulter/consulterGestionnaireRéseau.query.ts
packages/domain/réseau/src/gestionnaire/gestionnaireRéseau.aggregate.ts
packages/domain/réseau/src/raccordement/attribuer/attribuerGestionnaireRéseau.behavior.ts
packages/domain/réseau/src/raccordement/attribuer/attribuerGestionnaireRéseau.command.ts
packages/domain/réseau/src/raccordement/consulter/consulterRaccordement.query.ts
packages/domain/réseau/src/raccordement/modifier/modifierGestionnaireRéseauRaccordement.command.ts
packages/specifications/src/raccordement/attribuerGestionnaireRéseau.feature
packages/specifications/src/raccordement/modifierGestionnaireRéseauRaccordement.feature
packages/specifications/src/raccordement/stepDefinitions/raccordement.then.ts
packages/specifications/src/raccordement/stepDefinitions/raccordement.when.ts

Dans l'optique d'automatiser l'import de la date de Mise en service du raccordement, ainsi que la correction du code EIC, nous devons d'abord flagger comme `inconnu` tous les GRD qu'on ne peut vérifier dû aux mauvaises données, qui nous empêche un mapping correct avec les data ORE (principalement des typos dans les villes ou les codes postaux)
Cette PR introduit la capabilité d'attribuer un GRD "inconnu" à un raccordement, et les modifications du front pour qu'un projet avec GRD "inconnu" puisse être mis à jour
Cas testés: 
- un projet sans raccordement n'a pas de message d'erreur 
- un projet avec raccordement mais un gestionnaire inconnu a un message d'erreur 
- un projet avec raccordement mais un gestionnaire inconnu peut modifier ce gestionnaire (pas de 404)
Cas limite:
- un projet …

✨ Attribuer GRD inconnu

---

packages/applications/legacy/.env.template
packages/applications/legacy/jest.env.ts
packages/applications/legacy/src/config/fileStorage.config.ts
packages/applications/legacy/src/infra/file/S3FileStorageService.integration.ts
packages/applications/scheduled-tasks/s3-backup.sh
packages/applications/ssr/.env.template

Cette PR supprime l'ensemble des variables d'accés au bucket legacy. Ces variables ne sont plus utilisées en production
Lancer les tests avec le script test

♻️ Suppression anciennes variables pour accéder au bucket legacy

---

packages/applications/ssr/src/app/abandons/page.tsx
packages/applications/ssr/src/components/molecules/Search.tsx
packages/applications/ssr/src/components/organisms/ListFilters.tsx
packages/applications/ssr/src/components/pages/abandon/détails/EtapesAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/lister/AbandonList.page.tsx
packages/applications/ssr/src/components/templates/ListPage.template.tsx
packages/domain/lauréat/src/abandon/lister/listerAbandon.query.ts

- ajout barre de recherche
- correction des DownloadDocument pour abandon (la partie format était cachée sous le label)
- suggestion pour la mise en forme barre de recherche / filtres
Ticket : https://linear.app/startup-potentiel/issue/POT-390/ajout-dune-barre-de-recherche-par-nom-de-projets-sur-la-page-abandon

🎨 Ajout barre recherche sur liste abandons

---

packages/applications/document-builder/src/buildDocxDocument/buildDocxDocument.ts

Suite à #1894, les logos ne pouvaient plus être modifiés (par exemple pour les Dreal)

🐛 Modification du logo dans les modèles de document

---

packages/applications/ssr/src/components/pages/abandon/détails/EtapesAbandon.tsx

Fix accés à la transmission de la preuve de rencandidature depuis les étapes alors qu'il n'y a pas d'accord ni de tâche
Avant :
Aprés : 

🐛 Correction des étapes d'un abandon pour affichage transmission preuve uniquement si abandon accordé

---

packages/applications/ssr/src/components/pages/garanties-financières/détails/DétailsGarantiesFinancières.page.tsx

Améliorer la navigation vers la page de transmission de l'attestation de conformité depuis la page détails des GFs

🚸 Ajout d'un bouton pour transmettre l'attestation de conformité depuis la page des gfs (encart dédiée)

---

packages/applications/ssr/src/app/laureats/[identifiant]/abandon/page.tsx
packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.page.tsx
packages/applications/ssr/src/components/pages/abandon/détails/InfoBoxMainlevéeSiAbandonAccordé.tsx
packages/applications/ssr/src/components/pages/abandon/détails/accorder/AccorderAbandonAvecRecandidature.tsx
packages/applications/ssr/src/components/pages/abandon/détails/accorder/AccorderAbandonSansRecandidature.tsx
packages/applications/ssr/src/components/pages/abandon/détails/annuler/AnnulerAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/détails/confirmer/ConfirmerAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/détails/demanderConfirmation/DemanderConfirmationAbandon.tsx
packages/applications/ssr/src/components/pages/abandon/détails/rejeter/RejeterAbandon.tsx

- Création d'une infobox ETQ porteur si abandon accordé
- petites corrections d'affichage (sinon infobox toute petite)
[Issue Linear
](https://linear.app/startup-potentiel/issue/POT-431/[pp]-infox-pour-la-demande-de-mainlevee-des-gf-suite-a-une-demande)
Visuellement

✨ ETQ porteur Infobox mainlevée si abandon accordé

---

packages/applications/scheduled-tasks/attribuer-grd.sh

Le script bash appelait `npm run start:start:attribuer-grd` au lieu de `npm run start:attribuer-grd`
Lancement du script bash en local : `ORE_ENDPOINT=XXXXXX EVENT_STORE_CONNECTION_STRING=XXXXX sh packages/applications/scheduled-tasks/attribuer-grd.sh`

🐛 Fix nom du script npm appelé depuis attribuer-grd.sh

---

.github/workflows/release.yml

Le step "application-version" du workflow de release n'a pas besoin des packages, donc on peut se passer de l'étape d'installation des packages, qui prend ~53s (voir [ici](https://github.com/MTES-MCT/potentiel/actions/runs/9874527938/job/27270622625))

⚡️ Optimisation CD - application version

---

packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.page.tsx

Oublie `gap` entre les boutons

🐛 Fix detail abandon

---

packages/applications/bootstrap/src/setupTâchePlanifiée.ts
packages/domain/tâche-planifiée/src/saga/tâchePlanifiéeGarantiesFinancières.saga.ts
packages/specifications/src/projet/lauréat/garantiesFinancières/importerTypeGarantiesFinancières.feature
packages/specifications/src/projet/lauréat/garantiesFinancières/soumettreGarantiesFinancières.feature
packages/specifications/src/projet/lauréat/garantiesFinancières/stepDefinitions/garantiesFinancières.when.ts
packages/specifications/src/tâche-planifiée/ajouterTâchePlanifiée.feature
packages/specifications/src/tâche-planifiée/annulerTâchePlanifiée.feature
packages/specifications/src/tâche/acheverTâche.feature

- Une tâche est planifiée quand des garanties financières sont enregistrées par l'administration
- Une tâche est planifiée quand l'administration importe le type d'une garanties financières pour un projet
- Une tâche planifiée est annulée lorsqu'un dépôt de garanties financières est soumis
TDD

✅ Planifier / Annuler des tâches programmés liées aux gfs manquants

---

packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/demande-complete-raccordement:modifier/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.form.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.stories.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/modifierDemandeComplèteRaccordement.action.ts
packages/domain/réseau/src/raccordement/modifier/modifierDemandeComplèteRaccordement.behavior.ts
packages/domain/réseau/src/raccordement/modifier/modifierDemandeComplèteRaccordement.command.ts
packages/domain/réseau/src/raccordement/modifier/modifierDemandeComplèteRaccordement.usecase.ts
packages/domain/réseau/src/raccordement/modifier/modifierRéférenceDossierRaccordement.behavior.ts
packages/specifications/src/raccordement/modifierDemandeComplèteDeRaccordement.feature
packages/specifications/src/raccordement/modifierPropositionTechniqueEtFinancière.feature
packages/specifications/src/raccordement/modifierRéférenceDemandeComplèteDeRaccordement.feature
packages/specifications/src/raccordement/stepDefinitions/raccordement.when.ts

- Les DREALS doivent pouvoir modifier une DCR meme si le dossier de raccordement a une date de mise en service 
- Les PP ne doivent pas pouvoir modifier les DCR si le dossier de raccordement a une date de mise en service

🐛 Recadrer les droits de modifications d'une DCR en fonction de si le dossier de raccordement a une date de mise en service

---

.github/workflows/codeql-analysis.yml
.github/workflows/pr.yml

Quand on pousse un nouveau commit sur une PR, on peut annuler la github action en cours

👷 Annulation des builds concurrents sur PR

---

packages/applications/ssr/next.config.js
packages/domain/réseau/package.json
packages/domain/réseau/src/raccordement/raccordement.aggregate.ts
packages/domain/réseau/src/raccordement/transmettre/transmettreDateMiseEnService.behavior.ts
packages/domain/réseau/src/raccordement/transmettre/transmettreDateMiseEnService.command.ts
packages/domain/réseau/tsconfig.json
packages/specifications/src/raccordement/transmettreDateMiseEnService.feature

Suite à l'import des dates de MES vendredi, et de multiples essais dû à différents problèmes d'import, nous avons de nombreux doublons sur l'event stream, sans modification réelle de la donnée.

🐛 Doublons dans l'event stream pour DateMiseEnServiceTransmise

---

packages/infrastructure/ore-client/src/helper/matchOutreMerAndCorseCodePostalToGRD.test.ts
packages/libraries/monitoring/package.json
packages/libraries/monitoring/src/logger.spec.ts
packages/libraries/monitoring/src/logger.ts

- résolution du problème d'affichage des objets
- ajout d'un paramètre optionnel `serviceName` afin de clarifier où le code est exécuté

🔊 Ajout d'un nom de service et fix sur les metadata

---

packages/domain/utilisateur/src/permission.middleware.ts
packages/domain/utilisateur/src/role.valueType.ts

Refactor des permissions afin de pouvoir réutiliser les droits dans le front, grâce à une nouvelle fonction `Role.aLaPermission`.
```ts
// ...
canEdit: rôleUtilisateur.aLaPermission('réseau.raccordement.gestionnaire.modifier'),
// ...
```
Il y a deux points d'entrée aux permissions:
- est-ce que tel utilisateur peut executer tel message (mediator), ex. `Réseau.Raccordement.Command.ModifierGestionnaireRéseauRaccordement`. Utilisé dans le middleware d'application des permissions
- est-ce que tel utilisateur peut faire telle action (métier), ex. `réseau.raccordement.gestionnaire.modifier`. Utilisé dans le front.
Pour garder un seule source de vérité, mais pouvoir accéder aux deux niveaux, on a  maintenant: 
- `référentielPermissions`  qui fait un mapping entre des actions métiers, par …

♻️ Refactor des permissions pour utilisation dans le front

---

packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
packages/applications/ssr/src/components/organisms/garantiesFinancières/GarantiesFinancières.tsx
packages/applications/ssr/src/components/organisms/garantiesFinancières/GarantiesFinancièresActions.tsx

- meilleure condition
=> tout le monde a le droit d'enregistrer une attestation de constitution donc suppression de la condition
- supprimer doublon de wording

🚸 Fix alerte si pas d'attestation de constitution

---

packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/demande-complete-raccordement:modifier/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
packages/domain/réseau/src/raccordement/modifier/modifierDemandeComplèteRaccordement.behavior.ts
packages/domain/réseau/src/raccordement/modifier/modifierRéférenceDossierRaccordement.behavior.ts
packages/domain/réseau/src/raccordement/transmettre/transmettreDemandeComplèteRaccordement.behavior.ts
packages/specifications/src/raccordement/modifierDemandeComplèteDeRaccordement.feature
packages/specifications/src/raccordement/modifierRéférenceDemandeComplèteDeRaccordement.feature
packages/specifications/src/raccordement/transmettreDemandeComplèteDeRaccordement.feature

**Quand une date de mise en service est transmise sur un DCR**
ETQ DREAL je dois pouvoir soumettre une nouvelle DCR  ✅ 
ETQ DREAL je peux modifier une DCR qui n'est pas en service  ✅ 
ETQ DREAL je ne peux plus modifier la DCR en service  ✅ 
ETQ DREAL je dois pouvoir soumettre une PTF  ✅ 
ETQ DREAL je dois pouvoir modifier une PTF  ✅ 
ETQ PP  je ne peux pas modifier la référence de raccordement  d'une DCR "en service"  ✅ 
ETQ DREAL je ne dois pas pouvoir modifier la référence de raccordement d'une DCR "en service"  ✅
https://linear.app/startup-potentiel/issue/POT-400/%5Bdreal%5D-en-tant-que-dreal-je-dois-avoir-les-meme-droits-sur-la-page
front / back

🐛 Mise a jour des droits DREAL sur raccordement si date de mise en service v2

---

packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/modifierGestionnaireRéseauRaccordement.action.ts
packages/domain/réseau/src/raccordement/modifier/modifierGestionnaireRéseauRaccordement.behavior.ts
packages/domain/réseau/src/raccordement/modifier/modifierGestionnaireRéseauRaccordement.command.ts
packages/domain/réseau/src/raccordement/modifier/modifierGestionnaireRéseauRaccordement.usecase.ts
packages/domain/réseau/src/raccordement/raccordement.aggregate.ts
packages/specifications/src/raccordement/modifierGestionnaireRéseauRaccordement.feature
packages/specifications/src/raccordement/stepDefinitions/raccordement.when.ts

- ETQ PP, Impossibilite de changer gestionnaire du raccordement si DMS
- ETQ DREAL, Impossibilite de changer gestionnaire du raccordement si DMS
- 
https://linear.app/startup-potentiel/issue/POT-476/impossible-pour-un-porteur-de-projet-de-modifier-le-gestionnaire-de

🐛 Mise a jour des droits DREAL sur raccordement si date de mise en service

---

package-lock.json
packages/applications/ssr/next.config.js
packages/applications/ssr/package.json
packages/applications/ssr/sentry.client.config.ts
packages/applications/ssr/sentry.server.config.ts
packages/applications/ssr/src/app/global-error.tsx
packages/applications/ssr/src/instrumentation.ts
packages/applications/ssr/src/utils/getAuthenticatedUser.handler.ts

Pour réduire la taille de l'image docker afin de débloquer les erreur lors des déploiements il a fallu retirer la partie sentry pour l'instant le temps de trouver une solution pérenne.

🔥 Désactivation de sentry dans l'application NextJS

---

packages/applications/legacy/src/modules/project/Project.ts

Afin de corriger les dates d'achèvement erronées de projets ayant la mauvaise technologie
Cette PR active la mise à jour de la date à chaque fois lors d'un ré-import qui entraîne un changement de technologie.
Avec un dump de prod et un fichier de correction pour la période 2 de l'appel d'offre `PPE2 - Neutre` présent dans l'issue Linear.

✨ Mise à jour de la date d'achèvement lors d'un ré-import avec changement de technologie

---

packages/applications/ssr/src/app/reseaux/gestionnaires/page.tsx

`Promise.all` ne garantie pas l'ordre d'insertion dans l'array

🐛 Correction de l'ordre des GRD

---

packages/domain/utilisateur/src/role.valueType.ts
packages/domain/utilisateur/src/vérifierAccèsProjet/vérifierAccèsProjet.query.ts

🐛 Les utilisateurs de type CRE + caisse des dépôts doivent avoir accès à l'historique des mainlevée d'une GF

---

packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/enregistrerAttestationGarantiesFinancièresActuelles.feature
packages/specifications/src/projet/lauréat/garantiesFinancières/actuelles/importerTypeGarantiesFinancièresActuelles.feature

Les scénarios supprimés : 
- Impossible d'enregistrer l'attestation des garanties financières actuelles si celles-ci sont échues
- Impossible d'importer le type (et la date d'échéance selon le cas) des garanties financières actuelles si le projet dispose déjà de garanties financières échues

🔥 Supprimer les scénarios notimplemented inutiles après analyse métier

---

packages/applications/ssr/src/components/pages/candidatures/importer/candidature.schema.test.ts
packages/applications/ssr/src/components/pages/candidatures/importer/candidature.schema.ts

les noms des colonnes du fichier sont assez longs, ce qui rend peu lisible leur utilisation dans le code. Afin de garder quelque chose de lisible, on a un champs `colonnes` qui fait le mapping entre un nom facile à maniupler, et le nom réel de la colonne. 
Le mapping est fait en tout dernier, afin que les erreurs de validations référencent le nom tel qu'écrit dans le fichier, pour plus de clarté pour l'utilisateur. 
La partie traduction en 🇫🇷 sera faite plus tard, quand #2055 sera fini, afin de visualiser l'affichage des erreurs et d'adapter le wording en fonction

✨ Schema de validation du fichier CSV d'import des candidatures

---

packages/applications/cli/src/commands/raccordement/importer-date-mes.ts
packages/applications/legacy/src/controllers/modificationRequest/délai/getCorrigerDelaiAccordePage.ts
packages/applications/legacy/src/controllers/modificationRequest/délai/postCorrigerDelaiAccorde.ts
packages/applications/legacy/src/views/components/UI/templates/PageProjetTemplate.tsx
packages/applications/legacy/src/views/pages/délai/CorrigerDelaiAccordePage.tsx
packages/applications/notifications/src/subscribers/lauréat/tâchePlanifiée.notification.ts
packages/applications/ssr/src/app/laureats/[identifiant]/abandon/demander/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/abandon/modele-reponse/route.ts
packages/applications/ssr/src/app/laureats/[identifiant]/achevement/attestation-conformite:modifier/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/achevement/attestation-conformite:transmettre/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/actuelles:enregistrer-attestation/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/actuelles:enregistrer/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/actuelles:modifier/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/depot:modifier/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/depot:soumettre/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/modele-mise-en-demeure/route.ts
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/modele-reponse-mainlevee/route.ts
packages/applications/ssr/src/app/laureats/[identifiant]/garanties-financieres/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/[reference]/date-mise-en-service:transmettre/page.tsx
packages/applications/ssr/src/components/molecules/projet/ProjetBanner.tsx
packages/applications/ssr/src/components/pages/abandon/détails/accorder/accorderAbandonAvecRecandidature.action.ts
packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/importDatesMiseEnService.action.ts
packages/domain/candidature/src/consulter/consulterProjet.query.ts
packages/domain/candidature/src/index.ts
packages/domain/candidature/src/register.ts
packages/domain/utilisateur/src/role.valueType.ts

la "candidature" concerne les données du projet au moment où il a candidaté. 
le "projet" a des données supplémentaires, comme un statut différent et une date de désignation. C'est l'état "actuel" du projet. En réalité, "projet" disparaitra au profit de "lauréat", "éliminé" et "candidature".
Dans #2058, on ajoute l'import des candidatures dans la nouvelle stack, et on aura besoin de consulter ces données, d'où le renommage.

♻️ Renommage de ConsulterCandidature en ConsulterProjet

---

packages/applications/legacy/src/controllers/notificationCandidats/index.ts
packages/applications/legacy/src/controllers/notificationCandidats/legacyGetAdminImporterCandidatsPage.ts
packages/applications/legacy/src/controllers/notificationCandidats/postImportProjects.ts
packages/applications/legacy/src/routes.ts
packages/applications/legacy/src/views/components/UI/organisms/UserNavigation.tsx
packages/applications/legacy/src/views/index.ts
packages/applications/legacy/src/views/pages/LegacyAdminImporterCandidatsPage.tsx
packages/applications/legacy/src/views/pages/index.ts
packages/applications/routes/src/candidature/candidature.routes.ts
packages/applications/routes/src/candidature/index.ts
packages/applications/routes/src/index.ts
packages/applications/routes/src/lauréat/raccordement.routes.ts
packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx
packages/applications/ssr/src/components/molecules/projet/ProjetListItem.tsx

On garde l'ancienne page le temps que la feature soit full migrée, elle sera dispo via l'url seulement.
La nouvelle route vient remplacer l'ancienne dans le menu

🎨 Lien vers la nouvelle page d'import des candidats

---

package-lock.json
packages/applications/legacy/src/views/pages/AdminNotificationCandidatsPage.tsx

Quand il n'y a aucun filtre dans l'url et qu'on sélectionne une période différente alors le filtre ne s'applique pas et la prériode est remise à celle de départ. Cela est dû au fait que l'on ne transmet pas l'appel d'offres au changement de période.
- Correction de bug

🚑️ Correction sur les filtres de la page de notification des candidats

---

packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact.tsx

Création de la rubrique "Adresse email de candidature" dans la partie "Contact" pour pouvoir y intégrer l'adresse email contact

💄 Affichage de l'adresse email ayant servi à la candidature

---

packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/lister/ListItemDemandeMainlevée.tsx

En tant qu'utilisateur de la DGEC (ADMIN, DGEC, DGEC-VALIDATEUR) je dois avoir accès à un raccourci vers le détail des mainlevées depuis la page listing des mainlevée sur Potentiel

✨ Avoir un lien d'accès au détail de la mainlevée

---

packages/domain/candidature/src/corriger/corrigerCandidature.usecase.ts
packages/domain/candidature/src/importer/importerCandidature.usecase.ts

Si le document est enregistré après, il n'est pas disponible dans la saga legacy et `récupérerDocument` plante

🐛 Enregistrer les détails avant d'importer

---

packages/applications/ssr/src/components/organisms/List.tsx
packages/applications/ssr/src/components/templates/ListPage.template.tsx

Supprime un warning affiché lors du render des listes

🐛 Ne pas spread la prop `key` dans List

---

packages/applications/ssr/src/components/molecules/Filter.tsx
packages/applications/ssr/src/components/molecules/ListFilters.tsx

Quand on sélectionnait un filtre sur une liste, alors un tag apparait et nous permet d'afficher la liste filtrée. Si je clique sur la croix du tag pour le supprimer, la liste se mettait bien à jour, par contre la valeur du filtre sélectionné restait actif dans ListFilters. Cette PR fixe ce problème.

🎨 Suppression du filtre actif dans ListFilters quand on supprime un tag appliqué

---

packages/applications/ssr/src/components/atoms/form/Form.tsx
packages/applications/ssr/src/components/molecules/ModalWithForm.tsx
packages/applications/ssr/src/components/pages/abandon/demander/DemanderAbandon.form.tsx
packages/applications/ssr/src/components/pages/abandon/transmettrePreuveRecandidature/TransmettrePreuveRecandidature.form.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/AttestationConformité.form.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/FormulaireAttestationConformité.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/modifier/modifierAttestationConformité.page.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.page.tsx
packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidatures.form.tsx
packages/applications/ssr/src/components/pages/candidature/importer/ImporterCandidatures.form.tsx
packages/applications/ssr/src/components/pages/garanties-financières/FormulaireGarantiesFinancières.tsx
packages/applications/ssr/src/components/pages/garanties-financières/GarantiesFinancières.form.tsx
packages/applications/ssr/src/components/pages/garanties-financières/actuelles/enregistrer/EnregistrerGarantiesFinancières.page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/actuelles/enregistrerAttestation/EnregistrerAttestationGarantiesFinancières.form.tsx
packages/applications/ssr/src/components/pages/garanties-financières/actuelles/modifier/ModifierGarantiesFinancièresActuelles.form.tsx
packages/applications/ssr/src/components/pages/garanties-financières/dépôt/modifier/ModifierDépôtEnCoursGarantiesFinancières.page.tsx
packages/applications/ssr/src/components/pages/garanties-financières/dépôt/soumettre/SoumettreGarantiesFinancières.page.tsx
packages/applications/ssr/src/components/pages/réseau/gestionnaire/ajouter/AjouterGestionnaireRéseau.form.tsx
packages/applications/ssr/src/components/pages/réseau/gestionnaire/modifier/ModifierGestionnaireRéseau.form.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/importerDatesMiseEnService/importerDatesMiseEnService.form.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierDemandeComplèteRaccordement/ModifierDemandeComplèteRaccordement.form.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierGestionnaireRéseauRaccordement/ModifierGestionnaireRéseauRaccordement.form.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/modifier/modifierPropositionTechniqueEtFinancière/ModifierPropositionTechniqueEtFinancière.form.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDateMiseEnService/TransmettreDateMiseEnService.form.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.form.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettrePropositionTechniqueEtFinancière/TransmettrePropositionTechniqueEtFinancière.form.tsx

On affichait différemment les boutons d'actions des formulaires
Ajouter une nouvelle props obligatoire "actionButtons" pour définir le positionnement des boutons dans le composant générique Form.
Dans le front de l'app

♻️ Uniformiser les boutons d'actions des formulaires

---

packages/applications/projectors/src/subscribers/candidature/candidature.projector.ts
packages/applications/ssr/src/app/candidatures/page.tsx
packages/domain/candidature/src/candidature.entity.ts
packages/domain/candidature/src/lister/listerCandidatures.query.ts

Ajout du filtre sur les périodes de l'appel d'offres sélectionné dans la liste des candidatures

✨ Filtrer les candidatures par période d'un appel d'offres

---

package-lock.json
packages/applications/bootstrap/src/setupLauréat.ts
packages/applications/bootstrap/src/setupRéseau.ts
packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
packages/domain/lauréat/src/abandon/index.ts
packages/domain/réseau/package.json
packages/domain/réseau/src/raccordement/index.ts
packages/domain/réseau/src/raccordement/raccordement.aggregate.ts
packages/domain/réseau/src/raccordement/raccordement.register.ts
packages/domain/réseau/src/raccordement/raccordement.saga.ts
packages/domain/réseau/src/raccordement/supprimer/supprimerRaccordement.behavior.ts
packages/domain/réseau/src/raccordement/supprimer/supprimerRaccordement.command.ts
packages/infrastructure/domain-adapters/src/projet/listerProjetForOre.adapter.ts
packages/specifications/src/raccordement/stepDefinitions/raccordement.then.ts
packages/specifications/src/raccordement/supprimerRaccordement.feature

- Réaction via une saga à l'évènement AbandonAccordé
- Suppression du raccordement et des dossiers associés
TDD

✨ Supprimer le raccordement d'un projet lorsque celui-ci a son abandon accordé

---

packages/specifications/src/candidature/corrigerCandidature.feature

les tests utilisant désormais des valeurs aléatoires, on peut avoir le cas où l'appel d'offre est déjà `PPE2 - Neutre`

✅ Fix flaky test dans corriger candidature

---

packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.stories.tsx

Le storybook cassait car le format de la réponse signée était invalide, ce qui empêchait de pouvoir visualiser les stories

🐛 storybook : fix abandon détails stories

---

packages/applications/legacy/src/server.ts

Retiré de `script-src`, `connect-src`, laissé dans `style-src`
je ne vois pas de raison particulière d'avoir cette directive
Crisp ne demande pas ce header dans script-src ou connect-src, mais le demande pour style-src. cf https://docs.crisp.chat/guides/others/whitelisting-our-systems/crisp-domain-names/
NB: je ne touche pas pour l'instant à la directive `data:` qui a l'air utilisée par le DSFR

🔧 Mise à jour du header CSP sans 'unsafe-inline'

---

packages/applications/legacy/src/views/index.html.tsx
packages/applications/ssr/src/app/layout.tsx
packages/applications/ssr/src/app/robots.ts
packages/applications/ssr/src/middleware.ts

Ajout d'une page robots.txt, qui n'autorise que l'indexation de la home page, afin d'améliorer le score [lighthouse pour le SEO](https://dashlord.mte.incubateur.net/report/aHR0cHM6Ly9wb3RlbnRpZWwuYmV0YS5nb3V2LmZy/lhr-aHR0cHM6Ly9wb3RlbnRpZWwuYmV0YS5nb3V2LmZyLw==.html)
Ajout d'un tag `description`  ([docs](https://developer.chrome.com/docs/lighthouse/seo/meta-description))

🔍️ Ajout d'une page `robots.txt` et d'un tag `description`

---

packages/applications/ssr/src/components/pages/réseau/raccordement/détails/DétailsRaccordement.page.tsx

💄 Affichage différent si 1 ou plusieurs dossiers de raccordement

---

packages/applications/legacy/src/server.ts

Le [dashlord](https://dashlord.mte.incubateur.net/url/potentiel-beta-gouv-fr/securite/) nous donne un mauvais score suite à l'analyse faite par [Mozilla Observatory](https://observatory.mozilla.org/analyze/potentiel.beta.gouv.fr), notamment au niveau des CSP
Pour les redéfinir les CSP j'ai utilisé l'extension [Laboratory](https://addons.mozilla.org/en-US/firefox/addon/laboratory-by-mozilla/) qui permet de générer des CSP par rapport au besoin d'un site. Je suis repassé ainsi sur toutes les pages de la production.
Le contenu de cette PR est les CSP générés, ça devrait fixer nos soucis normalement.
**Avant**
**Après**

🔒️ Redefine CSP

---

packages/applications/scheduled-tasks/package.json
packages/applications/scheduled-tasks/src/annuler-echoir-gf-abandonnés-ou-éliminés.ts
packages/applications/scheduled-tasks/src/annuler-echoir-gf.ts
packages/domain/lauréat/src/garantiesFinancières/typeTâchePlanifiéeGarantiesFinancières.valueType.ts

script temporaire pour annuler les tâches planifiées pour les projets abandonnés et éliminés
Cela ne remplace pas l'implémentation nécessaire pour gérer les cas futurs, mais permet d'annuler les tâches insérées par erreur.

🐛 Annuler tâches 'échoir' GF pour abandonnés et éliminés

---

packages/applications/scheduled-tasks/package.json
packages/applications/scheduled-tasks/src/ajouter-rappel-gf-avec-date-echeance.ts

Ce script rattrape les projets qui ont une tâche programmée pour échoir leurs gfs SANS rappel à un mois ou deux mois de l'échéance
Avec un dump de prod en local

🎨 Ajouter les rappels d'échéance pour les projets ayant une tâche pour échoir ses GFs

---

packages/applications/ssr/src/app/candidatures/page.tsx
packages/applications/ssr/src/components/molecules/UserBasedRoleNavigation.tsx

et retirer le lien "régénérer des attestations" dans le ssr (déjà fait dans le legacy)

🐛 Corriger la preview d'attestation quand on filtre par période

---

packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/corrigerRéponseSignée/CorrigerRéponseSignée.form.tsx
packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/corrigerRéponseSignée/corrigerRéponseSignée.action.ts

🐛 Rendre obligatoire le document lors de la correction de réponse de mainlevée

---

packages/applications/legacy/src/controllers/project/getProjectPage.ts

Ex: https://potentiel-staging.osc-fr1.scalingo.io/projet/c1644a65-9a6c-465a-baab-2dcca8907d12/details.html
la page envoie une erreur, ce qui cause "page non trouvée"
c'est dû au fait que `dossiersRaccordement.dossiers[0]` est undefined

🐛 Page non trouvée en l'absence de dossier de raccordement

---

docs/contributing/CODING_CONVENTION.md
packages/applications/ssr/src/app/abandons/page.tsx
packages/applications/ssr/src/app/candidatures/page.tsx
packages/applications/ssr/src/app/garanties-financieres/demandes-mainlevee-en-cours/page.tsx
packages/applications/ssr/src/app/garanties-financieres/depots-en-cours/page.tsx
packages/applications/ssr/src/app/garanties-financieres/projets-en-attente/page.tsx
packages/applications/ssr/src/app/periodes/page.tsx
packages/applications/ssr/src/app/recours/page.tsx
packages/applications/ssr/src/app/taches/page.tsx
packages/applications/ssr/src/components/molecules/Filter.tsx
packages/applications/ssr/src/components/molecules/ListFilters.stories.tsx
packages/applications/ssr/src/components/molecules/ListFilters.tsx
packages/applications/ssr/src/components/organisms/ListHeader.tsx
packages/applications/ssr/src/components/pages/abandon/lister/AbandonList.stories.tsx
packages/applications/ssr/src/components/pages/candidature/lister/CandidatureList.stories.tsx
packages/applications/ssr/src/components/pages/garanties-financières/dépôt/lister/ListerDépôtsEnCoursGarantiesFinancières.stories.tsx
packages/applications/ssr/src/components/pages/garanties-financières/en-attente/lister/ListerProjetsAvecGarantiesFinancièresEnAttente.stories.tsx
packages/applications/ssr/src/components/pages/garanties-financières/mainlevée/lister/ListeDemandeMainlevée.stories.tsx
packages/applications/ssr/src/components/pages/période/PériodeList.stories.tsx
packages/applications/ssr/src/components/pages/recours/lister/RecoursList.stories.tsx
packages/applications/ssr/src/components/pages/tâche/TâcheList.stories.tsx

- suppression des defaultValue au niveau des filters (qui n'ont pas d'intérêt et compliquent la logique de l'url)
- rajout au niveau des filtres de la notion de dépendance de 2 filtres (```affects``` / ```dependsOn```) et amélioration de la logique. 1er test sur la page candidature

🐛 Fix filters and defaultValue

---

packages/domain/période/src/lister/listerPériodesNonNotifiées.ts
packages/domain/période/src/lister/listerToutesLesPériodes.ts

Actuellement quand on affiche la liste des périodes non notifiées ou sans aucun filtre alors on a que 9 éléments au lieu de 10 et le 10ème élément ne sera jamais affiché.

🐛 Correction du nombre d'élément retournés pour la liste des périodes

---

packages/applications/ssr/src/app/periodes/page.tsx
packages/domain/entity/src/orderByOptions.ts
packages/domain/période/src/consulter/consulterPériode.query.ts
packages/domain/période/src/lister/listerPériodesNonNotifiées.ts
packages/domain/période/src/lister/listerPériodesNotifiées.ts
packages/domain/période/src/lister/listerToutesLesPériodes.ts
packages/domain/période/src/période.entity.ts
packages/domain/période/tsconfig.json

Afin d'avoir une liste ordonnée des périodes, il faut trier automatiquement la liste des périodes selon les filtres appliqués :
- Toutes les périodes : tri par appel d'offres
- À notifier : tri par appel d'offres
- Notifiées : tri par date de notification

✨  Tri de la liste des périodes

---

packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
packages/applications/notifications/src/subscribers/période/période.notification.ts
packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.action.ts
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordement.page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordementAlert.tsx

- Alerte plus claire si pas de dossier de raccordement sur la page détail
- Suite à la transmission d'une attestation de conformité, je suis renvoyé vers la page détail de raccordement si je n'ai pas de dossier de raccordement
[Ticket](https://linear.app/startup-potentiel/issue/POT-528/etq-equipe-potentiel-nous-souhaitons-avoir-un-maximum-de-projets-en)
Visuel & scénario
- Nouvelle alerte
- Test du redirect

🎨 ETQ PP je suis invite a transmettre mon DCR

---

packages/applications/scheduled-tasks/src/candidature/getLocalité.ts
packages/applications/scheduled-tasks/src/candidature/getRégionAndDépartementFromCodePostal.ts
packages/applications/scheduled-tasks/src/candidature/migrate-project-import-events.ts

1er commit: le script tel qu'il était à la précédente migration
2e commit: retirer les champs supprimés depuis la migration
autres: les vrais corrections

🐛 Corriger statut lors du réimport des candiatures

---

package-lock.json
packages/applications/bootstrap/src/setupCandidature.ts
packages/applications/bootstrap/src/setupEliminé.ts
packages/applications/bootstrap/src/setupLauréat.ts
packages/applications/document-builder/package.json
packages/applications/document-builder/src/candidature/attestation/attestation.saga.ts
packages/applications/document-builder/tsconfig.json
packages/applications/projectors/src/subscribers/candidature/candidature.projector.ts
packages/domain/candidature/src/candidature.aggregate.ts
packages/domain/candidature/src/candidature.entity.ts
packages/domain/candidature/src/candidature.ts
packages/domain/candidature/src/consulter/consulterCandidature.query.ts
packages/domain/candidature/src/lister/listerCandidatures.query.ts
packages/domain/candidature/src/notifier/notifierCandidature.behavior.ts
packages/domain/candidature/src/notifier/notifierCandidature.command.ts
packages/domain/candidature/src/notifier/notifierCandidature.usecase.ts
packages/domain/candidature/src/register.ts
packages/domain/lauréat/src/lauréat.aggregate.ts
packages/domain/lauréat/src/notifier/notifierLauréat.behavior.ts
packages/domain/période/package.json
packages/domain/période/src/notifier/notifierPériode.command.ts
packages/domain/période/tsconfig.json
packages/domain/utilisateur/src/role.valueType.ts
packages/domain/éliminé/src/notifier/notifierÉliminé.behavior.ts
packages/domain/éliminé/src/éliminé.aggregate.ts
packages/specifications/src/candidature/candidature.world.ts
packages/specifications/src/candidature/stepDefinitions/candidature.then.ts
packages/specifications/src/période/notifierPériode.feature

Un nouvel évenement CandidatureNotifiée est ajouté. Il est redondant avec `LauréatNotifié` et `ÉliminéNotifié`, mais permet:
- de simplifier la saga attestation en réaction à ces deux événements
- d'avoir l'information `estNotifiée` sur une candidature, afin de permettre un filtre et la fonctionalité "notifier des candidats oubliés d'une période"
- de simplifier le téléchargement de l'attestation (on peut retrouver l'attestation en 1 query, plutot que vérifier lauréat et éliminé). Non implémenté dans cette PR

♻️ Candidature notifiée

---

packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/raccordements/demande-complete-raccordement:transmettre/page.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/AttestationConformité.form.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/InfoAttestationConformité.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/modifier/modifierAttestationConformité.page.tsx
packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.action.ts
packages/applications/ssr/src/components/pages/attestation-conformité/transmettre/transmettreAttestationConformité.page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/détails/AucunDossierDeRaccordementAlert.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/transmettre/transmettreDemandeComplèteRaccordement/TransmettreDemandeComplèteRaccordement.stories.tsx

Petits changements vu avec Matthieu pour la release 👍 
- changement du texte de l'alerte si pas de raccordement,
- Affichage de l'alerte dans la page transmettre (en plus de la page récap) si pas de raccordement

🐛 Fix/ raccordement text & alert

---

packages/applications/projectors/src/infrastructure/updateProjection.spec.ts
packages/applications/projectors/src/infrastructure/updateProjection.ts

Amélioration de `updateProjection` pour ne faire qu'une seule query. 
`jsonb_set` ne supporte pas les update multiples, donc on fait un update récursif (`jsonb_set(jsonb_set(...))`).
Insipré de https://github.com/event-driven-io/Pongo

⚡️ Optimisation de `updateProjection`

---

packages/infrastructure/email/src/sendEmail.ts

Suite au problème d'envoi d'email en prod pendant la maintenance, on ajout cette condition pour éviter quoi qu'il arrive qu'en mode maintenance des emails partent

🎨 Ajout d'un gardefou si l'app est en mode maintenance (pas d'envoi d'email)

---

packages/applications/legacy/src/views/components/UI/organisms/MetabaseStats.tsx
packages/applications/legacy/src/views/components/UI/organisms/index.ts
packages/applications/legacy/src/views/pages/AcheteurObligeStatistiquesPage.tsx
packages/applications/legacy/src/views/pages/AdemeStatistiquesPage.tsx
packages/applications/legacy/src/views/pages/AdminStatistiquesPage.tsx
packages/applications/legacy/src/views/pages/CreStatistiquesPage.tsx
packages/applications/legacy/src/views/pages/StatistiquesPage.tsx

les CSP empêchent l'execution du script inline `onload`, et l'iframe n'est pas resize correctement. En passant tout en react, on a plus le problème. 
En local, j'ai un soucis de scintillement, j'aimerais tester en dev si ca fait pareil.

🐛 Correction de l'affichage des Statistiques

---

docker-compose.yml

Dans de rare cas, le bucket n'est pas créé sur minio car celui-ci n'est pas encore joignable. l'ajout de `mc ping -c 1`  permet d'attendre un ping successful avant de continuer. 
Au passage, mini changement de la config docker compose pour plus de lisibilité

🧑‍💻 Attendre que minio soit up avant de créer le bucket

---

packages/applications/legacy/src/server.ts
packages/applications/legacy/src/views/components/UI/organisms/MetabaseStats.tsx

- Bug lors du download de stats
- Erreur sur l'attribut `AllowTransparency` qui existe pas

🐛 Fix csp when downloading stats

---

.demo/Tests-Intrusions-EY.csv
packages/domain/inmemory-referential/src/appelOffre/test.ts

Afin que les tests d'intrusion soient le plus exhaustif possible et ne pas perturber les données de production
Nous devons créer un appel d'offre "Test" pour lequel il sera possible d'importer des projets de tests
Les tests ayant lieu dans 3 jours il est nécessaire de l'avoir rapidement en production d'où l'utilisation de la `release/3.31` qui est celle actuellement en production

🧪 Ajout d'un appel d'offre "Test" nécessaire à la phase de tests d'intrusion

---

packages/applications/ssr/src/components/pages/candidature/corriger-par-lot/corrigerCandidatures.action.ts
packages/applications/ssr/src/components/pages/candidature/importer/candidature.schema.test.ts
packages/applications/ssr/src/components/pages/candidature/importer/candidature.schema.ts
packages/applications/ssr/src/components/pages/candidature/importer/importerCandidatures.action.ts
packages/domain/candidature/src/candidature.aggregate.ts
packages/domain/candidature/src/corriger/corrigerCandidature.behavior.ts
packages/domain/candidature/src/importer/importerCandidature.behavior.ts
packages/specifications/src/candidature/corrigerCandidature.feature
packages/specifications/src/candidature/importerCandidature.feature

Afin de réduire les manipulations manuelles avant un import de fichier CRE:
- support de "Retenu" dans la colonne "Classé ?", qui vaut "Classé"
- la colonne "voie... 1" peut-être vide si "voie... 2" ne l'est pas
- les projets éliminés peuvent avoir un type de GF, auquel cas on ne doit pas valider la date d'échéance
- support de "" (vide) au même titre que "N/A" pour les colonnes optionnelles (je n'ai identifié que évaluation carbone qui manquait)
Pour simplifier la gestion des erreurs
- ajout du numéro CRE dans les erreurs (métier uniquement, pas CSV)
Bonus:
- les tests ne passaient plus suite au renommage des colonnes en camelCase
- certains champs n'avaient pas été renommés en camelCase
- petit fix d'un bug si import via CSV: on doit ignorer `détailsMisÀJour` pour comparer l'ancienne …

✨ Améliorations de l'import CRE

---

packages/applications/projectors/src/infrastructure/updateManyProjection.spec.ts
packages/applications/projectors/src/infrastructure/updateManyProjections.ts
packages/applications/projectors/src/infrastructure/updateOneProjection.spec.ts
packages/applications/projectors/src/infrastructure/updateOneProjection.ts
packages/applications/projectors/src/subscribers/candidature/candidature.projector.ts
packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
packages/applications/ssr/src/app/reseaux/raccordements/page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/lister/DossierRaccordementList.page.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/lister/DossierRaccordementList.stories.tsx
packages/applications/ssr/src/components/pages/réseau/raccordement/lister/DossierRaccordementListItem.tsx
packages/domain/réseau/src/raccordement/lister/listerDossierRaccordement.query.ts
packages/infrastructure/pg-projections/src/index.ts

Reprend la correction de #2383 avec optimisation pour ne faire qu'une seule query
Bonus (optionnel, ca m'a servi pour tester mais je peux le retirer): ajout de la raison sociale du gestionnaire réseau dans le list item

🐛 Corriger la maj des Dossier de Raccordement après changement de gestionnaire

---

packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/enregistrer/enregistrerGarantiesFinancières.behavior.ts
packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/enregistrerAttestation/enregistrerAttestationGarantiesFinancières.behavior.ts
packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/importer/importerTypeGarantiesFinancières.behavior.ts

On devrait toujours maj l'aggregat gf sans écraser son état avant l'insertion de l'event
prévoir un rebuild gf

🐛 Aggrégat GF toujours redéfinit lorsqu'un évènement est ajouté

---

packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/enregistrer/enregistrerGarantiesFinancières.behavior.ts
packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/enregistrerAttestation/enregistrerAttestationGarantiesFinancières.behavior.ts
packages/domain/lauréat/src/garantiesFinancières/garantiesFinancièresActuelles/importer/importerTypeGarantiesFinancières.behavior.ts

Hotfixe : évènements GFs doivent surcharger les GFs actuelles et pas les redéfinir (aggrégat)

🔀 Intégration des modifications de la release 3.32

---

package-lock.json
packages/infrastructure/filigrane-facile-client/package.json
packages/infrastructure/filigrane-facile-client/src/ajouterFiligrane.ts
packages/infrastructure/filigrane-facile-client/tsconfig.json

Le fait d'avoir un getLogger dans un composant rendu coté serveur provoque une erreur dès qu'on arrive sur une page qui a un formulaire qui upload des fichiers.
Le fix tmp est de supprimer la dépendance au logger

🐛 Fix build ssr (getlogger) dans ajouterFiligrane

---

CONTRIBUTING.md
docs/contributing/API.md
packages/applications/ssr/src/utils/getAuthenticatedUser.handler.ts

Create a new client (grd-integration-enedis)
go to its service account 
give it an email (doesn't need to be valid, eg grd-integration-enedis@clients)
make it part of the group 17X100A100A0001A
enjoy
```ts
import * as client from "openid-client";
const { ISSUER_URL, CLIENT_ID, CLIENT_SECRET } = process.env;
const options = ISSUER_URL?.match(/http:\/\/localhost/)
? { execute: [client.allowInsecureRequests] }
: {};
const config = await client.discovery(
new URL(ISSUER_URL!),
CLIENT_ID!,
CLIENT_SECRET,
undefined,
options
);
const tokens = await client.clientCredentialsGrant(config, {});
const res = await client.fetchProtectedResource(
config,
tokens.access_token,
new URL("http://localhost:3000/api/v1/taches"),
"GET"
);
console.log(res.status, res.statusText);
console.log(await res.json()); …
```

✨ Récupérer le token d'authentication depuis les headers

---

packages/applications/legacy/src/views/components/UI/atoms/Badge.tsx
packages/applications/legacy/src/views/components/UI/templates/PageProjetTemplate.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeaderBadge.tsx
packages/applications/legacy/tailwind.config.js
packages/applications/ssr/src/components/molecules/candidature/NotificationBadge.tsx
packages/applications/ssr/src/components/molecules/projet/StatutProjetBadge.tsx

- legacy et ssr
- J'ai préféré faire un quick fix de transformation plutôt que de changer le valuetype de project statut (ainsi que les queries...)

🐛 Fix : uniformisation bouton "à notifier"

---

packages/infrastructure/pg-event-sourcing/src/subscribe/errors/DomainEventHandlingFailed.error.ts
packages/infrastructure/pg-event-sourcing/src/subscribe/errors/NotificationPayloadParse.error.ts
packages/infrastructure/pg-event-sourcing/src/subscribe/errors/RebuildFailed.error.ts
packages/infrastructure/pg-event-sourcing/src/subscribe/errors/UnknownEventHandlingFailed.error.ts
packages/infrastructure/pg-event-sourcing/src/subscribe/eventStreamEmitter.ts
packages/libraries/monitoring/src/logger.ts

les erreurs `Handling domain event failed ` ne loggent pas de cause, car `JSON.stringify(new Error("hello"))` => 
`'{}'`. 
Ce fix passe  l'erreur d'origine en cause de `DomainEventHandlingFailedError`, et ajoute la cause dans le log d'erreur.
la bonne facon de logguer les erreurs est donc : `logger.error(new CustomError(error))` ou `logger.error(new Error("custom mesage", { cause: error})` pour des erreurs non réutilisable

🔊 Amélioration du log des erreurs

---

packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getReprésentantLégal.ts
packages/applications/projectors/src/subscribers/lauréat/lauréat.projector.ts
packages/applications/projectors/src/subscribers/lauréat/représentantLégal.projector.ts
packages/applications/ssr/src/components/pages/représentant-légal/modifier/ModifierReprésentantLégal.page.tsx
packages/domain/lauréat/src/lauréat.entity.ts
packages/domain/lauréat/src/représentantLégal/consulter/consulterReprésentantLégal.query.ts

Utilisation de la projection lauréat pour obtenir les infos de représentant légal. Pour l'instant j'ai conservé la query "ConsulterReprésentantLégal" tant qu'on est pas capable de séléctionner des attributs en particulier.
TDD + test visuel

✨ Afficher les infos représentant légal dans la projection lauréat

---

packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getAbandon.ts
packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getAlertesRaccordement.ts
packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getAttestationDeConformité.ts
packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getGarantiesFinancières.ts
packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getRecours.ts
packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getReprésentantLégal.ts
packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
packages/applications/legacy/src/modules/project/queries/GetProjectDataForProjectPage.ts
packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales.tsx
packages/domain/utilisateur/src/role.valueType.ts
packages/libraries/monitoring/src/logger.ts

On a eu pas mal de soucis ces derniers temps pour les queries qui vont récupérer des infos des projections du domain. En effet si le role n'est pas autorisé à accéder à la ressource, la page projet est ko et impossible d'afficher quoi que ce soit.
J'ai ajouté des try/catch partout + modifié les props de la page pour dissocier la props `project` (legacy) des props provenant du domain (via les _utils)
Visuellement en switchant les roles

✨ Ajout de try/catch sur la page legacy projet pour éviter les erreurs de droit sur les queries

---

packages/applications/ssr/src/components/molecules/SignOutRedirect.tsx

Si le logout se fait dès le chargement de la page, la session est chargée en parallèle (via un appel HTTP à /auth/session) et le cookie est recréé aussitôt après avoir été supprimé
Cette PR permet d'attendre que la session soit chargée, et donc que l'appel HTTP soit terminé, donc plus de conflit possible. 
Explication ici: https://github.com/nextauthjs/next-auth/issues/4612#issuecomment-2035552856

🐛 Attendre que la session soit chargée avant de logout

---

packages/applications/ssr/src/components/molecules/projet/ProjectListItemHeading.tsx
packages/applications/ssr/src/components/molecules/projet/StatutProjetBadge.tsx
packages/applications/ssr/src/components/pages/candidature/lister/CandidatureListItem.tsx
packages/domain/candidature/src/lister/listerCandidatures.query.ts

[Ticket](https://linear.app/startup-potentiel/issue/POT-944/afficher-fc-et-gp-a-cote-de-classe-dans-la-liste-des-candidatures) 
Uniquement sur le badge liste, peut être ajouté à d'autres endroits si besoin

✨ Ajout info investissement sur badge candidature

---

packages/domain/réseau/src/raccordement/lister/listerDossierRaccordement.query.ts

[Ticket](https://linear.app/startup-potentiel/issue/POT-950/un-projet-classe-ne-doit-pas-avoir-un-badge-abandonne-dans-la-liste)
La solution la plus évidente était de rajouter un filtre pour ne récupérer que les abandons accordés, mais je pense qu'on peut supprimer complètement la vérification de l'abandon car un projet abandonné aura son raccordement supprimé.

🐛 Correction du statut Abandonné dans la liste des raccordements

---

package-lock.json
packages/applications/projectors/package.json
packages/applications/projectors/src/subscribers/lauréat/représentant-légal/getSensibleDocReplacement.ts
packages/applications/projectors/src/subscribers/lauréat/représentant-légal/handleChangementReprésentantLégalAccordé.ts
packages/applications/projectors/src/subscribers/lauréat/représentant-légal/handleChangementReprésentantLégalRejeté.ts

Pourquoi un remplacement et pas une suppression ? Et bien tout simplement afin d'avoir toujours un document existant et ainsi préserver l'historique du stream d'event.

✨ Remplacement des documents sensisbles après accord ou rejet de changement de représentant légal

---

packages/applications/projectors/src/subscribers/réseau/raccordement.projector.ts
packages/specifications/src/raccordement/modifierGestionnaireRéseauRaccordement.feature
packages/specifications/src/raccordement/stepDefinitions/raccordement.then.ts
packages/specifications/src/raccordement/stepDefinitions/raccordement.when.ts

- ajout des types manquants
- merger les cas `GestionnaireRéseauAttribué`, `GestionnaireRéseauInconnuAttribué`,  `GestionnaireRéseauRaccordementModifié` 
- mettre à jour `raccordement.dossiers` et `dossier-raccordement`  en cas de `GestionnaireRéseauAttribué`, `GestionnaireRéseauInconnuAttribué`, `GestionnaireRéseauRaccordementModifié`
[Ticket](https://linear.app/startup-potentiel/issue/POT-961/investiguer-donnee-grd-inconsistante-dans-les-dossiers-de-raccordement)

🐛 Correction de la projection raccordement en cas de modification du GRD

---

packages/specifications/src/helpers/waitForSagasNotificationsAndProjectionsToFinish.ts
packages/specifications/src/projet/lauréat/garantiesFinancières/en-attente/stepDefinitions/garantiesFinancièresEnAttente.given.ts
packages/specifications/src/projet/lauréat/garantiesFinancières/mainlevée/stepDefinitions/mainlevéeGarantiesFinancières.given.ts
packages/specifications/src/projet/lauréat/stepDefinitions/lauréat.given.ts
packages/specifications/src/raccordement/stepDefinitions/raccordement.given.ts
packages/specifications/src/raccordement/stepDefinitions/raccordement.then.ts
packages/specifications/src/raccordement/stepDefinitions/raccordement.when.ts
packages/specifications/src/setup.ts
packages/specifications/src/tâche/stepDefinitions/tâche.then.ts

Dans cette PR je reprends la fonction helpers qui s'appelait waitForEvents() et je lui applique deux changements : 
- renommage en waitForSagasNotificationsAndProjectionsToFinish() pour plus de clareté
- application de ce helper dans le setup  (dans l'After Step) en ciblant les .given et .when uniquement (il n'y aura que eux qui vont avoir besoin d'attendre que l'event émis soit traité)

✅ Wait event finish for sagas / notifs / projections in setup

---

packages/domain/candidature/src/notifier/notifierCandidature.behavior.ts
packages/domain/période/src/notifier/notifierPériode.command.ts
packages/specifications/src/période/notifierPériode.feature
packages/specifications/src/période/stepDefinitions/période.when.ts
packages/specifications/src/utilisateur/fixtures/validateur.fixture.ts
packages/specifications/src/utilisateur/stepDefinitions/utilisateur.given.ts

Sans ces informations, la notification serait incomplète et le rattrapage compliqué, mieux vaut planter directement. 
J'ai également ajouté que si toutes les notifications de candidat sont en erreur, alors le use case notifier période est également en erreur. Ce comportement n'est pas idéal, peut-être vaudrait-il mieux planter à la première erreur... J'ai pris ce parti pour limiter les changements dans cette PR qui n'a pas pour objectif de changer le comportement des erreurs

✨ Impossible de notifier une période sans nom ou fonction

---

packages/applications/ssr/src/components/atoms/form/document/DownloadDocument.tsx

Pour afficher PDF et non "application/pdf" quand on passe le format du document en paramètre :
```ts
<DownloadDocument
label="Télécharger la pièce justificative"
format={pièceJustificative.format} //ici la valeur est application/pdf
{...} 
/>
```

✨ Accepter le mimeType pour le format du document à télécharger

---

packages/applications/scheduled-tasks/backup-3-2-1.sh

Nous utilisons comme CHECK_IN_ID la date car sur les container scalingo la fonction uuidgen n'est pas présente ou inaccessible avec notre utilisateur

🔊 Utilisation de sentry pour monitorer la tâche cron du backup 3-2-1

---

packages/applications/legacy/src/controllers/upload.ts
packages/applications/ssr/src/utils/zod/blob/cannotExceedSize.ts

Autoriser l'upload de fichiers jusqu'à 25 mo
Interface

🎨 Autoriser les fichiers jusqu'à 25 mo

---

packages/applications/legacy/src/views/components/UI/molecules/Alertes/SuccessBox.tsx
packages/applications/ssr/src/components/atoms/form/FormSuccessAlert.tsx
packages/applications/ssr/src/components/pages/réseau/gestionnaire/ajouter/ajouterGestionnaireRéseau.action.ts
packages/applications/ssr/src/components/pages/réseau/raccordement/corriger-par-lot/corrigerRéférencesDossier.action.ts
packages/applications/ssr/src/components/pages/réseau/raccordement/corriger/corrigerRéférenceDossier.action.ts

Impossible de le faire facilement pour le legacy comme le composant alerte a été recodé...
Visuel si alerte dans le SSR (ne marche pas sur les alertes page projet)

🐛  Fix: url for success box ssr

---

packages/applications/ssr/src/components/molecules/historique/timeline/abandon/mapToAbandonDemandéTimelineItemProps.tsx
packages/applications/ssr/src/components/molecules/historique/timeline/abandon/mapToAbandonTimelineItemProps.tsx
packages/domain/lauréat/src/abandon/index.ts

Suite à une V2 de l'event, l'historique affichait "étape inconnue" car l'event n'était pas trigger
J'ai fixé le cas, mais il faudrait typer HistoryRecord pour qu'il soit suffisament intelligent pour bloquer si on rajoute un event sans qu'il soit représenté ici

🐛 AbandonDemandé-V2 doit être représenté dans l'historique abandon

---

packages/applications/legacy/src/controllers/userAccount/postSignup.ts

⚠️  Cette PR est full legacy. J'ai fais le choix de faire la vérification en amont en utilisant l'adapter récupérerUtilisateur plutôt que modifier le legacy des useCase (difficile à maintenir). Ce code est temporaire puisqu'il sera prochainement ré-écrit en fonction des choix fait sur la partie migration du module utilisateur ⚠️

🐛 Empecher de créer un utilisateur de type porteur avec un email déjà utilisé par un compte utilisateur Potentiel (désactivé ou non)

---

packages/applications/projectors/package.json
packages/applications/projectors/src/infrastructure/updateOneProjection.test.ts
packages/applications/projectors/src/infrastructure/updateOneProjection.ts

Dans des cas où une string contient des caractères du type ", ' ou \n... , l'update avec `updateOneProjection` ne fonctionne pas

🐛 Gérer les caractères spéciaux dans `updateOneProjection`

---

packages/applications/legacy/.env.template
packages/applications/ssr/.env.template
packages/applications/ssr/src/app/candidatures/[identifiant]/corriger/page.tsx
packages/applications/ssr/src/components/molecules/CommunePicker.tsx
packages/applications/ssr/src/components/pages/candidature/corriger/CorrigerCandidature.form.tsx
packages/applications/ssr/src/components/pages/candidature/corriger/corrigerCandidature.action.ts
packages/applications/ssr/src/utils/zod/candidature/candidature.schema.ts
packages/applications/ssr/src/utils/zod/candidature/candidatureFields.schema.ts
packages/specifications/src/candidature/importerCandidature.feature

Changements : 
- un picker pour la commune, qui préremplit le codePostal (mais reste éditable dans un premier temps) et la région/département, basé sur l'[API Géo](https://geo.api.gouv.fr/)
- la région / département provient donc de l'API et plus du référentiel hard-codé. Le référentiel hard-codé reste pour l'import via CSV pour le moment

✨ Commune Picker dans le formulaire de correction de candidature

---

.database/scripts/update-metabase-dump.sh
.database/scripts/update-potentiel-dump.sh
.docker-scripts/up-test.sh
.docker-scripts/up.sh

https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash

🔨 Fix script shebang

---

packages/applications/legacy/.env.template
packages/applications/request-context/src/authOptions.ts
packages/applications/request-context/src/getLogoutUrl.ts
packages/applications/routes/src/auth/auth.routes.ts
packages/applications/ssr/.env.template
packages/applications/ssr/src/app/auth/signIn/page.tsx
packages/applications/ssr/src/app/auth/signOut/page.tsx
packages/applications/ssr/src/components/molecules/SignOutProConnect.tsx

Si l'utilisateur n'est pas autorisé sur Potentiel, il risque de ne pas pouvoir se déconnecter de proconnect. Ceci impacte surtout les envs de test car on utilise plusieurs comptes, mais pourrait arriver en prod si quelqu'un a plusieurs comptes proconnect.

🐛 Permettre la déconnexion de proconnect si l'utilisateur n'est pas autorisé

---

packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx

=> https://linear.app/startup-potentiel/issue/POT-1064/informations-sur-le-raccordement-dun-projet
CRE
ADMIN

🎨 Nouvel affichage pour raccordement sur la page projet 

---

packages/applications/projectors/src/infrastructure/updateManyProjections.ts
packages/applications/projectors/src/infrastructure/updateOneProjection.ts
packages/applications/projectors/src/subscribers/lauréat/abandon/abandonAccordé.projector.ts
packages/applications/projectors/src/subscribers/lauréat/abandon/abandonConfirmé.projector.ts
packages/applications/projectors/src/subscribers/lauréat/abandon/abandonPasséEnInstruction.projector.ts
packages/applications/projectors/src/subscribers/lauréat/abandon/abandonRejeté.projector.ts
packages/applications/projectors/src/subscribers/lauréat/abandon/confirmationAbandonDemandée.projector.ts

Avant ce changement, le Partial n'était appliqué qu'aux propriétés à la racine: cette PR permet de modifier un sous objet.
Malheureusement je n'ai pas réussi à faire fonctionner `DeepPartial` avec `AtLeastOne` mais il me semble que AtLeastOne est moins important, car il est peu probable d'oublier de spécifier un champs à mettre à jour (ou si c'est le cas, les tests le montreront), alors que l'absence de DeepPartial cause un problème d'utilisation actuellement.

🐛 Corriger le type de `updateOneProjection` pour permettre de modifier un sous-objet

---

packages/applications/ssr/src/app/candidatures/page.tsx
packages/applications/ssr/src/components/atoms/LinkAction.tsx
packages/applications/ssr/src/components/molecules/ListFilters.tsx
packages/applications/ssr/src/components/organisms/ListHeader.tsx
packages/applications/ssr/src/components/pages/réseau/gestionnaire/lister/GestionnaireRéseauList.page.tsx
packages/applications/ssr/src/components/templates/ListPage.template.tsx

LinkAction : voir page gestionnaire réseau. Jusque là l'icone est hard-codée, on peut désormais la personaliser au besoin
Filtres: un paramètre de filtre (ie AppelOffre) peut maintenant affecter plusieurs autres paramètres (ie les reset quand on change appelOffre par exemple)

✨ Personaliser l'icône du LinkAction + plusieurs filtres affectés

---

packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getAbandon.ts
packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeader.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/AbandonInfoBox.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact.tsx
packages/applications/ssr/src/app/elimine/[identifiant]/recours/page.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/abandon/page.tsx
packages/applications/ssr/src/components/pages/abandon/détails/DétailsAbandon.page.tsx
packages/applications/ssr/src/components/pages/abandon/détails/passerEnInstruction/PasserAbandonEnInstruction.form.tsx
packages/applications/ssr/src/components/pages/recours/détails/DétailsRecours.page.tsx
packages/applications/ssr/src/components/pages/recours/détails/passerEnInstruction/PasserRecoursEnInstruction.form.tsx
packages/domain/lauréat/src/abandon/abandon.aggregate.ts
packages/domain/lauréat/src/abandon/instruire/passerAbandonEnInstruction.behavior.ts
packages/domain/éliminé/src/recours/instruire/passerRecoursEnInstruction.behavior.ts
packages/domain/éliminé/src/recours/recours.aggregate.ts
packages/specifications/src/projet/lauréat/abandon/passerAbandonEnInstruction.feature
packages/specifications/src/projet/lauréat/abandon/stepDefinitions/abandon.given.ts
packages/specifications/src/projet/lauréat/abandon/stepDefinitions/abandon.when.ts
packages/specifications/src/projet/éliminé/recours/passerRecoursEnInstruction.feature
packages/specifications/src/projet/éliminé/recours/stepDefinitions/recours.when.ts
packages/specifications/src/utilisateur/fixtures/admin.fixture.ts

- Reprendre l'instruction pour un admin
- Domain
- front
- Mini changement pour l'affichage de l'abandon sur la page projet

✨ Reprendre l'instruction pour un recours ou un abandon ETQ Admin

---

packages/infrastructure/pg-event-sourcing/src/subscribe/eventStreamEmitter.ts
packages/infrastructure/pg-event-sourcing/src/subscribe/subscribe.test.ts
packages/infrastructure/pg-event-sourcing/src/subscribe/subscribe.ts

Ces changements permettent de gérer les déconnexions du client postgresql des subscribers permettant d'alimenter les projections, de notifier par email ou encore d'exécuter les comportements métier de l'application legacy.
Lors d'une erreur on tente de se reconnecter 10 fois (grâce à une policy avec un ExponentialBackoff).
Après une reconnection il faut bien entendu réessayer le traitement des pending acknowledgments qui ont pu avoir lieu entre temps.

🥅 Ajout d'un mécanisme de reconnection des subscribers en cas de déconnection

---

packages/applications/legacy/src/sequelize.config.ts
packages/applications/request-context/src/authOptions.ts
packages/infrastructure/pg-event-sourcing/src/subscribe/subscribe.ts
packages/libraries/pg-helpers/src/usePoolClient.ts

permet une meilleure analyse des connections ouvertes
exemple avec cette query
```
SELECT *
FROM pg_stat_activity
where datname = 'potentiel'
```

🔧 Ajouter un application_name aux connections Postgres

---

package-lock.json
packages/applications/bootstrap/src/setupLauréat.ts
packages/applications/notifications/src/subscribers/lauréat/puissance/changementPuissanceRejeté.notification.ts
packages/applications/notifications/src/subscribers/lauréat/puissance/index.ts
packages/applications/projectors/src/subscribers/lauréat/puissance/changementPuissanceRejeté.projector.ts
packages/applications/projectors/src/subscribers/lauréat/puissance/index.ts
packages/domain/lauréat/src/puissance/changement/accorder/accorderChangementPuissance.behavior.ts
packages/domain/lauréat/src/puissance/changement/errors.ts
packages/domain/lauréat/src/puissance/changement/rejeter/rejeterChangementPuissance.behavior.ts
packages/domain/lauréat/src/puissance/changement/rejeter/rejeterChangementPuissance.command.ts
packages/domain/lauréat/src/puissance/changement/rejeter/rejeterChangementPuissance.usecase.ts
packages/domain/lauréat/src/puissance/index.ts
packages/domain/lauréat/src/puissance/puissance.aggregate.ts
packages/domain/lauréat/src/puissance/puissance.register.ts
packages/specifications/src/projet/lauréat/puissance/changement/accorderChangementPuissance.feature
packages/specifications/src/projet/lauréat/puissance/changement/annulerChangementPuissance.feature
packages/specifications/src/projet/lauréat/puissance/changement/changementPuissance.world.ts
packages/specifications/src/projet/lauréat/puissance/changement/fixture/rejeterChangementPuissance.fixture.ts
packages/specifications/src/projet/lauréat/puissance/changement/rejeterChangementPuissance.feature
packages/specifications/src/projet/lauréat/puissance/changement/stepDefinitions/changementPuissance.given.ts
packages/specifications/src/projet/lauréat/puissance/changement/stepDefinitions/changementPuissance.then.ts
packages/specifications/src/projet/lauréat/puissance/changement/stepDefinitions/changementPuissance.when.ts
packages/specifications/src/projet/lauréat/puissance/puissance.world.ts
packages/specifications/src/projet/lauréat/puissance/stepDefinitions/puissance.then.ts

- **✅ La DREAL associée au projet rejette le changement de puissance d'un projet lauréat**
- **✅ Le DGEC validateur rejette le changement de puissance d'un projet lauréat**
- **✅ Impossible de rejeter une demande de changement de puissance à la hausse d'un projet lauréat pour un utilisateur DREAL**
- **✅ Impossible de rejeter une demande de changement de puissance à la baisse d'un projet lauréat pour un utilisateur DGEC**
- **✅ Impossible de rejeter le changement de puissance d'un projet lauréat si aucune demande n'est en cours**
- **✅ Impossible de rejeter le changement de puissance d'un projet lauréat si la demande a déjà été accordée**
- **✅ Impossible de rejeter le changement de puissance d'un projet lauréat si la demande a déjà été annulée**
- **✅ Impossible de rejeter le changement …

✨ Rejeter une demande de changement de puissance - Domain

---

packages/applications/cli/src/commands/files/backup.ts

Utilisation :
dans le .env :
```
#Source 
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
S3_BUCKET=
S3_ENDPOINT=
S3_BACKUP_BUCKET=potentiel
S3_BACKUP_ENDPOINT=http://localhost:9000
S3_BACKUP_AWS_ACCESS_KEY_ID=minioadmin
S3_BACKUP_AWS_SECRET_ACCESS_KEY=minioadmin
```
Run: 
```bash
potentiel-cli files backup --progress
npx tsx ./bin/dev.js files backup --progress 
```
éventuellement, le flag `--recover` peut être utilisé pour reprendre la copie en cas d'interruption

✨ Commande CLI pour effectuer un backup des fichiers

---

packages/applications/ssr/src/components/pages/réclamer-projets/réclamer/réclamerProjet.action.ts
packages/applications/ssr/src/utils/withRateLimit.ts

Dans le cas spécifique de Réclamer, l'identifiant projet est chiffré (car le numéro CRE est demandé comme preuve que le porteur connait ce projet)
Donc la clé change à chaque chargement de la page...

🐛 Correction de la clé du rate limiter, qui change à chaque chargement

---

packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getActionnaire.ts
packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getProducteur.ts
packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getPuissance.ts
packages/applications/legacy/src/controllers/project/getProjectPage/_utils/getReprésentantLégal.ts
packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectActions.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/components/ProjectHeader.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/Contact.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoActionnaire.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/InfoPuissance.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoProducteur.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoReprésentantLégal.tsx
packages/applications/ssr/src/components/pages/puissance/changement/demander/DemanderChangementPuissanceFormErrors.tsx
packages/domain/utilisateur/src/role.valueType.ts

- ETQ PP, dans l'onglet Actions : Au lieu d'afficher la modification, afficher le lien vers une demande si demande présente (pour toutes les demandes)
- ETQ Admin et Dreal : avoir accès à mes vraies actions
- Alignement ReprésentantLégal sur les autres demandes (wording et fonctionnement)
- Petit fix avec les modificationscahierdescharges (les actions admin / dreal ne s'affichaient pas sur la page projet sinon)
Pas mal de tests visuels

🎨 Alignement des actions (dreal, admin, pp) dans le legacy pour les demandes

---

package-lock.json
packages/applications/cli/package.json
packages/applications/cli/src/commands/tache/achever.ts
packages/applications/ssr/src/components/pages/tâche/TâcheListItem.tsx
packages/domain/tâche/src/tâche.ts

Changer le lien en cas de gestionnaire réseau inconnu afin de rediriger vers la page de DCR
CLI pour achever une tâche, pour permettre de supprimer des tâches qui ne devraient pas exister

🐛 Corrections sur les tâches de raccordement + CLI pour achever une tâche

---

.docker-scripts/up.sh
.github/workflows/shared-workflow.yml
package.json

temps de build réduit pour vérifier statistiques + ajout d'un délai pour laisser le temps à la DB (visiblement pg_isready ne suffit pas complètement...)

👷 Correction du step Vérifier statistiques

---

packages/applications/legacy/src/views/pages/projectDetailsPage/sections/EtapesProjet.tsx
packages/applications/ssr/src/app/laureats/[identifiant]/historique/page.tsx
packages/applications/ssr/src/utils/historique/mapToProps/achèvement/events/mapToAttestationConformitéTransmiseTimelineItemProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/garanties-financières/events/mainlevée/mapToDemandeMainlevéeGarantiesFinancièresAccordéeTimelineItemsProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/raccordement/events/gestionnaire-réseau/mapToGestionnaireRéseauAttribuéTimelineItemProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/raccordement/events/gestionnaire-réseau/mapToGestionnaireRéseauRaccordementModifiéTimelineItemProps.tsx

- **🐛 Ordonner correctement les éléments de l'historique avant leur mapping**
- **✨ Affichage du courrier de main levée accordée**
- **💄 Ne pas afficher le liens pour accéder au référentiel de gestionnaire de réseau**
- **💄 Ajout du lien pour accéder à la preuve de transmission au cocontractant**
- **💄 Meilleure identification du dernier élément des étapes du projet**

💄 Améliorations de l'affichage de l'historique d'un projet

---

packages/applications/legacy/src/controllers/project/getProjectPage/index.ts
packages/applications/legacy/src/views/pages/projectDetailsPage/ProjectDetails.tsx
packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx
packages/specifications/src/projet/lauréat/abandon/accorderAbandon.feature
packages/specifications/src/projet/lauréat/abandon/demanderPreuveRecandidature.feature

- **🐛 Utilisation de la bonne date pour l'historique de la transmission de la PTF (#3185)**
- **Amélioration de l'impression de l'historique projet (#3188)**
- **🐛 Hotfix get laureat (#3195)**
- **✨ Permettre la modification depuis la page projet des données d'achèvement (#3200)**

🔀 Intégration des modifications de la release 3.53

---

packages/applications/cli/src/hooks/init/config.ts
packages/libraries/monitoring/src/logger.test.ts
packages/libraries/monitoring/src/logger.ts
packages/libraries/monitoring/src/winston/console.transport.ts

:warning: Modification du format par défaut des métadonnées, pas très exploitable actuellement. 
Cette PR améliore la gestion des métadonnées dans les logs, en permettant par exemple d'en précisant des globales qui seront toujours spécifiées. 
C'est utile dans le contexte de la CLI, où on aimerait pouvoir trouver les logs d'une éxecution donnée,  et savoir à quelle commande celà correspond.

✨ Gestion des métadonnées par défaut dans le logger, et ajout de métadonnées à la CLI

---

packages/domain/projet/src/lauréat/achèvement/achèvement.aggregate.ts
packages/domain/projet/src/lauréat/achèvement/calculerDateAchèvementPrévisionnel/calculerDateAchèvementPrévisionnel.option.ts
packages/domain/projet/src/lauréat/cahierDesCharges/choisir/choisirCahierDesCharges.usecase.ts
packages/domain/projet/src/lauréat/lauréat.aggregate.ts
packages/specifications/src/projet/lauréat/achèvement/calculerDateAchèvementPrévisionnel.feature

- **🧪 Calculer la date d'achèvement prévisionnel lorsqu'un projet lauréat change son cahier des charges par le CDC du 30/08/2022**
- **✅ Calculer la date d'achèvement prévisionnel lorsqu'un projet lauréat change son cahier des charges par le CDC du 30/08/2022**

✨ Ajouter 18 mois à la date d'achèvement prévisionnel si le CDC paru le 30/08/2022 est séléctionné

---

packages/applications/ssr/src/app/reseaux/gestionnaires/[identifiant]/raccordements/mise-en-service-en-attente:exporter/route.ts
packages/applications/ssr/src/utils/apiAction.ts
packages/domain/projet/src/accès/accès.error.ts
packages/domain/projet/src/lauréat/raccordement/errors.ts
packages/domain/utilisateur/src/errors.ts

L'erreur API est systématiquement `Opération rejetée`, ce qui restreint la compréhension. 
Par ailleurs,  de nombreuses erreurs `OperationRejectedError` ne sont pas des problèmes de permissions mais simplement une opération impossible, donc une `InvalidOperationError`.

🥅 Clarifier les erreurs dans l'API et harmoniser le type d'erreur

---

packages/applications/ssr/src/app/laureats/changements/abandon/page.tsx
packages/applications/ssr/src/app/laureats/changements/delai/page.tsx
packages/applications/ssr/src/app/laureats/changements/puissance/page.tsx

Discussion avec le métier
Vio : très facile de changer, pour info on a le même comportement sur puissance et abandon (seuls DGEC et DREAL peuvent filtrer), qu'en dis tu ? Devrait on autoriser tous les utilisateurs à voir le filtre ?
Mat : Je pense que l'on devait autoriser tous les utilisateurs ayant accès à la page d'avoir également accès au filtre

🐛 Correction d'un bug de visibilité de filtre sur puissance, abandon et délai

---

packages/applications/ssr/src/app/laureats/[identifiant]/(détails)/modifier/modifierLauréat.action.ts

Avant dans modifierLauréat action, concernant la partie "candidature", pour les informations relative à l'autorisation d'urbanisme on retournait `undefined` s'il n'y avait pas de modification sur ces données ce qui est une erreur. Avec cette correction on va récupérer les précédentes valeurs lorsqu'elles existent.

🐛 Permettre de modifier la candidature depuis le projet lauréat

---

packages/applications/ssr/src/app/laureats/[identifiant]/historique/page.tsx
packages/applications/ssr/src/utils/historique/mapToProps/actionnaire/events/mapToActionnaireModifiéTimelineItemsProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/actionnaire/events/mapToChangementActionnaireSuppriméTimelineItemProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/actionnaire/mapToActionnaireTimelineItemProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/délai/events/mapToDemandeDélaiSuppriméeTimelineItemProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/puissance/events/mapToChangementPuissanceAnnuléTimelineItemProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/puissance/events/mapToChangementPuissanceSuppriméTimelineItemProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/puissance/index.tsx
packages/applications/ssr/src/utils/historique/mapToProps/représentant-légal/events/mapToChangementReprésentantLégalSuppriméTimelineItemProps.tsx
packages/applications/ssr/src/utils/historique/mapToProps/représentant-légal/mapToReprésentantLégalTimelineItemProps.tsx

Changement des icônes en passant, [carte](https://linear.app/startup-potentiel/issue/POT-1818/historisation-de-lannulation-des-demandes-en-cours-suite-a-validation)

♻️ Affichage des événement de suppression de demandes suite à abandon dans la frise

---

packages/applications/legacy/src/views/pages/projectDetailsPage/sections/InfoGenerales/index.tsx

Ne pas afficher le message lorsque l'attestation est déjà enregistrée

Mauvais message attestation GF attendue
